[pytest]
filterwarnings =
    ignore:Please use `import python_multipart` instead\.:PendingDeprecationWarning:starlette\.formparsers
    ignore:.*on_event is deprecated, use lifespan event handlers instead\..*:DeprecationWarning:server
    ignore:.*on_event is deprecated, use lifespan event handlers instead\..*:DeprecationWarning:fastapi\.applications
    ignore::DeprecationWarning:server
    ignore::DeprecationWarning:fastapi\.applications