"""TRACK 15.42 · ReportLab parallel of the pdf_branding foundation.

Same semantics as the WeasyPrint HTML helpers in `pdf_branding.py`:
* White-label config from env vars (`PDF_BRAND_*`).
* Audit block (record id · source module · project · version · env · generated by/on).
* Metadata block (doc type · doc id · project# · generated · env).

Both renderers share `pdf_branding.get_white_label()` and
`PDF_FOUNDATION_VERSION` so MASCI defaults and version stamps stay in
lock-step across the engine boundary.

Public API:
    draw_audit_block_flowable(...) -> Flowable
    draw_metadata_block_flowable(...) -> Flowable
    draw_universal_footer(canvas, doc) -> None   # @bottom page chrome
    build_brand_header_flowable(...) -> Flowable # top brand bar
    PageNumCanvas (canvas.Canvas subclass for "Page X of Y")

Adoption pattern (additive — never strip existing flowables):
    from pdf_branding_rl import (
        draw_audit_block_flowable, draw_metadata_block_flowable,
    )
    ...
    flowables.append(draw_metadata_block_flowable(document_type="...", ...))
    # existing flowables stay above/below — DO NOT touch them
    flowables.append(draw_audit_block_flowable(record_id="...", ...))
"""
from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas as _rl_canvas
from reportlab.platypus import (
    Flowable, KeepTogether, Paragraph, Spacer, Table, TableStyle,
)

from pdf_branding import (
    PDF_FOUNDATION_VERSION,
    _env_tag,
    get_white_label,
)


# ───────────────────────── PARAGRAPH STYLES ─────────────────────────────────

_AUDIT_LABEL_STYLE = ParagraphStyle(
    name="t1541_audit_label",
    fontName="Courier-Bold",
    fontSize=6.5,
    leading=8,
    textColor=colors.HexColor("#64748b"),
    spaceAfter=0,
)

_AUDIT_VALUE_STYLE = ParagraphStyle(
    name="t1541_audit_value",
    fontName="Courier",
    fontSize=7.5,
    leading=9.5,
    textColor=colors.HexColor("#0f172a"),
    spaceAfter=0,
)

_AUDIT_TITLE_STYLE = ParagraphStyle(
    name="t1541_audit_title",
    fontName="Courier-Bold",
    fontSize=7,
    leading=9,
    textColor=colors.HexColor("#475569"),
    spaceAfter=4,
)

_META_STYLE = ParagraphStyle(
    name="t1541_meta",
    fontName="Courier",
    fontSize=7,
    leading=9,
    textColor=colors.HexColor("#475569"),
    spaceAfter=4,
)


# ───────────────────────── AUDIT BLOCK (Flowable) ───────────────────────────


def draw_audit_block_flowable(
    *,
    record_id: str,
    source_module: str,
    project: Optional[str] = None,
    document_version: Optional[str] = None,
    generated_by: Optional[str] = None,
    generated_at: Optional[datetime] = None,
) -> Flowable:
    """Returns a Platypus Flowable wrapping the audit block as a
    KeepTogether table. Caller appends this to their `flowables` list
    AFTER all existing operational content.
    """
    wl = get_white_label()
    when = (generated_at or datetime.now(timezone.utc)).strftime(
        "%Y-%m-%d %H:%M:%S UTC",
    )
    rows = [
        ("Record ID", record_id),
        ("Source Module", source_module),
        ("Project", project or "—"),
        ("Document Version", document_version or PDF_FOUNDATION_VERSION),
        ("Generated By", generated_by or "system"),
        ("Generated On", when),
        ("Environment", _env_tag()),
        ("Foundation", f"v{PDF_FOUNDATION_VERSION}"),
    ]
    data = [[
        Paragraph(f"<b>{_xml_safe(k)}</b>", _AUDIT_LABEL_STYLE),
        Paragraph(_xml_safe(str(v)), _AUDIT_VALUE_STYLE),
    ] for k, v in rows]

    title = Paragraph(
        f"AUDIT TRAIL \u00B7 FOUNDATION v{PDF_FOUNDATION_VERSION}",
        _AUDIT_TITLE_STYLE,
    )
    tbl = Table(
        data,
        colWidths=[1.4 * inch, 4.6 * inch],
        hAlign="LEFT",
        spaceBefore=0,
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#f8fafc")),
        ("BOX",        (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("LINEBEFORE", (0, 0), (0, -1), 2.5, colors.HexColor(f"#{wl.brand_color}")),
        ("LEFTPADDING",   (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 4),
        ("TOPPADDING",    (0, 0), (-1, -1), 1.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1.5),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
    ]))
    return KeepTogether([
        Spacer(1, 8),
        title,
        tbl,
    ])


# ───────────────────────── METADATA BLOCK (Flowable) ────────────────────────


def draw_metadata_block_flowable(
    *,
    document_type: str,
    document_id: Optional[str] = None,
    project_number: Optional[str] = None,
    extra: Optional[dict] = None,
) -> Flowable:
    """Returns a small monospace metadata strip Flowable for use just
    after the brand header. Mirrors `build_metadata_block_html`."""
    when = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts = [
        f"<b>DOCTYPE:</b> {_xml_safe(document_type)}",
    ]
    if document_id:
        parts.append(f"<b>DOCID:</b> {_xml_safe(str(document_id))}")
    if project_number:
        parts.append(f"<b>PROJECT#:</b> {_xml_safe(str(project_number))}")
    parts.append(f"<b>GENERATED:</b> {_xml_safe(when)}")
    parts.append(f"<b>ENV:</b> {_xml_safe(_env_tag())}")
    if extra:
        for k, v in extra.items():
            if v:
                parts.append(f"<b>{_xml_safe(str(k).upper())}:</b> {_xml_safe(str(v))}")
    text = " \u00B7 ".join(parts)
    return Paragraph(text, _META_STYLE)


# ───────────────────────── UNIVERSAL FOOTER CALLBACK ────────────────────────


def draw_universal_footer(canvas: _rl_canvas.Canvas, doc) -> None:
    """ReportLab `onPage` callback that paints the universal footer:
    `<tagline> · Page X of Y` along the bottom of every page. Pass this
    as `onFirstPage`/`onLaterPages` to a SimpleDocTemplate.build()
    call. Caller's existing onPage callback can chain to this for
    backward compat.
    """
    canvas.saveState()
    wl = get_white_label()
    width, _height = canvas._pagesize  # type: ignore[attr-defined]
    tagline = wl.footer_tagline
    page_num = canvas.getPageNumber()
    # We don't know total pages without two-pass; use the PageNumCanvas
    # subclass below for "Page X of Y" rendering. As a graceful default
    # this callback prints only the current page.
    canvas.setFont("Courier-Bold", 6.5)
    canvas.setFillColor(colors.HexColor("#334155"))
    canvas.drawString(0.5 * inch, 0.35 * inch, tagline[:120])
    canvas.drawRightString(
        width - 0.5 * inch, 0.35 * inch,
        f"Page {page_num}",
    )
    canvas.restoreState()


class PageNumCanvas(_rl_canvas.Canvas):
    """Two-pass canvas that injects `Page X of Y` into the bottom-right
    of every page on `save()`. Use with `SimpleDocTemplate.build(...,
    canvasmaker=PageNumCanvas)` to get total-page-aware footers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: list = []

    def showPage(self):  # noqa: N802 — reportlab API
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_page_of_total(total)
            super().showPage()
        super().save()

    def _draw_page_of_total(self, total: int) -> None:
        self.saveState()
        wl = get_white_label()
        width, _h = self._pagesize  # type: ignore[attr-defined]
        self.setFont("Courier-Bold", 6.5)
        self.setFillColor(colors.HexColor("#334155"))
        self.drawString(
            0.5 * inch, 0.35 * inch,
            (wl.footer_tagline or "")[:120],
        )
        self.drawRightString(
            width - 0.5 * inch, 0.35 * inch,
            f"Page {self.getPageNumber()} of {total}",
        )
        self.restoreState()


# ───────────────────────── BRAND HEADER (Flowable) ──────────────────────────


def build_brand_header_flowable(title: str, kicker: str = "") -> Flowable:
    """Top-of-document brand bar — mirrors `brand_header` in the HTML
    foundation. Returns a small Platypus Flowable so any ReportLab
    generator can prepend it without rewriting their layout."""
    wl = get_white_label()
    brand_style = ParagraphStyle(
        name="t1541_brand",
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=21,
        textColor=colors.HexColor(f"#{wl.brand_color}"),
        spaceAfter=0,
    )
    kicker_style = ParagraphStyle(
        name="t1541_kicker",
        fontName="Courier-Bold",
        fontSize=7.5,
        leading=9,
        textColor=colors.HexColor("#475569"),
        spaceAfter=0,
    )
    title_style = ParagraphStyle(
        name="t1541_title",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=17,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=6,
    )
    bits = [Paragraph(f"<b>{_xml_safe(wl.brand_name)}</b>", brand_style)]
    if kicker:
        bits.append(Paragraph(_xml_safe(kicker.upper()), kicker_style))
    if title:
        bits.append(Paragraph(_xml_safe(title), title_style))
    return KeepTogether(bits)


# ───────────────────────── XML SAFE ESCAPE ─────────────────────────────────


def _xml_safe(s: str) -> str:
    """Escape special chars for ReportLab Paragraph (which uses a
    small XML subset)."""
    if s is None:
        return ""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


__all__ = [
    "build_brand_header_flowable",
    "draw_audit_block_flowable",
    "draw_metadata_block_flowable",
    "draw_universal_footer",
    "PageNumCanvas",
]
