"""TRACK 15.42 · Extended field preservation diff (same superset rule).

Verifies AFTER ⊇ BEFORE for every PDF generated by
`track_15_42_pdf_baseline_extended.py`.
"""
from __future__ import annotations
import sys
from pathlib import Path

OUT_BASE = Path("/tmp/track_15_42")


def _fingerprints(text: str) -> set[str]:
    import re
    iso_re = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$")
    sha_re = re.compile(r"^sha256=[0-9a-f]{16}$")
    dt_iso = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})")
    dt_space = re.compile(r"\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}(?::\d{2})?(?:\s*UTC)?")
    dt_human = re.compile(
        r"[A-Z][a-z]{2,8}\s+\d{1,2},\s+\d{4}\s+\d{1,2}:\d{2}\s*[AP]M\s*UTC",
        re.IGNORECASE,
    )
    # pdfminer expands letter-spaced Courier text into "X Y Z" — collapse
    # back into "XYZ" so equality checks aren't defeated by font letter-
    # spacing differences between BEFORE and AFTER captures.
    letter_sp = re.compile(r"(?<=\w) (?=\w(?:\s|$))")
    fps = set()
    for raw in (text or "").splitlines():
        line = raw.strip()
        if not line:
            continue
        # Collapse letter-spacing
        compact_line = letter_sp.sub("", line)
        if compact_line.startswith("Page ") and "of" in compact_line:
            continue
        if compact_line.startswith("Generated 20") or compact_line.startswith("Generated  20"):
            continue
        # Skip foundation-injected dynamic chrome + ANY "Generated …"
        # banner footer line (per-render timestamp).
        upper_collapsed = re.sub(r"\s+", " ", compact_line.upper())
        if (
            upper_collapsed.startswith("GENERATED ")
            or any(tag in upper_collapsed for tag in (
                "DOCTYPE :", "DOCTYPE:",
                "DOCID :", "DOCID:",
                "PROJECT # :", "PROJECT#:",
                "GENERATED :", "GENERATED:",
                "RECORD ID", "SOURCE MODULE", "DOCUMENT VERSION",
                "GENERATED BY", "GENERATED ON",
                "ENV :", "ENV:", "ENVIRONMENT",
                "FOUNDATION V", "AUDIT TRAIL",
                "EXPORTED :", "EXPORTED:",
            ))
        ):
            continue
        compact = compact_line.replace(" ", "")
        if iso_re.match(compact):
            continue
        if sha_re.match(compact):
            continue
        # Normalize remaining timestamp forms (in case operational
        # text contains a now()-based stamp that drifts between runs)
        norm = compact_line
        norm = dt_iso.sub("<TS>", norm)
        norm = dt_space.sub("<TS>", norm)
        norm = dt_human.sub("<TS>", norm)
        fps.add(norm)
    return fps


def main():
    before_dir = OUT_BASE / "before"
    after_dir = OUT_BASE / "after"
    any_fail = False
    print(f"{'PDF':<40s} {'BEFORE':>8s} {'AFTER':>8s} {'MISSING':>8s} VERDICT")
    print("-" * 80)
    rows = sorted(p.name for p in before_dir.glob("*.txt"))
    for fn in rows:
        name = fn[:-4]
        b_path = before_dir / fn
        a_path = after_dir / fn
        if not a_path.exists():
            print(f"{name:<40s}      —        —       —  SKIP (no AFTER)")
            continue
        b_fps = _fingerprints(b_path.read_text())
        a_fps = _fingerprints(a_path.read_text())
        missing = b_fps - a_fps
        verdict = "🟢 PASS" if not missing else "🔴 FAIL"
        print(f"{name:<40s} {len(b_fps):>8d} {len(a_fps):>8d} {len(missing):>8d}  {verdict}")
        if missing:
            any_fail = True
            for m in sorted(missing)[:8]:
                print(f"    - {m!r}")
            if len(missing) > 8:
                print(f"    ... +{len(missing)-8} more")
    print("-" * 80)
    if any_fail:
        print("🔴 FIELD PRESERVATION FAIL")
        sys.exit(1)
    print("🟢 FIELD PRESERVATION PASS — extended set")


if __name__ == "__main__":
    main()
