"""Iter-32 — QA/QC Inspection routes (concrete-form, rebar, subcontractor-work).

Covers:
- POST /api/qaqc-inspections (all 3 kinds; concrete-form-only fields persisted; counts recomputed)
- Server-side PM backfill from jobs_master when payload omits pm_name/pm_email
- GET /api/qaqc-inspections (admin) — summary rows include pm_name and pm_email
- GET /api/pm/qaqc-inspections?pm=<email|name> — PM-scoped filtering, empty pm => []
- GET /api/qaqc-inspections/{id} — full doc returned, no _id leakage
- DELETE /api/qaqc-inspections/{id} — removes record
- GET /api/admin/qaqc-inspections/stats and export.csv smoke checks
"""
import os
from pathlib import Path

import pytest
import requests


def _read_kv(path: Path, key: str) -> str:
    try:
        for line in path.read_text().splitlines():
            if line.startswith(f"{key}="):
                return line.split("=", 1)[1].strip().strip('"').rstrip("/")
    except Exception:
        pass
    return ""


BASE_URL = (
    _read_kv(Path("/app/frontend/.env"), "REACT_APP_BACKEND_URL")
    or os.environ.get("REACT_APP_BACKEND_URL", "")
).rstrip("/")
ADMIN_PASSWORD = _read_kv(Path("/app/backend/.env"), "ADMIN_PASSWORD") or "Maddix123!"
PM_PASSWORD = _read_kv(Path("/app/backend/.env"), "PM_PASSWORD") or "Maddix123!"

# Project number 25-15 maps to a real PM in jobs_master (Chris Wright)
SEED_PROJECT = "25-15"
SEED_PM_NAME = "Chris Wright"
SEED_PM_EMAIL = "chriswright@mascigc.com"


# ---------- fixtures ----------

@pytest.fixture(scope="module")
def admin_token():
    r = requests.post(
        f"{BASE_URL}/api/admin/login",
        json={"password": ADMIN_PASSWORD},
        timeout=15,
    )
    if r.status_code != 200:
        pytest.skip(f"Admin login failed: {r.status_code} {r.text[:120]}")
    return r.json()["token"]


@pytest.fixture(scope="module")
def pm_token():
    r = requests.post(
        f"{BASE_URL}/api/pm/login",
        json={"password": PM_PASSWORD},
        timeout=15,
    )
    if r.status_code != 200:
        pytest.skip(f"PM login failed: {r.status_code} {r.text[:120]}")
    return r.json()["token"]


@pytest.fixture(scope="module")
def admin_headers(admin_token):
    return {"X-Admin-Token": admin_token}


@pytest.fixture(scope="module")
def pm_headers(pm_token):
    return {"X-PM-Token": pm_token}


# Bare-minimum 1x1 png data URL (small, valid placeholder)
_TINY_PNG = (
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAA"
    "DUlEQVR4nGNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg=="
)


def _base_payload(kind: str, **overrides) -> dict:
    p = {
        "inspection_kind": kind,
        "project_name": "TEST_QAQC E53F1 SR 404",
        "project_number": SEED_PROJECT,
        "location": "SR 404 Pineda",
        "client": "FDOT",
        "subcontractor_name": "TEST_Sub-Construction LLC",
        "inspection_date": "2026-05-04",
        "inspection_time": "10:30",
        "inspector_name": "TEST_Inspector",
        "work_area": "Station 12+50",
        "weather_conditions": "Sunny, 78F",
        "checklist": [
            {"key": "i1", "label": "Item 1", "result": "pass", "note": ""},
            {"key": "i2", "label": "Item 2", "result": "pass", "note": ""},
            {"key": "i3", "label": "Item 3", "result": "fail", "note": "needs rework"},
            {"key": "i4", "label": "Item 4", "result": "na", "note": ""},
        ],
        "inspection_notes": "Generated by test_qaqc_inspections_iter32",
        "deficiencies": "",
        "corrective_actions": "",
        "photos": [_TINY_PNG, _TINY_PNG, _TINY_PNG],
        "photo_captions": ["a", "b", "c"],
        "inspector_signature": _TINY_PNG,
        # pass_count/fail_count/na_count intentionally omitted — server should compute
    }
    p.update(overrides)
    return p


# ---------- module-level state for cleanup ----------
_CREATED_IDS: list[str] = []


@pytest.fixture(scope="module", autouse=True)
def _cleanup(admin_headers):
    yield
    for rid in _CREATED_IDS:
        try:
            requests.delete(
                f"{BASE_URL}/api/qaqc-inspections/{rid}",
                headers=admin_headers,
                timeout=10,
            )
        except Exception:
            pass


# ---------- tests ----------

class TestQaqcCreate:
    """POST /api/qaqc-inspections — all 3 kinds; concrete fields persist; counts recomputed."""

    def test_concrete_form_post_persists_concrete_fields(self):
        payload = _base_payload(
            "concrete_form",
            mix_design="3000 PSI #57",
            yards_ordered="14.5",
            concrete_vendor="TEST_Cemex",
        )
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["inspection_kind"] == "concrete_form"
        assert body["mix_design"] == "3000 PSI #57"
        assert body["yards_ordered"] == "14.5"
        assert body["concrete_vendor"] == "TEST_Cemex"
        # Server-side count recomputation: 2 pass / 1 fail / 1 na
        assert body["pass_count"] == 2
        assert body["fail_count"] == 1
        assert body["na_count"] == 1
        assert isinstance(body["id"], str) and len(body["id"]) >= 8
        _CREATED_IDS.append(body["id"])

    def test_rebar_post(self):
        payload = _base_payload("rebar")
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["inspection_kind"] == "rebar"
        # No concrete-only fields required for rebar — should default to ""
        assert body.get("mix_design", "") == ""
        _CREATED_IDS.append(body["id"])

    def test_subcontractor_work_post(self):
        payload = _base_payload(
            "subcontractor_work",
            work_activity="Saw cutting",
        )
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 200, r.text
        body = r.json()
        assert body["inspection_kind"] == "subcontractor_work"
        assert body["work_activity"] == "Saw cutting"
        _CREATED_IDS.append(body["id"])

    def test_unknown_kind_rejected(self):
        payload = _base_payload("not_a_kind")
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 400
        assert "inspection_kind" in r.text.lower()


class TestPmBackfill:
    """Server-side PM backfill from jobs_master when payload omits pm_name/pm_email."""

    def test_pm_backfilled_from_jobs_master(self, admin_headers):
        # Don't provide pm_name / pm_email — server should look them up
        payload = _base_payload("concrete_form", mix_design="4000 PSI", yards_ordered="8")
        # Sanity: payload has no pm_email/pm_name keys
        assert "pm_email" not in payload and "pm_name" not in payload
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 200, r.text
        rid = r.json()["id"]
        _CREATED_IDS.append(rid)

        # GET single record — pm_name + pm_email should now be present
        g = requests.get(
            f"{BASE_URL}/api/qaqc-inspections/{rid}",
            headers=admin_headers,
            timeout=15,
        )
        assert g.status_code == 200, g.text
        doc = g.json()
        assert doc.get("pm_name") == SEED_PM_NAME, f"expected pm_name backfill, got {doc.get('pm_name')!r}"
        assert (doc.get("pm_email") or "").lower() == SEED_PM_EMAIL.lower()
        assert "_id" not in doc  # never leak Mongo _id

    def test_pm_explicit_value_not_overwritten(self, admin_headers):
        payload = _base_payload(
            "rebar",
            pm_name="Override PM",
            pm_email="override@example.com",
        )
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 200
        rid = r.json()["id"]
        _CREATED_IDS.append(rid)
        g = requests.get(
            f"{BASE_URL}/api/qaqc-inspections/{rid}",
            headers=admin_headers,
            timeout=15,
        ).json()
        assert g["pm_name"] == "Override PM"
        assert g["pm_email"].lower() == "override@example.com"


class TestAdminListAndPmScoped:
    """Admin GET list + PM-scoped GET /api/pm/qaqc-inspections."""

    def test_admin_list_includes_pm_fields(self, admin_headers):
        r = requests.get(
            f"{BASE_URL}/api/qaqc-inspections",
            headers=admin_headers,
            timeout=15,
        )
        assert r.status_code == 200, r.text
        rows = r.json()
        assert isinstance(rows, list) and len(rows) > 0
        # Every summary row must expose pm_name + pm_email keys
        for row in rows[:25]:
            assert "pm_name" in row, f"missing pm_name in {row}"
            assert "pm_email" in row
            assert "id" in row and "inspection_kind" in row
        # And at least one of our created records (with backfilled PM) must surface
        ours = [row for row in rows if row["id"] in _CREATED_IDS]
        assert ours, "expected our created record(s) in admin list"
        backfilled = [row for row in ours if row.get("pm_email") == SEED_PM_EMAIL]
        assert backfilled, "expected at least one row with backfilled pm_email"

    def test_admin_list_requires_auth(self):
        # conftest auto-attaches X-Admin-Token; explicitly blank both tokens
        r = requests.get(
            f"{BASE_URL}/api/qaqc-inspections",
            headers={"X-Admin-Token": "", "X-PM-Token": ""},
            timeout=10,
        )
        assert r.status_code == 401

    def test_pm_scoped_empty_pm_returns_empty(self, admin_headers):
        r = requests.get(
            f"{BASE_URL}/api/pm/qaqc-inspections?pm=",
            headers=admin_headers,
            timeout=15,
        )
        assert r.status_code == 200, r.text
        assert r.json() == []

    def test_pm_scoped_by_email_filters(self, admin_headers):
        r = requests.get(
            f"{BASE_URL}/api/pm/qaqc-inspections",
            params={"pm": SEED_PM_EMAIL},
            headers=admin_headers,
            timeout=15,
        )
        assert r.status_code == 200, r.text
        rows = r.json()
        assert isinstance(rows, list)
        assert len(rows) > 0, "expected backfilled record to surface for chriswright"
        for row in rows:
            assert (row.get("pm_email") or "").lower() == SEED_PM_EMAIL.lower()

    def test_pm_scoped_by_name_filters(self, admin_headers):
        r = requests.get(
            f"{BASE_URL}/api/pm/qaqc-inspections",
            params={"pm": SEED_PM_NAME},
            headers=admin_headers,
            timeout=15,
        )
        assert r.status_code == 200, r.text
        rows = r.json()
        for row in rows:
            assert row.get("pm_name") == SEED_PM_NAME

    def test_pm_scoped_unknown_pm_returns_empty(self, admin_headers):
        r = requests.get(
            f"{BASE_URL}/api/pm/qaqc-inspections",
            params={"pm": "nobody_at_all@example.com"},
            headers=admin_headers,
            timeout=15,
        )
        assert r.status_code == 200
        assert r.json() == []

    def test_pm_scoped_accepts_pm_token(self, pm_headers):
        # require_admin accepts admin OR PM tokens — verify with PM token
        r = requests.get(
            f"{BASE_URL}/api/pm/qaqc-inspections",
            params={"pm": SEED_PM_EMAIL},
            headers=pm_headers,
            timeout=15,
        )
        assert r.status_code == 200, r.text

    def test_pm_scoped_requires_auth(self):
        r = requests.get(
            f"{BASE_URL}/api/pm/qaqc-inspections",
            params={"pm": SEED_PM_EMAIL},
            headers={"X-Admin-Token": "", "X-PM-Token": ""},
            timeout=10,
        )
        assert r.status_code == 401


class TestStatsAndDelete:
    def test_stats_endpoint(self, admin_headers):
        r = requests.get(
            f"{BASE_URL}/api/admin/qaqc-inspections/stats",
            headers=admin_headers,
            timeout=15,
        )
        assert r.status_code == 200, r.text
        body = r.json()
        assert "total" in body and isinstance(body["total"], int)
        assert "by_kind" in body and isinstance(body["by_kind"], list)
        kinds = {row["kind"] for row in body["by_kind"]}
        assert {"concrete_form", "rebar", "subcontractor_work"}.issubset(kinds)

    def test_delete_record(self, admin_headers):
        # Create a throwaway record explicitly for delete
        payload = _base_payload("rebar")
        r = requests.post(f"{BASE_URL}/api/qaqc-inspections", json=payload, timeout=20)
        assert r.status_code == 200
        rid = r.json()["id"]

        d = requests.delete(
            f"{BASE_URL}/api/qaqc-inspections/{rid}",
            headers=admin_headers,
            timeout=15,
        )
        assert d.status_code == 200
        assert d.json().get("deleted") is True

        # Verify removal — GET should 404
        g = requests.get(
            f"{BASE_URL}/api/qaqc-inspections/{rid}",
            headers=admin_headers,
            timeout=10,
        )
        assert g.status_code == 404
