import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowLeft,
  Bell,
  BookOpen,
  Briefcase,
  ClipboardCheck,
  Download,
  FileText,
  HardHat,
  Home,
  LogOut,
  Package,
  Printer,
  Search,
  Settings,
  Share2,
  ShieldCheck,
  Trash2,
  Truck,
  Upload,
  UserRound,
  Wrench,
  X,
} from "lucide-react";

export const SEMANTIC_ICON_REGISTRY = {
  admin: Briefcase,
  archive: Archive,
  back: ArrowLeft,
  close: X,
  dailyReports: FileText,
  delete: Trash2,
  download: Download,
  equipment: Wrench,
  fleet: Truck,
  home: Home,
  hr: UserRound,
  inspection: ClipboardCheck,
  notifications: Bell,
  print: Printer,
  qaqc: ClipboardCheck,
  safety: ShieldCheck,
  search: Search,
  settings: Settings,
  share: Share2,
  signOut: LogOut,
  shop: Package,
  success: ShieldCheck,
  transportation: Truck,
  upload: Upload,
  warning: AlertTriangle,
  work: HardHat,
  workflow: Activity,
  knowledge: BookOpen,
};

export default SEMANTIC_ICON_REGISTRY;