// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: airport · 2 ES translations

export const TOPICS_AIRPORT_ES = {
  airport_movement_area_awareness: {
    title: "Áreas de Movimiento de Aeropuerto — Disciplina de Pista, Taxiway y ATC",
    incident_pattern: "Los incidentes en trabajos de aeropuerto involucran aeronaves, no solo equipo de tierra. El patrón se repite: una cuadrilla está pavimentando o reparando pavimento al borde de una pista o taxiway. El líder ha despejado la zona de trabajo con ATC. La autorización era por una hora. La cuadrilla se pasa de la autorización porque un equipo se descompuso. ATC, asumiendo que la zona está despejada en el tiempo acordado, libera la pista. Una aeronave está rodando en 90 segundos. El trabajador sacando un equipo no sabe que la autorización venció. El hallazgo más consistente en fatalidades relacionadas con aeropuerto es ruptura de comunicación — entre ATC, el líder, y los trabajadores en tierra.",
    hazards_reviewed: "Golpe de aeronave a trabajador o equipo en área de movimiento activa · Jet blast / prop wash · FOD creado por escombros del sitio · Incursión de equipo a pista activa · Ruptura de comunicación con ATC · Confusión en operaciones de baja visibilidad o noche",
    discussion_notes: "• El trabajo en área de movimiento requiere autorización de ATC y ventana CONFIRMADA. El líder tiene la radio. El líder está en ello.\n• Si la ventana de trabajo está por expirar — PARE. Saque a todos y todo. NO empuje el tiempo. ATC va a re-autorizar; las aeronaves no pueden aterrizar dos veces.\n• Los trabajadores todos cargan radios en la frecuencia de operaciones que la autoridad del aeropuerto asigna. Escuchen primero, hablen segundo.\n• Disciplina de FOD — cada llave, cada cono, cada escombro contado antes de despejar el área. Un perno suelto destruye un motor de jet.\n• Hi-vis a especificación de aeropuerto — no igual que hi-vis de construcción. ANSI 207 colores de Seguridad Pública donde se requiera. Lea la especificación del contrato.\n• Equipo en zona activa — escoltado, marcado, y en radio ATC. Pickups también. Nadie freelancea sobre un taxiway.\n• Zonas de jet blast / prop wash — aun aeronaves pequeñas crean viento que puede lanzar a una persona o un cono. Manténgase lejos de aeronaves en espera.\n• Operaciones de noche / baja visibilidad — coordinación extra, iluminación extra, check-ins extra. No empuje a través de mala visibilidad sin alineación con autoridad.",
    references_cited: "FAA AC 150/5210-5 · FAA AC 150/5370-2 · Procedimientos TSA / específicos del aeropuerto · SOP de Operaciones de Aeropuerto MASCI",
    action_items: "Protocolo de autorización ATC reforzado · Responsabilidad de FOD revisada · Disciplina de radio discutida · Simulacro de retirada por expiración de ventana asignado",
  },
  airport_jet_blast_fueling: {
    title: "Jet Blast, Prop Wash y Conciencia de Recarga en Aeropuerto",
    incident_pattern: "Los trabajadores subestiman el jet blast y prop wash. Un turbohélice regional encendiendo genera 100+ mph de viento atrás. Un jet comercial en thrust de ralenti genera vientos capaces de voltear una pickup. El patrón: una cuadrilla está posicionando equipo cerca de una aeronave en espera, el piloto sube thrust para empezar a taxiar, y un trabajador, un cono, o un equipo es lanzado. Combine eso con el ambiente de recarga de aeropuerto — Jet-A está en todas partes, las fuentes de ignición deben controlarse, y una chispa estática es un fuego Clase B instantáneo. El trabajo en aeropuerto tiene sus propios riesgos que no existen en ningún otro lado.",
    hazards_reviewed: "Trabajador / equipo lanzado por jet blast · Lesión por prop wash a cuadrilla en tierra · Ignición estática de Jet-A · Ignición de nube de vapor cerca de operaciones de combustible · Daño auditivo por ruido de aeronave · FOD por escombros lanzados",
    discussion_notes: "• Manténgase lejos de aeronaves en espera. Una distancia de 100 pies es un punto de partida, no un máximo. Si puede ver el motor, el motor lo puede golpear con blast.\n• Protección auditiva en cualquier área de movimiento activa. El ruido de aeronaves daña la audición en minutos de exposición.\n• Áreas de recarga Jet-A — sin fuentes de chispa dentro de 50 pies. Sin celulares, sin linternas sin clasificación intrínseca, sin metal-contra-metal.\n• Amarre o ponga peso a TODO cerca de un taxiway. Conos, caballetes, equipo. Lo que se queda en viento normal se vuela en prop wash.\n• Las operaciones de recarga tienen su propia cuadrilla. Las cuadrillas de construcción no intersectan con ops de recarga. Manténgase lejos de camiones de combustible y aeronaves recargando.\n• Conexión a tierra estática para cualquier trabajo adyacente a recarga. Cables de bonding, varillas de tierra. La estática es la fuente de ignición silenciosa.\n• Si siente viento de repente — mire alrededor. Una aeronave se está moviendo en un lugar que no esperaba. Verifique posición antes de continuar.\n• Protección ocular — escombros en trabajo de aeropuerto están en todas partes. Caretas abiertas no son suficiente en aeropuertos ocupados.",
    references_cited: "FAA AC 150/5230-4 · NFPA 407 (servicio de combustible de aeronaves) · OSHA 1926.101 (audición) · SOP de Aeropuerto MASCI",
    action_items: "Distancia de despeje de aeronave reforzada · Protección auditiva verificada · Control de ignición adyacente a recarga discutido · Política de amarre para conos / equipo revisada",
  },
};
