// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: airport · 2 ES translations

export const TOPICS_AIRPORT_ES = {
  airport_movement_area_awareness: {
    title: "Áreas de Movimiento de Aeropuerto — Disciplina de Pista, Taxiway y ATC",
    incident_pattern: "Los incidentes en trabajos de aeropuerto involucran aeronaves, no solo equipo de tierra. El patrón se repite: una cuadrilla está pavimentando o reparando pavimento al borde de una pista o taxiway. El líder ha despejado la zona de trabajo con ATC. La autorización era por una hora. La cuadrilla se pasa de la autorización porque un equipo se descompuso. ATC, asumiendo que la zona está despejada en el tiempo acordado, libera la pista. Una aeronave está rodando en 90 segundos. El trabajador sacando un equipo no sabe que la autorización venció. El hallazgo más consistente en fatalidades relacionadas con aeropuerto es ruptura de comunicación — entre ATC, el líder, y los trabajadores en tierra.",
    hazards_reviewed: "Golpe de aeronave a trabajador o equipo en área de movimiento activa · Jet blast / prop wash · FOD creado por escombros del sitio · Incursión de equipo a pista activa · Ruptura de comunicación con ATC · Confusión en operaciones de baja visibilidad o noche",
    discussion_notes: "• El trabajo en área de movimiento requiere autorización de ATC y ventana CONFIRMADA. El líder tiene la radio. El líder está en ello.\n• Si la ventana de trabajo está por expirar — PARE. Saque a todos y todo. NO empuje el tiempo. ATC va a re-autorizar; las aeronaves no pueden aterrizar dos veces.\n• Los trabajadores todos cargan radios en la frecuencia de operaciones que la autoridad del aeropuerto asigna. Escuchen primero, hablen segundo.\n• Disciplina de FOD — cada llave, cada cono, cada escombro contado antes de despejar el área. Un perno suelto destruye un motor de jet.\n• Hi-vis a especificación de aeropuerto — no igual que hi-vis de construcción. ANSI 207 colores de Seguridad Pública donde se requiera. Lea la especificación del contrato.\n• Equipo en zona activa — escoltado, marcado, y en radio ATC. Pickups también. Nadie freelancea sobre un taxiway.\n• Zonas de jet blast / prop wash — aun aeronaves pequeñas crean viento que puede lanzar a una persona o un cono. Manténgase lejos de aeronaves en espera.\n• Operaciones de noche / baja visibilidad — coordinación extra, iluminación extra, check-ins extra. No empuje a través de mala visibilidad sin alineación con autoridad.",
    references_cited: "FAA AC 150/5210-5 · FAA AC 150/5370-2 · Procedimientos TSA / específicos del aeropuerto · SOP de Operaciones de Aeropuerto MASCI",
    action_items: "Protocolo de autorización ATC reforzado · Responsabilidad de FOD revisada · Disciplina de radio discutida · Simulacro de retirada por expiración de ventana asignado",
  },
  airport_jet_blast_fueling: {
    title: "Jet Blast, Prop Wash y Conciencia de Recarga en Aeropuerto",
    incident_pattern: "Los trabajadores subestiman el jet blast y prop wash. Un turbohélice regional encendiendo genera 100+ mph de viento atrás. Un jet comercial en thrust de ralenti genera vientos capaces de voltear una pickup. El patrón: una cuadrilla está posicionando equipo cerca de una aeronave en espera, el piloto sube thrust para empezar a taxiar, y un trabajador, un cono, o un equipo es lanzado. Combine eso con el ambiente de recarga de aeropuerto — Jet-A está en todas partes, las fuentes de ignición deben controlarse, y una chispa estática es un fuego Clase B instantáneo. El trabajo en aeropuerto tiene sus propios riesgos que no existen en ningún otro lado.",
    hazards_reviewed: "Trabajador / equipo lanzado por jet blast · Lesión por prop wash a cuadrilla en tierra · Ignición estática de Jet-A · Ignición de nube de vapor cerca de operaciones de combustible · Daño auditivo por ruido de aeronave · FOD por escombros lanzados",
    discussion_notes: "• Manténgase lejos de aeronaves en espera. Una distancia de 100 pies es un punto de partida, no un máximo. Si puede ver el motor, el motor lo puede golpear con blast.\n• Protección auditiva en cualquier área de movimiento activa. El ruido de aeronaves daña la audición en minutos de exposición.\n• Áreas de recarga Jet-A — sin fuentes de chispa dentro de 50 pies. Sin celulares, sin linternas sin clasificación intrínseca, sin metal-contra-metal.\n• Amarre o ponga peso a TODO cerca de un taxiway. Conos, caballetes, equipo. Lo que se queda en viento normal se vuela en prop wash.\n• Las operaciones de recarga tienen su propia cuadrilla. Las cuadrillas de construcción no intersectan con ops de recarga. Manténgase lejos de camiones de combustible y aeronaves recargando.\n• Conexión a tierra estática para cualquier trabajo adyacente a recarga. Cables de bonding, varillas de tierra. La estática es la fuente de ignición silenciosa.\n• Si siente viento de repente — mire alrededor. Una aeronave se está moviendo en un lugar que no esperaba. Verifique posición antes de continuar.\n• Protección ocular — escombros en trabajo de aeropuerto están en todas partes. Caretas abiertas no son suficiente en aeropuertos ocupados.",
    references_cited: "FAA AC 150/5230-4 · NFPA 407 (servicio de combustible de aeronaves) · OSHA 1926.101 (audición) · SOP de Aeropuerto MASCI",
    action_items: "Distancia de despeje de aeronave reforzada · Protección auditiva verificada · Control de ignición adyacente a recarga discutido · Política de amarre para conos / equipo revisada",
  },
  // iter303 · airport-domain tone benchmark ES (operator-approved v2)
  // Mental-model-first framing · field-Spanish discipline: trocas · wash de la
  // hélice · golpe de llanta · tarp untranslated · 'nomás' removed for
  // universality. Rhetorical anchor preserved: "El perno no cambió. El pavimento
  // donde quedó cambió todo el significado del perno."
  airport_fod_control: {
    title: "Control de FOD (Escombros Sueltos) en Plataforma — La Disciplina Que Cierra la Brecha Mental",
    incident_pattern:
      "El FOD no se siente como un riesgo fatal cuando uno lo tiene en la mano. Un perno. Una tuerca. Un pedazo de dos pulgadas de molienda de asfalto. El modelo mental del contratista es 'basura para barrer antes de irse.' El modelo mental del aeródromo es completamente diferente: ese mismo perno, en la línea central, al arranque del motor, se mete a 8,000 RPM. El vuelo Air France 4590 fue destruido por escombros dejados en una pista por un avión anterior. La consecuencia fue total. Más cerca de casa: un perno de carruaje de 4 pulgadas cerca de la línea central de un taxiway al final del turno se convierte en un desmontaje de motor de varios millones de dólares, un cierre de pista, y el fin del trabajo del contratista en el aeropuerto. El perno no cambió. El pavimento donde quedó cambió todo el significado del perno. Las cuadrillas que han trabajado lado-aire conocen esto en los huesos. Las cuadrillas que vienen de carretera, servicios, o concreto usualmente no — tratan el aeródromo como otra obra de pavimento hasta que algo sale mal. La disciplina de FOD es el puente entre esos dos entendimientos, y ese puente se construye un turno a la vez.",
    hazards_reviewed:
      "Ingestión por motor en arranque o despegue · Daño o reventón de llanta en carrera de despegue · Violación de FAA Part 139 y escalación del contrato · Cierre de pista o taxiway durante respuesta de barrido · EPP perdido por chorro de jet convirtiéndose en FOD · Material rastreado del área de trabajo a áreas activas de movimiento · Compresión por tiempo en limpieza de fin de turno · Personal golpeado por FOD propulsado por chorro de jet",
    discussion_notes:
      "• El FOD no es basura. Cada objeto en pavimento del lado-aire es un incidente de aeronave potencial. El cambio de 'limpieza' a 'peligro vivo' es la disciplina.\n• Revise bolsas antes de cruzar a un área de movimiento. Tornillos sueltos, plumas, tapones de oído, lentes — cualquier cosa que el chorro de jet pueda levantar es FOD.\n• Golpe de llanta en el perímetro cada vuelta. No solamente al final del turno. Cada vuelta, del área de trabajo al laydown.\n• Cajas abiertas con tarp antes de cruzar el perímetro. Molienda, grava, pedazos de banda — si puede salir volando, es FOD al aterrizar.\n• Herramientas por cuenta, firmadas a la entrada y a la salida. Doce entran, doce salen. 'Creo que las tenía todas' es como una llave se convierte en reporte FAA.\n• Cinchos, clips de banda, papel de cinta, envolturas de EPP — a la bolsa de basura a sus pies. Nunca al pavimento. Nunca 'lo agarro al regreso.'\n• EPP perdido es FOD. Un guante volado por el wash de la hélice es el mismo problema que un perno tirado. Reporte, recupere, reemplace.\n• Caminata de FOD al final del turno: hombro a hombro, ojos abajo, antes de la entrega a Operaciones del Aeródromo. Camínelo. No lo maneje.\n• Encuentra FOD: levántelo. No 'que lo agarre la siguiente cuadrilla.' No 'lo reporto y espero.' El FOD está vivo hasta que esté en la mano de alguien.\n• Si su zona es la fuente de una alerta de FOD de Operaciones del Aeródromo, su contrato está en juego. Tómelo en serio la primera vez.",
    references_cited:
      "FAA Part 139 (Certificación de Operación de Aeropuerto) · FAA AC 150/5210-24 (Manejo de FOD en Aeropuertos) · ICAO Anexo 14 · Reporte Final NTSB Air France 4590 · SOP de Operaciones del Aeródromo · Condiciones Especiales del Contrato",
    action_items:
      "Protocolo de revisión de bolsas revisado · Disciplina de cuenta de herramientas confirmada (cuenta de entrada / cuenta de salida) · Procedimiento de golpe de llanta y tarp verificado · Responsable de caminata de FOD asignado por nombre · Bolsa de basura en cada posición de trabajo · Vía de comunicación con Operaciones del Aeródromo confirmada",
  },
};
