// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: concrete · 12 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_CONCRETE = [
  {
    key: "drilled_shaft",
    domain: "concrete",
    title: "Drilled Shaft / Caisson Operations",
    category: "Hazard-Specific",
    hazards_reviewed: "Falls into open shaft · Cave-in of shaft sidewall · Struck-by drill stem / Kelly bar · Engulfment from collapsing slurry/casing · Crane / rig tipping · Suspended load swing",
    discussion_notes: "• Open shafts ALWAYS covered or barricaded; never leave open and unattended.\n• Set ground crew clear of swing radius of drill rig.\n• Workers stay outside reach of suspended drill stem and casing.\n• Slurry handling — chemical PPE, splash protection, eyewash within 25 ft.\n• Trained signal person for crane support; certified rigger for rebar cages and casings.\n• Trip hazards from rebar, hoses, slurry lines kept controlled.",
    references_cited: "OSHA 1926 Subpart P (excavation) · OSHA 1926 Subpart CC (cranes) · DFI Drilled Shaft Safety",
    action_items: "Open shafts covered/barricaded · Swing radius marked · Signal person designated · Slurry PPE staged",
  },
  {
    key: "saw_cutting",
    domain: "concrete",
    title: "Pavement Saw Cutting",
    category: "Tool / Equipment Specific",
    hazards_reviewed: "Respirable silica · Cuts / amputations from blade · Kickback · Noise · Heat / hot blade · Struck-by passing traffic · Slurry contamination",
    discussion_notes: "• Wet cut whenever possible — water suppression is OSHA Table 1 control for silica.\n• When dry cut required: HEPA vacuum AND respiratory protection.\n• Inspect blade before each use; dispose of cracked or chipped blades.\n• Two-handed grip; no overreach; firm footing.\n• Hearing protection — pavement saws routinely exceed 100 dBA.\n• Slurry: contain it; don't let it run into storm drain (NPDES violation).\n• Eye + face protection from flying chips.",
    references_cited: "OSHA 1926.1153 (Silica Table 1) · OSHA 1926.300 · OSHA 1926.95",
    action_items: "Wet-cut equipment ready · Respirator if dry · Slurry containment · Hearing & face PPE · Blade inspected",
  },
  {
    key: "curb_gutter",
    domain: "concrete",
    title: "Curb & Gutter Operations",
    category: "Hazard-Specific",
    hazards_reviewed: "Slip-form machine pinch points · Hot/wet concrete contact · Repetitive bending and lifting · Struck-by passing traffic · Silica from sawing finished concrete · Skin chemical burns",
    discussion_notes: "• Workers stay outside slip-form machine no-go zone — typical 6 ft buffer.\n• Hand-finishing crews wear waterproof gloves and boots; rinse skin contact immediately.\n• Lift / move forms with proper body mechanics — keep load close, knees bent.\n• Edge work near live traffic = positive protection (drum line minimum, barrier preferred).\n• Joint sawing follows silica controls (Table 1).\n• Dispose of waste concrete properly; no dumping into storm drains.",
    references_cited: "OSHA 1926 Subpart Q · OSHA 1926.1153 · NIOSH Concrete Worker Bulletin",
    action_items: "Waterproof PPE issued · No-go zone marked · Lifting plan briefed · Silica Table 1 controls in place",
  },
  {
    key: "mse_wall",
    domain: "concrete",
    title: "MSE Wall / Retaining Wall Construction",
    category: "Hazard-Specific",
    hazards_reviewed: "Falls from elevated panels · Struck-by panel during placement · Pinch / crush during reinforcement strap install · Backfill compaction edge instability · Material handling strains",
    discussion_notes: "• Tag lines control panel rotation during placement.\n• Workers behind panels protected from struck-by during set; outside swing radius.\n• Tie-off required when working at edges 6 ft+; guardrails installed as wall height grows.\n• Compaction equipment kept set distance from wall face per design.\n• Reinforcement straps unrolled with tools, not bare hands.\n• Wall toe stable before next lift placed.",
    references_cited: "OSHA 1926 Subpart M · AASHTO LRFD Bridge Design · NCMA Design Manual",
    action_items: "Tag lines staged · Fall protection above 6 ft · Compaction setbacks marked · Lifting plan briefed",
  },
  {
    key: "concrete_silica",
    domain: "concrete",
    title: "Concrete Operations & Respirable Silica",
    category: "Hazard-Specific",
    hazards_reviewed: "Respirable crystalline silica (silicosis, lung cancer) · Caustic burns from wet concrete · Skin / eye irritation · Rebar impalement · Forms collapse · Lifting injuries",
    discussion_notes: "• OSHA Table 1 — match every dust-generating task to its specified engineered control (water OR vacuum).\n• Respiratory protection (P100 or supplied air) when controls insufficient or task isn't on Table 1.\n• Waterproof gloves, boots, sleeves with wet concrete; rinse skin contact immediately.\n• Rebar caps on every exposed end at trip height or below.\n• Forms inspected and braced before pour; competent person for forming.\n• Eye protection mandatory during cutting, grinding, sawing, chipping.",
    references_cited: "OSHA 1926.1153 · OSHA 1926 Subpart Q · NIOSH Silica Bulletin",
    action_items: "Table 1 controls in place · Water/vacuum systems checked · Respirators fit-tested · Rebar caps installed",
  },
  {
    key: "concrete_pumping",
    domain: "concrete",
    title: "Concrete Pumping",
    category: "Tool / Equipment Specific",
    hazards_reviewed: "Pump line whip / failure · Struck-by hose · Caustic spray injuries to eyes/skin · Tipping pump truck on inadequate outriggers · Overhead power line contact · Plug/blockage causing line failure",
    discussion_notes: "• Outriggers fully extended on cribbing; ground bearing capacity confirmed.\n• Stay clear of overhead lines — minimum 10 ft (more for higher voltage).\n• Hose handler stays outside potential whip zone; positive comms with operator.\n• Eye/face protection mandatory — burst fittings spray cement under pressure.\n• Clear blockages by reverse, never by disconnecting under pressure.\n• Safety chains on all clamp connections.",
    references_cited: "ACPA Concrete Pump Safety · OSHA 1926.701 · OSHA 1926.405",
    action_items: "Outriggers cribbed · Overhead clearance verified · Eye/face PPE · Comms tested · Safety chains in place",
  },
  {
    key: "formwork",
    domain: "concrete",
    title: "Formwork Safety",
    category: "Procedure / SOP",
    hazards_reviewed: "Form collapse · Falls from formwork · Struck-by falling forms · Pinch / crush during stripping · Rebar impalement · Hardware failure under load",
    discussion_notes: "• Formwork designed by qualified person for the load (concrete + workers + equipment).\n• No deviation from drawings without engineer approval.\n• Inspect formwork before pour — every brace, every tie, every shore.\n• Workers tie off when working at form height 6 ft+.\n• Stripping: only after concrete reaches required strength; controlled drop zones.\n• Rebar caps on all exposed ends; no walking on top mat without planking.",
    references_cited: "OSHA 1926.703 · ACI 347 Formwork · OSHA 1926.703(b)",
    action_items: "Form drawings on site · Pre-pour inspection logged · Strip strength verified · Rebar caps in place",
  },
  {
    key: "bridge_deck_pour",
    domain: "concrete",
    title: "Bridge Deck Pours",
    category: "Hazard-Specific",
    hazards_reviewed: "Falls over edge · Falls through deck openings · Struck-by finishing machine · Concrete spray from pump · Rebar trip / impalement · Heat stress on long pours",
    discussion_notes: "• Perimeter guardrail or full PFAS before any deck work begins.\n• Cover or barricade every opening.\n• Finishing machine no-go zones marked; operator and crew comms verified.\n• Heat stress plan in effect — water, ice, shade, rotation.\n• Crew briefing: pour sequence, dump location, comms with mixer drivers.\n• Edge protection at fascia stays in place until parapet poured.",
    references_cited: "OSHA 1926 Subpart M · OSHA 1926.502 · AASHTO Bridge Construction",
    action_items: "Edge protection in place · Openings covered · Heat plan active · Pour sequence briefed",
  },
  {
    key: "curing_sealing",
    domain: "concrete",
    title: "Curing & Sealing Operations",
    category: "Hazard-Specific",
    hazards_reviewed: "Solvent vapor inhalation · Skin/eye irritation · Fire / explosion from flammable cures · Slip on wet cure · Spray-back to face during application",
    discussion_notes: "• Read SDS before any cure / sealer use; verify required PPE.\n• Solvent-based products: respiratory protection, no smoking, no ignition sources, ground sprayers.\n• Spray downwind; shut off if wind shifts.\n• Eye / face protection mandatory.\n• Slip hazard — flag wet areas, no walking on freshly cured surfaces.\n• Spill kits onsite; environmental compliance for any spill.",
    references_cited: "OSHA 1926.59 (HazCom) · Material SDS · NFPA 30 (Flammables)",
    action_items: "SDS reviewed · Respirators ready · Wet zones flagged · Spill kits onsite",
  },
  {
    key: "cold_weather_concrete",
    domain: "concrete",
    title: "Cold Weather Concrete Operations",
    category: "Hazard-Specific",
    hazards_reviewed: "Cold stress / hypothermia · Burns from heated water / steam · CO from heaters in enclosures · Slips on icy surfaces · Frozen-aggregate kickbacks from chute",
    discussion_notes: "• Layered clothing, insulated waterproof gloves and boots; cover head and neck.\n• Heated enclosures: ONLY direct-fired heaters with continuous CO monitoring; OR indirect-fired heaters venting outside.\n• Warming areas (heated trailer / shed) within 100 ft of crew.\n• Salt / sand walking surfaces; flag icy areas.\n• Hot water for mix: 140°F max at point of use; gloves required.\n• Buddy system — frostbite first signs are subtle.",
    references_cited: "OSHA Cold Stress Bulletin · ACI 306 Cold-Weather Concreting",
    action_items: "Cold-weather PPE issued · CO monitoring set · Walking surfaces de-iced · Warming area available",
  },
  {
    key: "diamond_grinding",
    domain: "concrete",
    title: "Diamond Grinding & Grooving",
    category: "Tool / Equipment Specific",
    hazards_reviewed: "Respirable silica · Slurry slips · Hot blade contact · Noise · Struck-by passing traffic · Eye injury from chip / spray",
    discussion_notes: "• Wet grind for silica control (Table 1) — blade water on continuously.\n• Vacuum slurry to prevent storm drain contamination.\n• Hearing protection — process exceeds 95 dBA.\n• Eye / face protection from chips and spray.\n• Operator stays clear of blade; cool blade before any maintenance.\n• Slurry disposed at approved location.",
    references_cited: "OSHA 1926.1153 (Silica Table 1) · ACPA Grinding Best Practices",
    action_items: "Water spray verified · Slurry containment · Hearing & eye PPE · Disposal location approved",
  },
  {
    key: "sound_wall",
    domain: "concrete",
    title: "Sound Wall / Noise Wall Construction",
    category: "Hazard-Specific",
    hazards_reviewed: "Falls from height · Struck-by panel during placement · Crush during column erection · Wind catching panels · Crane tipping · Live traffic adjacent",
    discussion_notes: "• Tag lines control panel rotation; workers outside swing radius.\n• Wind speed monitoring — stop placement at mfr / engineer-specified threshold.\n• Tie-off above 6 ft; perimeter guardrail / catch system as wall grows.\n• Crane signal person designated and certified.\n• Live traffic side: positive protection (barrier) between work and travel lane.\n• Foundations cured to design strength before column / panel placement.",
    references_cited: "OSHA 1926 Subpart M · OSHA 1926 Subpart CC · AASHTO LRFD",
    action_items: "Tag lines staged · Wind monitor on site · Fall protection 6 ft+ · Signal person designated",
  },
];
