// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: dewatering · 8 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_DEWATERING = [
  {
    key: "dewatering_jetting_rig_overhead_strike",
    domain: "dewatering",
    title: "Jetting Rig Overhead Powerline Strikes",
    category: "Hazard-Specific",
    role_context: ["operator","lead","spotter"],
    incident_pattern: "Jetting-rig powerline contacts almost never happen during steady jetting — they happen during repositioning. The rig is set, the operator finishes a header, and now needs to move to the next stab. They retract a little, swing the boom, and the boom mast — usually fully extended from the last header — sweeps into the overhead line. The driver is focused on the ground crew and the next stab, not on what's 30 feet above. Around utility yards, behind grocery stores, on the back side of pump stations — overhead lines are everywhere and the masts on jet rigs are tall enough to find them.",
    hazards_reviewed: "Electrocution of operator or ground crew · Mast contact with energized line during reposition · Step potential around energized rig · Outage / fire from utility damage · Burns from arc flash",
    discussion_notes: "• Before the rig comes off the trailer — walk the site. Look up. Identify EVERY overhead line within 50 feet of any place the mast will travel.\n• 20-foot minimum clearance from energized lines under OSHA 1926.1408. If the line is below 50 kV. Bigger voltage = bigger clearance.\n• Lower the mast BEFORE you reposition. Every time. The 30 seconds it costs you is the cheapest insurance you'll buy.\n• Designate a spotter whose ONLY job is watching the mast and the lines during any reposition. Not multitasking. Not also signaling ground crew. Just the mast and the lines.\n• If you don't know whether a line is energized, treat it as live. Call the utility. Get a confirmed de-energize and ground BEFORE you work close to it.\n• Contact happens: STAY ON THE RIG. Keep ground crew back at least one rig-length plus the line. Call 911 and the utility. Step-potential has killed more people than the initial contact.\n• If you HAVE to exit: bunny-hop with feet together. Never have two body parts on the ground at the same time until 30 feet clear.",
    references_cited: "OSHA 29 CFR 1926.1408 · OSHA 1926.416 · NESC clearances · MASCI Jet Rig Setup SOP",
    action_items: "Overhead walk-around done · Mast-down-before-reposition habit reinforced · Designated mast-spotter assigned · Contact-response procedure reviewed",
  },
  {
    key: "dewatering_suction_line_entrapment",
    domain: "dewatering",
    title: "Suction-Line Entrapment and Engulfment",
    category: "Hazard-Specific",
    role_context: ["operator","lead"],
    incident_pattern: "Suction-line engulfment is one of the least talked-about fatalities in dewatering, and one of the most preventable. A wellpoint header gets clogged, the operator pulls a stinger to check the screen, and water rushes through the open line. Anyone within a few feet — boots in the trench bottom, hand reaching for the screen, kneeling beside the line — can be pulled into the suction by hydraulic action. Even a 6-inch suction at full vacuum will hold a hand or a boot to the inlet hard enough that the worker cannot self-release. Several documented fatalities in our region trace back to a single 'just gonna check the screen' action.",
    hazards_reviewed: "Hand or limb pulled into suction inlet · Engulfment in collapsing wellpoint trench · Drowning in unscreened sump · Hose-whip injury · Pinch / amputation at strainer",
    discussion_notes: "• Vacuum off BEFORE anyone touches a suction line, header, stinger, screen, or strainer. Period. No exceptions. No 'I'll be quick about it.'\n• Lockout the pump at the controls AND verify zero pressure at the gauge before anyone gets near the inlet.\n• If you must work near a flowing line, use a long-handled tool. Never put a hand or arm in the suction zone.\n• Strainer screens prevent entrapment AND prevent screen failures — inspect them daily, replace any cracked or worn one.\n• Wellpoint trenches should be properly shored or sloped. Engulfment risk is real if the trench wall fails while someone is at the bottom servicing a header.\n• Sump pits with open suction inlets need barriers or grates. A kid, a worker, a dog — anything that falls in is in trouble immediately.\n• Train new crew on suction physics — explain why a 6-inch hose at 25 inches Hg will not let go of a hand. Make it real, not theoretical.",
    references_cited: "OSHA 29 CFR 1926 Subpart P · OSHA 1910.147 (LOTO) · Manufacturer pump operation manual · MASCI Dewatering SOP",
    action_items: "Vacuum-off-before-touch rule reinforced · Lockout at pump controls verified · Strainer inspection assigned · New-crew suction physics briefing scheduled",
  },
  {
    key: "dewatering_diesel_pump_fueling_fires",
    domain: "dewatering",
    title: "Diesel Pump Fueling Fires",
    category: "Hazard-Specific",
    role_context: ["operator","lead","driver"],
    incident_pattern: "Diesel pump fires almost never happen at the fuel station — they happen on-site during refueling of running or recently-shut-down equipment. The pump has been running 12 hours, the muffler and turbo are at 800–1000°F, the operator is rushing to fuel up before the next storm, and a fuel splash hits hot metal. The fire is instant and immediately threatens the operator standing 18 inches from the fill spout. Most of these fires turn into burn injuries, not fatalities — but they ruin a worker's life and shut a job down. The pattern is preventable with one simple discipline: cool-down time and clean fueling.",
    hazards_reviewed: "Fuel splash onto hot exhaust / turbo · Static discharge ignition during transfer · Spill creating slip + fire hazard · Burn injury to fueler · Equipment loss · Environmental release",
    discussion_notes: "• Shut the pump OFF before fueling. Allow 5–10 minutes of cooldown if the engine has been running hard. The exhaust manifold and turbo stay hot long after shutdown.\n• No smoking · no cell-phone calls · no open flames within 25 feet of fueling. This is not optional.\n• Maintain bond between the fuel container or hose and the pump frame during transfer. Static is a real ignition source.\n• Don't top off. The expansion when fuel warms can push fuel out the vent and onto the engine.\n• Fuel transfer at night with a flashlight — not with a hot work-light propped on the pump. Lights run hot.\n• Spill kit on every dewatering site. Absorbent pads, sock, drain mat. Drain mat goes UNDER the fill point every time.\n• If a fire starts: ABC extinguisher within reach (within 10 ft of fueling point). Pull the operator clear FIRST. Then fight the fire. Never fight a fire alone.\n• Electric submersibles: GFCI on every electrical pump, cords inspected daily for damage, bonding + grounding verified at the pump frame. A failing seal turns the whole trench into a shock hazard for anyone working in the water.",
    references_cited: "NFPA 30 · OSHA 1926.152 · EPA SPCC · DOT 49 CFR 173 · MASCI Fueling SOP",
    action_items: "Cooldown-before-fueling habit discussed · Extinguisher within 10 ft verified · Spill kit + drain mat at every pump · Bonding-during-transfer reviewed",
  },
  {
    key: "dewatering_wellpoint_trench_collapse",
    domain: "dewatering",
    title: "Wellpoint Trench Collapse Around Headers",
    category: "Hazard-Specific",
    role_context: ["operator","lead","ground_crew"],
    incident_pattern: "Wellpoint trench collapses follow a tight pattern: the trench is dug to a moderate depth (4–8 ft), the header laid, the wellpoints jetted. Three days into pumping, the soil between points has been pulled tighter and the trench walls look stable. A worker steps down into the trench to service a clogged point or repair a leak. The dewatering has actually changed the soil structure — saturated material above an now-dry section creates a sliding plane. The wall fails inward with no warning. The worker, even if they live, is buried to the chest in seconds. Once-stable trenches are not stable forever when water content changes.",
    hazards_reviewed: "Burial / suffocation from collapsed trench wall · Crush injury from wall failure · Drowning in trench bottom from sudden inrush · Struck-by from falling header / equipment · Hypothermia in long-duration burial",
    discussion_notes: "• Trench protection at 5 ft+ is not optional — slope, bench, shore, or trench box. Dewatering does NOT replace shoring.\n• Trenches over 4 ft need a ladder or ramp within 25 ft of any worker.\n• Reclassify the soil after dewatering has been running. Saturated-to-dry transitions create unstable layers. Talk to your competent person.\n• Spoil pile at least 2 ft from the edge. Equipment paths at least one trench-depth back. Vibration from running pumps loosens edge material over hours.\n• Service a wellpoint from ABOVE the trench whenever possible. The risk of being in the trench to fix a point is not worth the time saved.\n• Never work alone in a wellpoint trench. The first 60 seconds after a collapse is when survival happens — only if someone topside sees it.\n• Daily inspection by a competent person — and after any rain, freeze-thaw, or vibration event.",
    references_cited: "OSHA 29 CFR 1926 Subpart P · OSHA 1926.651 · OSHA 1926.652 · MASCI Dewatering Trench SOP",
    action_items: "Trench protection reviewed for current depth · Soil reclassification done after pumping start · Above-trench service habit reinforced · Daily competent-person inspection assigned",
  },
  {
    key: "dewatering_rotating_shaft_belt",
    domain: "dewatering",
    title: "Rotating Shaft and Belt Entanglement",
    category: "Hazard-Specific",
    role_context: ["operator","lead","mechanic"],
    incident_pattern: "Belt and shaft entanglement injuries on dewatering pumps usually happen when a guard is off for a service task and the engine gets bumped or restarted by someone who didn't know a crew member was working on it. A glove, a sleeve, a shirt tail, a hood drawstring catches a v-belt or a coupling. The pump engine is making 1800 RPM at the coupling — the entire arm is in before the worker can react. Hoodies, loose sleeves, and unbuttoned cuffs are the leading factor in nearly every documented incident. The second factor is missing LOTO when a guard is off.",
    hazards_reviewed: "Arm / hand pulled into v-belt or coupling · Crush / amputation from rotating shaft · Death from clothing caught in PTO · Burn from belt friction · Eye injury from belt failure",
    discussion_notes: "• Guards in place ANY time the engine is running. No exceptions. If the guard is broken, the pump doesn't run until it's fixed.\n• Lockout the engine at the kill switch AND remove the key before any guard comes off. Verify with a start-attempt before reaching in.\n• Sleeves buttoned · shirts tucked · NO hoodie drawstrings · NO loose jewelry near rotating equipment.\n• Snug gloves only — and consider gloves OFF when working close to rotating shafts. Loose glove fingers grab v-belts.\n• Train new operators to identify EVERY pinch point on the pump before they ever touch it running. Walk it down. Point at each one.\n• Belt service is engine-OFF service. Tensioning, alignment, replacement — all engine-off, with the key in your pocket.\n• If a guard is off for inspection — assign one person as the lock holder. Their key stays in their pocket. No one else can start.",
    references_cited: "OSHA 29 CFR 1910.147 (LOTO) · OSHA 1910.219 · ANSI B11 · Manufacturer pump operation manual",
    action_items: "Guards-in-place rule reinforced · LOTO before guard removal verified · Clothing standards (no drawstrings) discussed · New-operator pinch-point walk-down assigned",
  },
  {
    key: "dewatering_discharge_hose_whip",
    domain: "dewatering",
    title: "Discharge Hose Whip and Pressure Release",
    category: "Hazard-Specific",
    role_context: ["operator","lead","ground_crew"],
    incident_pattern: "Discharge-hose whip incidents happen because a hose connection fails or a section breaks free under pressure. A 6 or 8-inch discharge hose at 60–80 psi carries enormous stored energy. When a coupling lets go, the hose end becomes a whip — moving fast enough to break bones, throw workers, or knock someone off a trench bank. The pattern is usually a worn cam-lock or quick-connect coupling, a missing safety pin or clip, or a hose that wasn't restrained where it should have been. The whip travels along the path of least resistance — usually toward whoever is nearest.",
    hazards_reviewed: "Hose-whip strike to head / chest · Pressure release knocking worker into trench · Slip injury from sudden water release · Coupling failure projectile · Burns from heated discharge (hot oil pumps)",
    discussion_notes: "• Inspect every cam-lock and coupling on every shift. Look for worn cams, missing safety clips, deformed gaskets. Replace anything questionable.\n• Safety pins / clips on every coupling. They are not optional. They are what keeps the hose connected when a cam fatigues.\n• Restrain discharge hoses where they change direction, where they cross a path, where they go over a bank. Use rope ties, sandbags, or proper restraints — not stacked rocks.\n• When pressurizing a line, no one stands in line with the hose. Everyone steps off-axis BEFORE the pump starts.\n• If a hose lets go: KILL THE PUMP from the control side first. Don't try to grab the hose. Hose ends weigh enough to break a hand at 60 psi.\n• Whip-checks (woven safety cables) on every coupling on long discharge runs. Standard equipment, not optional.\n• Daily walk of the entire discharge run — look for stress points, kinks, abrasion, exposed restraint, leaks. Catch the failure BEFORE the whip.",
    references_cited: "OSHA 29 CFR 1926.302 · ASME B31.3 · Manufacturer hose / coupling ratings · MASCI Discharge SOP",
    action_items: "Coupling inspection assigned to each shift · Safety pins verified on all couplings · Whip-checks deployed on long runs · Pump-off-before-touch reinforced",
  },
  {
    key: "dewatering_spoil_edge_instability",
    domain: "dewatering",
    title: "Spoil Placement Around Wellpoint Trench Edges",
    category: "Hazard-Specific",
    role_context: ["operator","lead","equipment_operator"],
    incident_pattern: "Most wellpoint trench-edge failures don't start with the trench wall — they start with the spoil pile. Spoil placed too close to the edge adds surcharge load. Equipment running parallel to the trench transmits vibration through the spoil into the wall. Three days of pumping plus the static load of a 4-foot spoil pile plus the dynamic load of a passing excavator equals a wall section that slides into the trench with no warning. The crew member servicing a header at the bottom never sees it coming. The fix is unglamorous and known: keep spoil back, keep equipment back, and inspect daily.",
    hazards_reviewed: "Trench collapse from spoil surcharge · Engulfment of worker in trench bottom · Equipment slide into trench · Struck-by from spoil avalanche · Hose / header damage from collapsed wall",
    discussion_notes: "• Spoil pile minimum 2 feet from trench edge. For deeper trenches, push it farther — 1 trench-depth back is the safer benchmark.\n• No equipment paths within one trench-depth of the edge. Excavators, loaders, dump trucks — all back from the lip.\n• Use plywood or steel road plates if you must cross or work near the edge. Distributes load and reduces local stress.\n• Equipment running parallel to a wellpoint trench transmits vibration. Vibration loosens edge soil. Move the equipment path or stop running it for the duration.\n• Compounding effect: pumping pulls water from the trench wall. Loss of pore pressure makes wet soil settle and dry soil crack. The wall you set yesterday is not the wall you have today.\n• Daily competent-person inspection of the spoil and edge, not just the trench bottom. The edge tells you the future.\n• If you see ANY tension crack, fissure, or slumping at the edge — pull workers OUT immediately. Re-inspect before letting anyone back in.",
    references_cited: "OSHA 29 CFR 1926.651(j) · OSHA 1926.652 Appendix B · MASCI Trench Edge SOP",
    action_items: "Spoil setback verified · Equipment path moved back · Daily edge inspection assigned · Tension-crack response reviewed",
  },
  {
    key: "dewatering_night_work_struck_by",
    domain: "dewatering",
    title: "Nighttime Dewatering Visibility and Struck-By",
    category: "Hazard-Specific",
    role_context: ["operator","lead","ground_crew","driver"],
    incident_pattern: "Nighttime dewatering work is more dangerous than day work for one specific reason: visibility cones. Operators see the area lit by their work-lights and assume everyone else does too. The truck driver pulling onto the site sees a halo of glare and a black field beyond. The ground worker servicing a header in the unlit zone is invisible. Most nighttime struck-by incidents on dewatering jobs happen when a delivery truck, a transfer rig, or a customer vehicle enters a lit work zone and the driver does not see a worker outside the lit cone. The pattern repeats because lighting is set up for the WORK, not for the visibility of the workers.",
    hazards_reviewed: "Struck-by from vehicle entering site at night · Worker in unlit zone invisible to driver · Trip / fall in unlit area · Equipment contact with poorly-lit obstructions · Fatigue + reduced reaction time",
    discussion_notes: "• Light the work AND the worker paths. A single tower light on the pump is not enough. Light the routes between the trailer, the pumps, and the trench.\n• Hi-vis reflective Class 3 at night — not Class 2. Sleeves, vest, pants. The reflective tape is what makes you visible in a headlight beam.\n• Every worker has a personal light — headlamp or chest light — that turns toward incoming vehicles. Driver's eye-tracking goes to motion of light. Use that.\n• Designated entry / exit lane for vehicles. Marked with cones or barricades. No driver freelances through a dewatering work area at night.\n• Driver of any incoming vehicle: stop at the site edge. Make radio or eye contact with the lead before entering. NEVER assume the area is clear.\n• Fatigue is real. Night shifts after long days produce reaction times like blood alcohol over the legal limit. Watch each other. Force breaks. Send people home.\n• Severe weather at night — call it earlier than you would in daylight. You cannot see what's coming.",
    references_cited: "OSHA 29 CFR 1926.56 · ANSI/ISEA 107 (Class 3) · MUTCD nighttime work zones · MASCI Night Work SOP",
    action_items: "Worker-path lighting reviewed · Class 3 hi-vis required for night shift · Personal lights distributed · Entry lane defined and marked · Fatigue check-in time set",
  },
];
