// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: excavation · 4 ES translations

export const TOPICS_EXCAVATION_ES = {
  trenching_shoring: {
    title: "Seguridad en Zanjas, Apuntalamiento y Excavación",
    incident_pattern: "Las fatalidades por colapso de zanja siguen el mismo patrón casi siempre: una zanja de 4 a 6 pies, un trabajador baja 'nomás un minuto' a revisar grado o jalar un tubo atorado, y la pared falla. La zanja está apenas debajo de 5 pies, la cuadrilla no jaló la caja por un tramo tan corto, y la pila de spoil queda a un pie del borde. La pared entra como una sola losa — no como un hundimiento lento. El trabajador queda enterrado hasta el pecho en 2 segundos, y una yarda cúbica de tierra pesa ~3,000 lb. Aun si la cabeza queda libre, la compresión del pecho mata en menos de 5 minutos. Hemos perdido trabajadores en este mismo patrón en nuestra región. Cinco pies no es un número mágico — profundidad, suelo, agua y tráfico todos importan.",
    hazards_reviewed: "Derrumbe / colapso · Sepultamiento · Caídas a la excavación · Golpe por material o tierra apilada · Atmósferas peligrosas · Acumulación de agua · Servicios subterráneos · Equipo cayendo a la zanja",
    discussion_notes: "• Persona competente inspecciona toda excavación diariamente, después de lluvia y tras cualquier cambio de condiciones.\n• Sistema de protección obligatorio a 5 pies+: talud, apuntalamiento, escudo o banco.\n• Tierra apilada y equipo a ≥2 pies del borde.\n• Escalera/rampa/escalones requeridos a 25 pies de cualquier trabajador en zanja de 4 pies+.\n• Prueba atmosférica donde se sospeche atmósfera peligrosa.\n• Cuadrillas fuera del radio de giro del equipo y nunca bajo cargas suspendidas.\n• Nadie entra a una zanja sin sistema de protección — punto.",
    references_cited: "OSHA 29 CFR 1926 Subparte P · OSHA 1926.651 · OSHA 1926.652 · OSHA Trenching Quick Card",
    action_items: "Confirmar persona competente · Verificar sistema según tipo de suelo · Ticket 811 vigente · Inspección diaria registrada · Plan de rescate revisado",
  },
  soil_classification: {
    title: "Clasificación de Suelos (Tipo A / B / C)",
    incident_pattern: "La mala clasificación del suelo mata más seguido que ninguna clasificación — porque la caja o el talud se eligió con confianza para el tipo EQUIVOCADO. Una zanja se clasifica como 'arcilla Tipo A' en la junta matutina, la caja coincide con eso, y la pared falla porque la lluvia de la semana pasada saturó las 18 pulgadas superiores a Tipo C efectivo. La persona competente lo caminó seco, hizo la prueba manual con material de un día, y la cuenta cambió de la noche a la mañana. El arreglo es reclasificación recurrente — después de lluvia, después de congelación-deshielo, después de vibración, después de cualquier disturbio. Cuando hay duda, clasifique HACIA ABAJO, no hacia arriba. El costo de un talud extra son unas yardas cúbicas; el costo de equivocarse es una fatalidad.",
    hazards_reviewed: "Sistema de protección equivocado · Colapso por debilidad no detectada · Suelos en capas comportándose como el más débil · Suelo saturado reclasificado tras lluvia",
    discussion_notes: "• Tipo A: más estable (arcilla, terreno duro) — talud 3/4:1.\n• Tipo B: medio (suelos limosos) — talud 1:1.\n• Tipo C: menos estable (grava, arena, sumergido) — talud 1.5:1.\n• Suelo en capas = clasificar como la capa más débil.\n• Suelo previamente alterado es automáticamente Tipo C.\n• Pruebas visuales + manuales por persona competente; reclasificar tras lluvia o congelación.\n• En caso de duda, clasificar más bajo (más conservador).",
    references_cited: "OSHA 1926 Subparte P Apéndice A · OSHA Tabla de Clasificación de Suelos",
    action_items: "Tipo de suelo registrado diariamente · Persona competente realiza prueba · Sistema ajustado tras cambio de clima",
  },
  excavation_potholing_daylight: {
    title: "Potholing y Daylight Antes de Excavación Mecánica",
    incident_pattern: "Los golpes a servicios subterráneos que el ticket 811 NO previno casi siempre se rastrean al mismo atajo: la cuadrilla obtuvo un locate, las marcas estaban imperfectas, y el operador golpeó algo con el cucharón tratando de 'encontrarlo.' Las marcas son orientativas — la zona de tolerancia alrededor de ellas es 18-24 pulgadas en la mayoría de los estados, y dentro de esa zona, la excavación mecánica debe PARAR y comienza el daylight. Una línea de fibra de 14 pulgadas, un main de gas de 6 pulgadas, un alimentador de alto voltaje — todos viven a una o dos pulgadas de donde el cucharón está excavando. El arreglo es potholing con aire o vacío antes de que el cucharón entre a la zona de tolerancia de cualquier marca. Cuesta una hora. La alternativa cuesta una vida o una cuadra entera de servicio.",
    hazards_reviewed: "Golpe a energía energizada · Ruptura de main de gas / explosión · Golpe a fibra / comm con impacto de servicio · Reventón de main de agua · Operador atrapado en flash por golpe eléctrico · Exposición de cuadrilla durante búsqueda-con-cucharón",
    discussion_notes: "• Ticket 811 válido Y vigente. Vuelva a llamar antes de que el cucharón empiece si el ticket pasó la ventana de expiración estatal.\n• Camine las marcas ANTES de que el operador se suba. Coteje marcas con el ticket. Cualquier cosa faltante o contradictoria — pare, vuelva a llamar.\n• Zona de tolerancia es típicamente 18-24 pulgadas a cada lado de la marca. Dentro de esa zona, no excavación mecánica. Punto.\n• Daylight con air-knife, excavador de vacío, o pala hasta que el servicio esté expuesto y confirmado. Luego mecánica puede reanudar.\n• Excavador de vacío: mantenga la varilla en movimiento, vigile la fuerza de succión, protección ocular contra rebote.\n• Operador y cuadrilla acuerdan señales ANTES de excavar. Movimiento del cucharón por la zona de tolerancia necesita reconocimiento explícito de la cuadrilla.\n• Si pega algo inesperado — PARE. No trate de despejarlo. Identifique qué es desde distancia segura.\n• Golpe de gas: despeje viento arriba, sin fuentes de ignición, llame al 911 y al servicio. No trate de tapar o detener la fuga usted mismo.\n• Golpe de energía: manténgase atrás. Trate cualquier cosa metálica en la zanja como energizada. Llame al 911 y al servicio. No entre a la zanja hasta que el servicio confirme desenergización.",
    references_cited: "Mejores Prácticas CGA · OSHA 1926.651(b) · Estatutos estatales 811 / One-Call · SOP de Locate MASCI",
    action_items: "Ticket 811 verificado vigente · Zona de tolerancia explicada al operador · Herramientas de daylight en sitio · Procedimiento de respuesta a golpe revisado",
  },
  excavation_spoil_placement: {
    title: "Colocación de Pila de Spoil Alrededor de Zanjas Abiertas",
    incident_pattern: "Los colapsos de zanja relacionados con spoil son predecibles y prevenibles. La pila de spoil queda a 18 pulgadas del borde porque el espacio disponible es apretado, el excavador corre paralelo a la zanja porque el trabajo lo demanda, y el suelo ha estado en el sol perdiendo humedad toda la mañana. Para las 2 p.m. la carga de sobrepeso en el borde de la zanja más la vibración del equipo corriendo más el asentamiento natural del terreno original saturado mina la pared. La pared se desliza adentro. Un trabajador en el fondo revisando grado queda enterrado. Mismo patrón que las zanjas de wellpoint, pero en trabajo diario de tubería y servicios pasa más seguido porque las cuadrillas están menos alerta.",
    hazards_reviewed: "Colapso de zanja por sobrecarga de spoil · Vibración de equipo aflojando pared · Engullimiento de trabajador · Avalancha de material de spoil sobre cuadrilla · Tropezón con pila en el borde",
    discussion_notes: "• Spoil mínimo 2 pies del borde de la zanja. Para zanjas más profundas que 5 pies, empújela atrás a una profundidad-de-zanja o más. Si no puede, la caja se llama inmediatamente.\n• Trayectos de equipo a una profundidad-de-zanja atrás del borde. Excavadores corriendo paralelos a una zanja transmiten vibración a través del spoil hacia la pared.\n• Si el spoil TIENE que quedarse cerca, instale plywood o placas de acero en el borde para distribuir la carga.\n• Vigile la pila a través del día. Una pila firme a las 7 a.m. puede estar suelta-flujo a las 2 p.m. al secarse — o saturada y más pesada después de lluvia.\n• Grietas de tensión en el borde son su última advertencia. Si ve una, saque trabajadores AHORA y reinstale protección antes de re-entrar.\n• Caras de pila de spoil — si una pila está amontonada en el borde, el lado que ve a la zanja puede avalanzar al fondo por sí solo. Mantenga pilas extendidas, no amontonadas.\n• Trabajadores pasando el borde sobre una pila — riesgo de tropezón, torcedura de tobillo. Mantenga ruta de acceso limpia en cada escalera.\n• Hablen cada mañana. La pila cambia diariamente — el plan de ayer no es el plan de hoy.",
    references_cited: "OSHA 29 CFR 1926.651(j) · OSHA 1926.652 · NIOSH Trinchera · SOP de Zanja MASCI",
    action_items: "Setback de spoil verificado · Trayecto de equipo movido del borde · Inspección diaria de borde asignada · Respuesta a grieta de tensión revisada",
  },
};
