// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: general · 18 ES translations

export const TOPICS_GENERAL_ES = {
  demolition: {
    title: "Operaciones de Demolición",
    hazards_reviewed: "Caídas · Golpe por escombros · Colapso prematuro · Exposición a asbesto / plomo · Polvo de sílice · Incendio de corte/trabajo en caliente · Golpe a servicios remanentes",
    discussion_notes: "• Estudio de ingeniería antes de demoler — pisos, muros, materiales, servicios.\n• Estudio de materiales peligrosos — asbesto, plomo, PCBs identificados y abatidos.\n• Servicios cortados, capeados, bloqueados antes de demoler.\n• Zonas de caída barricadas; spotters en perímetro.\n• Controles de polvo — supresión con agua y EPP respiratorio.\n• Permisos de trabajo en caliente para corte/soldadura/quema.\n• Inspección diaria de estructura remanente.",
    references_cited: "OSHA 1926 Subparte T · OSHA 1926.850 · OSHA 1926.1101 (Asbesto) · OSHA 1926.62 (Plomo)",
    action_items: "Estudio ingeniería · Estudio MatPel · Servicios LOTO · Zonas de caída · Permisos de hot work",
  },
  hot_work: {
    title: "Trabajo en Caliente — Soldadura, Corte, Esmerilado",
    hazards_reviewed: "Incendio / explosión · Quemaduras · Exposición UV / IR (arco) · Inhalación de humos de soldadura · Escoria caliente igniciendo combustibles · Ruptura de cilindro de gas",
    discussion_notes: "• Permiso de Trabajo en Caliente requerido y en sitio para cualquier corte/soldadura/esmerilado fuera del taller.\n• Vigilante de fuego con extintor durante Y 30 min después.\n• Combustibles a 35 pies removidos o protegidos con mantas de soldadura.\n• Cilindros encadenados verticalmente, tapas puestas, oxígeno y combustible separados por 20 pies o barrera no combustible de 5 pies.\n• Protección ocular — sombra acorde al amperaje; protección de espectadores.\n• Ventilación o aire suministrado para galvanizado, cadmio o metal recubierto.",
    references_cited: "OSHA 1926 Subparte J · OSHA 1926.352 · NFPA 51B · ANSI Z49.1",
    action_items: "Permiso firmado · Vigilante de fuego · Combustibles despejados · Extintor listo · Cilindros asegurados",
  },
  forklift_telehandler: {
    title: "Operaciones de Montacargas / Telehandler",
    hazards_reviewed: "Volcadura · Golpe por carga · Atropello de peatones · Caídas desde horquillas (sin pasajeros) · Contacto con altura libre · Carga muy alta para ver",
    discussion_notes: "• Operador certificado (cert de 3 años + evaluación).\n• Inspección pre-turno registrada.\n• Capacidad con boom extendido es MENOR que retraído — leer la tabla.\n• Carga detrás del talón de horquillas; inclinar hacia atrás al viajar.\n• Viajar con horquillas bajas, ~6 pulgadas sobre el suelo.\n• Reversa en rampas con carga cuesta arriba; sin pasajeros nunca.\n• Outriggers requeridos para telehandler con alcance completo.",
    references_cited: "OSHA 1926.602 · OSHA 1910.178 · ANSI/ITSDF B56.6 · ANSI/ITSDF B56.1",
    action_items: "Cert vigente · Tabla de capacidad · Procedimiento de outriggers · Sin pasajeros",
  },
  ppe_general: {
    title: "EPP — Revisión Diaria de Cumplimiento",
    hazards_reviewed: "Lesión en cabeza · Lesión ocular · Pérdida auditiva · Lesión en pie · Laceración de mano · Lesión por aplastamiento · Falta de hi-vis llevando a atropello",
    discussion_notes: "• Casco — Tipo II para zonas de tráfico / impacto; reemplazar cada 5 años o tras impacto.\n• Lentes de seguridad con protectores laterales — ANSI Z87 mínimo.\n• Hi-vis Clase 2 día / Clase 3 noche para todo trabajo de carretera.\n• Botas con punta de acero o composite — sin tenis.\n• Guantes resistentes a cortes para trabajo afilado / abrasivo.\n• Protección auditiva donde el ruido > 85 dBA TWA.\n• EPP inspeccionado antes de uso; EPP dañado fuera de servicio.",
    references_cited: "OSHA 1926 Subparte E · OSHA 1926.95 · ANSI Z87 / Z89 / Z41",
    action_items: "Inventario EPP · EPP dañado reemplazado · Clase de hi-vis · Protección auditiva disponible",
  },
  stop_work: {
    title: "Autoridad para Suspender el Trabajo",
    hazards_reviewed: "Peligro inminente ignorado · Presión de producción sobre seguridad · Condición peligrosa escalando · Cuasi-accidente no reportado",
    discussion_notes: "• CADA miembro de la cuadrilla tiene la autoridad y responsabilidad de suspender el trabajo por cualquier preocupación de seguridad.\n• Nadie será represaliado, nunca, por suspender de buena fe.\n• Proceso: Parar. Notificar. Corregir. Reanudar. — los cuatro pasos.\n• Documentar el evento de Stop Work para aprender.\n• Stop Work cubre tu trabajo, tu cuadrilla, el público — cualquiera expuesto.\n• Si no estás seguro, para. Mejor perder 5 minutos que un compañero.",
    references_cited: "Cláusula General de OSHA 5(a)(1) · Política Stop Work MASCI",
    action_items: "Cartel Stop Work visible · Cuadrilla reconoce autoridad · Eventos recientes revisados",
  },
  near_miss: {
    title: "Reporte de Cuasi-Accidentes",
    hazards_reviewed: "Cuasi-accidentes recurrentes llevando a lesión real · Peligros no reportados · Datos de tendencia perdidos · Cultura de silencio",
    discussion_notes: "• Un cuasi-accidente es una lección gratis. Trátalo como una lesión que tuviste suerte de evitar.\n• Reporta cualquier acto inseguro, condición insegura o cercana — mismo turno.\n• Reporte anónimo disponible; sin represalias.\n• MASCI rastrea cuasi-accidentes para tendencias — así prevenimos el siguiente incidente.\n• No culpar al trabajador; corregir condición o proceso.\n• Ejemplos: herramienta cayó de altura, intrusión de vehículo, oscilación amplia de carga, casi tropiezo.",
    references_cited: "OSHA VPP · ANSI Z10 · Procedimiento Cuasi-Accidente MASCI",
    action_items: "Formulario disponible · Reporte revisado · Reportes recientes discutidos · Acciones correctivas rastreadas",
  },
  stretch_flex: {
    title: "Estiramiento y Calentamiento / Reunión Diaria",
    hazards_reviewed: "Esguinces y torceduras · Lesiones de tejido blando · Lesión muscular en frío · Movimiento repetitivo · Resbalones/tropiezos/caídas en la primera hora del turno",
    discussion_notes: "• Rutina de 5 minutos antes del trabajo — cuello, hombros, espalda, caderas, isquiotibiales.\n• Recorrer la lista de tareas e identificar algo nuevo o inusual.\n• Confirmar asignaciones de cuadrilla y equipo del turno.\n• Identificar preocupaciones del clima (calor, frío, rayos, viento, lluvia).\n• Confirmar todos aptos para el deber — sin discapacidad, enfermedad o fatiga.\n• Recordatorio rápido de seguridad relevante al trabajo de hoy.",
    references_cited: "MASCI Daily Huddle SOP · NIOSH Ergonomía",
    action_items: "Rutina de estiramiento completada · Tareas informadas · Revisión de clima · Aptos confirmados",
  },
  slips_trips: {
    title: "Resbalones, Tropiezos y Caídas (Mismo Nivel)",
    hazards_reviewed: "Resbalón en superficies húmedas/aceitosas/heladas · Tropiezo con mangueras, varilla, escombros · Caída en terreno desigual · Tobillo torcido por agujeros / suaves · Cargando con carga al caminar",
    discussion_notes: "• Causa #1 de lesiones en obra civil pesada — y la más prevenible.\n• Superficies despejadas de mangueras, cables, varilla — enrollar y apilar.\n• Caminos definidos y marcados a través de la obra.\n• Botas con suela agresiva; reemplazar cuando estén desgastadas.\n• No cargar cargas que bloqueen la vista de los pies.\n• Sal/arena o barrer hielo y escombros.\n• Agujeros cubiertos o barricadas — banderear terreno desigual.",
    references_cited: "OSHA 1926.25 · OSHA 1926.501 · NIOSH STF",
    action_items: "Caminos marcados · Cables/mangueras manejados · Agujeros cubiertos · Superficies mantenidas",
  },
  hand_injury: {
    title: "Prevención de Lesiones de Mano",
    hazards_reviewed: "Laceraciones · Lesiones por aplastamiento (pellizcos) · Punciones · Quemaduras · Amputaciones por equipo giratorio · Esfuerzo repetitivo",
    discussion_notes: "• Igualar el guante al peligro — resistente a cortes para afilado, químico para químico, impacto para impacto.\n• Identificar pellizcos antes de alcanzar — usar herramientas para posicionar, no manos.\n• Empujar, no jalar — cuando jalar falla, tu mano va contra lo que jalas.\n• Nunca tocar disco, tambor o banda en movimiento — LOTO antes de servicio.\n• Inspeccionar herramientas a diario; remover dañadas de servicio.\n• Arrodillarse o usar plataforma estable para trabajo fino.",
    references_cited: "OSHA 1926.95 · Estadísticas BLS · Política de Seguridad de Manos MASCI",
    action_items: "Guantes apropiados · Pellizcos identificados · Herramientas inspeccionadas · LOTO informado",
  },
  hearing_conservation: {
    title: "Conservación Auditiva",
    hazards_reviewed: "Pérdida auditiva permanente inducida por ruido · Tinnitus · Dificultad de comunicación enmascarando otros peligros · Daño acumulativo de carrera",
    discussion_notes: "• Nivel de acción OSHA 85 dBA TWA — la mayoría de maquinaria pesada lo excede.\n• Tapones O orejeras — ambos para ruido de impacto (martillo, tambor de milling, demolición).\n• Reemplazar tapones de espuma diariamente; limpiar reusables a diario.\n• Audiograma anual por programa de conservación auditiva.\n• Vigilar señales tempranas: zumbido, subir TV, perder conversaciones.\n• Señales de mano silenciosas durante trabajo ruidoso; pre-arreglar comunicación.",
    references_cited: "OSHA 1926.101 · OSHA 1910.95 · NIOSH REL",
    action_items: "Protección disponible · Usada en ruido alto · Audiograma anual",
  },
  respiratory_protection: {
    title: "Protección Respiratoria",
    hazards_reviewed: "Sílice · Asbesto · Humos de soldadura · Solventes de asfalto/pintura · Diésel · CO · Moho / polvo · Ajuste inadecuado permitiendo exposición",
    discussion_notes: "• Respirador requerido cuando los controles de ingeniería sean insuficientes.\n• Prueba de ajuste anual — cuantitativa o cualitativa — registrada.\n• Autorización médica antes de uso de respirador.\n• Igualar cartucho al contaminante — P100 para partículas, OV para vapores orgánicos.\n• Inspeccionar antes de cada uso; verificación de sello en cada colocación.\n• Barba / vello facial rompe el sello — afeitado en superficie de sello.\n• Cartuchos tienen vida útil — cambiar según horario.",
    references_cited: "OSHA 1910.134 · OSHA 1926.103 · Certificación NIOSH",
    action_items: "Pruebas de ajuste · Cartuchos en stock · Procedimiento de sello · Horario de cambio",
  },
  hazcom_sds: {
    title: "Comunicación de Peligros / SDS",
    hazards_reviewed: "Exposición química a producto desconocido · EPP equivocado · Incompatibilidades de almacenamiento · Disposición inadecuada · Pictogramas mal interpretados",
    discussion_notes: "• Cada químico en sitio tiene SDS — accesible.\n• Leer SDS antes del primer uso: peligros, EPP, almacenamiento, primeros auxilios, respuesta a derrame.\n• Etiquetas intactas y legibles — sin contenedores de transferencia sin marcar.\n• 9 pictogramas GHS — saber qué significa cada uno.\n• Segregación: inflamables aparte de oxidantes, ácidos aparte de bases.\n• Disposición según SDS y EPA / requisitos estatales — no a drenajes.",
    references_cited: "OSHA 1926.59 · OSHA 1910.1200 · GHS",
    action_items: "Carpeta SDS vigente · Etiquetas revisadas · Segregación · Disposición identificada",
  },
  site_walk: {
    title: "Recorrido Diario del Sitio / Evaluación de Peligros",
    hazards_reviewed: "Nuevos peligros del trabajo de ayer · Cambios por clima (agua, escarcha, daño por viento) · Equipo / material movido · Invasión pública · Trabajo de servicios desde último turno",
    discussion_notes: "• Capataz recorre toda la zona de trabajo antes de que las cuadrillas inicien.\n• Buscar algo nuevo o diferente de ayer: agua en zanja, barricadas desplazadas, tumbados, robo, vandalismo.\n• Verificar que sistemas de protección sigan en lugar.\n• Verificar tropiezos por movimiento nocturno de equipo / material.\n• Reponer / reemplazar lo faltante o dañado antes de que las cuadrillas entren.\n• Documentar e informar hallazgos en la reunión.",
    references_cited: "MASCI Site Walk SOP · OSHA Persona Competente",
    action_items: "Recorrido completado · Hallazgos informados · Correcciones registradas",
  },
  housekeeping_cleanup: {
    title: "Limpieza y Orden al Final del Turno",
    hazards_reviewed: "Tropiezos por material dejado · Robo de herramientas / equipo no asegurado · Lesión pública por peligros abiertos · Contaminación de drenaje por derrames · Vandalismo / invasión",
    discussion_notes: "• 15 minutos de orden al final de cada turno — no negociable.\n• Herramientas y equipo pequeño bajo llave; equipo grande estacionado seguro.\n• Zanjas / estructuras abiertas cubiertas, barricadas, iluminadas.\n• Dispositivos MOT restaurados a configuración nocturna; luces revisadas.\n• Basura y escombros recogidos; sin plástico / desperdicio que pueda volar a drenajes.\n• Recorrer el sitio una última vez antes de salir.",
    references_cited: "OSHA 1926.25 · Estándar de Orden MASCI",
    action_items: "Herramientas aseguradas · Excavaciones cubiertas/iluminadas · MOT verificado · Recorrido completado",
  },
  new_hire_orientation: {
    title: "Orientación para Nuevos Contratados / Nuevos al Sitio",
    hazards_reviewed: "Desconocimiento de peligros del sitio · Equipo / procedimientos desconocidos · Mayor tasa de lesiones en primeros 30 días · EPP / capacitación faltante · Cultura desalineada en Stop Work",
    discussion_notes: "• CADA nuevo contratado y CADA persona nueva en el sitio recibe orientación específica del sitio.\n• Recorrer el sitio, señalar peligros, rutas de evacuación, botiquín, extintores.\n• Revisar TCP específico, JHP de su cuadrilla y permisos activos.\n• Reforzar Autoridad para Suspender Trabajo — la tienen desde el minuto uno.\n• Emparejar con compañero experimentado por 1-3 días.\n• Confirmar certificaciones / capacitación vigentes antes de iniciar.",
    references_cited: "OSHA 1926.21 · Procedimiento MASCI Nuevo Contratado",
    action_items: "Orientación completada · Compañero asignado · Registros de capacitación · Stop Work informado",
  },
  subcontractor_coordination: {
    title: "Coordinación con Subcontratistas",
    hazards_reviewed: "Actividades en conflicto · Desconocimiento mutuo de peligros · Diferentes estándares de seguridad · Falla de comunicación · Presión de horario sobre secuencia",
    discussion_notes: "• Cada sub en sitio ha tenido revisión pre-mob de seguridad con MASCI.\n• Reunión diaria de coordinación — quién está dónde, qué actividades, conflictos identificados.\n• Subs siguen estándares MASCI o más altos — nunca más bajos.\n• Autoridad MASCI para Suspender Trabajo se extiende a TODOS los trabajadores sin importar empleador.\n• JHP / plan pre-tarea compartido entre oficios en conflicto.\n• Incidentes reportados a MASCI mismo día.",
    references_cited: "Política OSHA Multi-Empleador · Pre-Cualificación MASCI",
    action_items: "Reps de seguridad sub identificados · Coordinación diaria · Stop Work extendido · JHPs compartidos",
  },
  emergency_action_plan: {
    title: "Plan de Acción de Emergencia / Evacuación",
    hazards_reviewed: "Emergencias del sitio (incendio, fuga de gas, clima severo, amenaza activa) · Evacuación inadecuada · Falla de contar personal · Salida bloqueada · Respuesta 911 demorada",
    discussion_notes: "• Cada sitio tiene un EAP publicado — punto de reunión, rutas primaria y secundaria, indicaciones 911, contactos en sitio.\n• Contar TODO el personal en el punto de reunión — sistema de compañero o registro.\n• Nunca re-entrar por herramientas, vehículos o material.\n• Quien llama al 911 permanece en línea; provee dirección del sitio e info de acceso.\n• Operadores apagan equipo seguramente si hay tiempo; si no, evacuar inmediatamente.\n• Ensayar el EAP cada 90 días o tras cambios mayores del sitio.",
    references_cited: "OSHA 1926.35 · NFPA 101 · Manejo Estatal / Local de Emergencias",
    action_items: "EAP publicado · Punto de reunión · Dirección 911 verificada · Ensayo programado",
  },
  fire_prevention: {
    title: "Prevención de Incendios y Uso de Extintores",
    hazards_reviewed: "Ignición de hot work · Derrame de combustible / vapor · Fumar cerca de inflamables · Selección equivocada de extintor · Trabajador no entrenado peleando incendio · Incendio de vehículo/equipo",
    discussion_notes: "• Combustibles a 35 pies+ de hot work; extintor listo.\n• Polvo químico ABC para la mayoría de incendios; CO2 para eléctrico; espuma para combustibles.\n• PASS: Pull, Aim, Squeeze, Sweep — solo combatir incendio menor a un cesto y solo con ruta de escape clara.\n• En duda — sal y llama al 911.\n• No fumar cerca de combustible, grasa, solventes — solo áreas designadas.\n• Inspeccionar extintores mensualmente; recargar tras uso.",
    references_cited: "OSHA 1926 Subparte F · NFPA 10 · NFPA 51B",
    action_items: "Extintores inspeccionados · Técnica PASS · Áreas designadas · Permisos hot work",
  },
};
