// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: general · 18 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_GENERAL = [
  {
    key: "demolition",
    domain: "general",
    title: "Demolition Operations",
    category: "Hazard-Specific",
    hazards_reviewed: "Falls from height · Struck-by falling debris · Premature collapse · Asbestos / lead exposure · Silica dust · Fire from cutting / hot work · Utility strike on remaining lines",
    discussion_notes: "• Engineering survey required before demo — identify floors, walls, materials, utilities.\n• Hazmat survey — asbestos, lead, PCBs identified and abated before demo.\n• Utilities cut, capped, locked out before demo.\n• Drop zones barricaded; spotters at perimeter.\n• Dust controls — water suppression and respiratory PPE.\n• Hot work permits for any cutting, welding, torching.\n• Daily inspection of remaining structure for stability.",
    references_cited: "OSHA 1926 Subpart T · OSHA 1926.850 · OSHA 1926.1101 (Asbestos) · OSHA 1926.62 (Lead)",
    action_items: "Engineering survey complete · Hazmat survey complete · Utilities locked out · Drop zones marked · Hot work permits ready",
  },
  {
    key: "hot_work",
    domain: "general",
    title: "Hot Work — Welding, Cutting, Grinding",
    category: "Procedure / SOP",
    hazards_reviewed: "Fire / explosion · Burns · UV / IR exposure (arc flash) · Welding fume inhalation · Hot slag igniting combustibles · Compressed gas cylinder rupture",
    discussion_notes: "• Hot Work Permit required and on site for any cutting/welding/grinding outside designated shop area.\n• Fire watch posted with extinguisher during AND 30 minutes after work.\n• Combustibles within 35 ft removed or shielded with welding blankets.\n• Cylinders chained upright, caps on, oxygen and fuel separated by 20 ft or 5-ft non-combustible barrier.\n• Eye protection — shade matched to amperage; bystanders shielded.\n• Ventilation or supplied air for galvanized, cadmium, or coated metal.",
    references_cited: "OSHA 1926 Subpart J · OSHA 1926.352 · NFPA 51B · ANSI Z49.1",
    action_items: "Hot work permit signed · Fire watch assigned · Combustibles cleared · Extinguisher staged · Cylinders secured",
  },
  {
    key: "forklift_telehandler",
    domain: "general",
    title: "Forklift / Telehandler Operations",
    category: "Tool / Equipment Specific",
    hazards_reviewed: "Tipping (loaded or unloaded) · Struck-by load · Run-over of pedestrians · Falls from forks (no riders) · Overhead clearance contact · Load too high to see over",
    discussion_notes: "• Operator certified (3-year cert + evaluation).\n• Pre-shift inspection logged.\n• Capacity at boom extension is LESS than at retracted — read the chart.\n• Load behind heel of forks; tilt back during travel.\n• Travel forks low, tines about 6 in. above ground.\n• Backing on ramps with load uphill; no riders ever.\n• Outriggers required for telehandler at full reach.",
    references_cited: "OSHA 1926.602 · OSHA 1910.178 · ANSI/ITSDF B56.6 · ANSI/ITSDF B56.1",
    action_items: "Operator cert current · Capacity chart on machine · Outriggers procedure · No-riders rule briefed",
  },
  {
    key: "ppe_general",
    domain: "general",
    title: "PPE — Daily Compliance Review",
    category: "Stretch & Flex",
    hazards_reviewed: "Head injury · Eye injury · Hearing loss · Foot injury · Hand laceration · Crush injury · Hi-vis non-compliance leading to struck-by",
    discussion_notes: "• Hard hat — Type II for traffic / impact zones; replace every 5 years or after impact.\n• Safety glasses with side shields — ANSI Z87 minimum.\n• Hi-vis Class 2 day / Class 3 night for all roadway work.\n• Steel or composite toe boots — no athletic shoes.\n• Cut-resistant gloves for sharp / abrasive work.\n• Hearing protection wherever noise > 85 dBA TWA.\n• PPE inspected before use; damaged PPE removed from service.",
    references_cited: "OSHA 1926 Subpart E · OSHA 1926.95 · ANSI Z87 / Z89 / Z41",
    action_items: "PPE inventory checked · Damaged PPE replaced · Hi-vis class verified · Hearing protection available",
  },
  {
    key: "stop_work",
    domain: "general",
    title: "Stop Work Authority",
    category: "Procedure / SOP",
    hazards_reviewed: "Imminent danger ignored · Production pressure overriding safety · Hazardous condition allowed to escalate · Near-miss not reported",
    discussion_notes: "• EVERY crew member has the authority and the responsibility to stop work for any safety concern.\n• No one will be retaliated against, ever, for stopping work in good faith.\n• Process: Stop. Notify. Correct. Resume. — all four steps.\n• Document the stop-work event so we can learn from it.\n• Stop work covers your own work, your crew, the public — anyone exposed.\n• If you're not sure, stop. Better to lose 5 minutes than a coworker.",
    references_cited: "OSHA General Duty Clause 5(a)(1) · MASCI Stop Work Policy",
    action_items: "Stop Work poster visible · Crew acknowledged authority · Recent stop-work events reviewed",
  },
  {
    key: "near_miss",
    domain: "general",
    title: "Near-Miss Reporting",
    category: "Procedure / SOP",
    hazards_reviewed: "Recurring near-misses leading to actual injury · Unreported hazards · Trend data lost · Culture of silence",
    discussion_notes: "• A near-miss is a free lesson. Treat it like an injury you got lucky on.\n• Report any unsafe act, unsafe condition, or close call — same shift.\n• Anonymous reporting available; no retaliation.\n• MASCI tracks near-misses for trends — this is how we prevent the next incident.\n• Don't blame the worker; fix the condition or process.\n• Examples: dropped tool from height, vehicle intrusion, suspended load swing wide, almost-trip-and-fall.",
    references_cited: "OSHA VPP · ANSI Z10 · MASCI Near-Miss Procedure",
    action_items: "Near-miss form available · Reporting reviewed · Recent reports discussed · Corrective actions tracked",
  },
  {
    key: "stretch_flex",
    domain: "general",
    title: "Stretch & Flex / Daily Huddle",
    category: "Stretch & Flex",
    hazards_reviewed: "Strains and sprains · Soft-tissue injuries · Cold muscle injury · Repetitive motion · Slips/trips/falls during first hour of shift",
    discussion_notes: "• 5-minute stretch routine before work — neck, shoulders, back, hips, hamstrings.\n• Walk through today's task list and identify anything new or unusual.\n• Confirm crew assignments and equipment for the shift.\n• Identify weather concerns (heat, cold, lightning, wind, rain).\n• Confirm everyone is fit for duty — no impairment, illness, or fatigue concerns.\n• Quick safety reminder relevant to today's work.",
    references_cited: "MASCI Daily Huddle SOP · NIOSH Ergonomics",
    action_items: "Stretch routine completed · Today's tasks briefed · Weather check · Fit-for-duty confirmed",
  },
  {
    key: "slips_trips",
    domain: "general",
    title: "Slips, Trips & Falls (Same-Level)",
    category: "Hazard-Specific",
    hazards_reviewed: "Slip on wet/oily/icy surfaces · Trip on hoses, rebar, debris · Fall on uneven terrain · Twisted ankle from holes / soft spots · Carrying load while walking",
    discussion_notes: "• Most common injury cause on heavy civil — and most preventable.\n• Walking surfaces clear of hoses, cords, rebar — coil and stack.\n• Walk paths defined and marked through the work site.\n• Boots with aggressive tread; replace when worn.\n• Don't carry loads that block your view of feet.\n• Salt/sand or sweep ice and debris.\n• Holes covered or barricaded — flag uneven ground.",
    references_cited: "OSHA 1926.25 · OSHA 1926.501 · NIOSH STF",
    action_items: "Walk paths marked · Cords/hoses managed · Holes covered · Walking surfaces maintained",
  },
  {
    key: "hand_injury",
    domain: "general",
    title: "Hand Injury Prevention",
    category: "Hazard-Specific",
    hazards_reviewed: "Lacerations · Crush injuries (pinch points) · Punctures · Burns · Amputations from rotating equipment · Repetitive strain",
    discussion_notes: "• Match the glove to the hazard — cut-resistant for sharp, chemical for chemical, impact for impact.\n• Identify pinch points before reaching — use tools to position, not hands.\n• Push, don't pull — when pulling fails, your hand goes into what you're pulling against.\n• Never touch a moving blade, drum, conveyor — LOTO before service.\n• Inspect tools daily; remove damaged tools from service.\n• Take a knee or use a stable platform for fine work.",
    references_cited: "OSHA 1926.95 · BLS Injury Statistics · MASCI Hand Safety Policy",
    action_items: "Task-appropriate gloves issued · Pinch points identified · Tools inspected · LOTO procedures briefed",
  },
  {
    key: "hearing_conservation",
    domain: "general",
    title: "Hearing Conservation",
    category: "Hazard-Specific",
    hazards_reviewed: "Permanent noise-induced hearing loss · Tinnitus · Communication difficulty masking other hazards · Cumulative damage over career",
    discussion_notes: "• OSHA action level 85 dBA TWA — most heavy iron exceeds this.\n• Earplugs OR earmuffs — both for impact noise (jackhammer, milling drum, demolition).\n• Replace foam plugs daily; clean reusables daily.\n• Annual audiogram per the hearing conservation program.\n• Watch for early signs: ringing in ears, having to turn up TV, missing conversations.\n• Quiet hand signals during high-noise work; pre-arrange comms.",
    references_cited: "OSHA 1926.101 · OSHA 1910.95 · NIOSH REL",
    action_items: "Hearing protection available · Worn during high-noise work · Annual audiogram scheduled",
  },
  {
    key: "respiratory_protection",
    domain: "general",
    title: "Respiratory Protection",
    category: "Procedure / SOP",
    hazards_reviewed: "Silica · Asbestos · Welding fumes · Asphalt / paint solvents · Diesel exhaust · CO · Mold / dust · Inadequate fit allowing exposure",
    discussion_notes: "• Respirator required when engineering controls are insufficient.\n• Annual fit testing — quantitative or qualitative — recorded.\n• Medical clearance before respirator use.\n• Match cartridge to contaminant — P100 for particulates, OV for organic vapors.\n• Inspect respirator before each use; user seal check every donning.\n• Beards / facial hair break the seal — clean shave at sealing surface.\n• Cartridges have service life — change per the schedule.",
    references_cited: "OSHA 1910.134 · OSHA 1926.103 · NIOSH respirator certification",
    action_items: "Fit tests current · Cartridges in stock · Seal-check procedure briefed · Schedule for cartridge change",
  },
  {
    key: "hazcom_sds",
    domain: "general",
    title: "Hazard Communication / SDS",
    category: "Procedure / SOP",
    hazards_reviewed: "Chemical exposure from unknown product · Wrong PPE for chemical · Storage incompatibilities (flammable + oxidizer) · Improper disposal · Pictograms misunderstood",
    discussion_notes: "• Every chemical on site has an SDS — readily accessible.\n• Read SDS before first use: hazards, PPE, storage, first aid, spill response.\n• Container labels intact and legible — no unmarked transfer containers.\n• 9 GHS pictograms — know what each one means.\n• Storage segregation: flammables apart from oxidizers, acids apart from bases.\n• Disposal per SDS and EPA / state requirements — not into storm drains.",
    references_cited: "OSHA 1926.59 · OSHA 1910.1200 · GHS",
    action_items: "SDS binder current · Labels checked · Storage segregation verified · Disposal location identified",
  },
  {
    key: "site_walk",
    domain: "general",
    title: "Daily Site Walk / Hazard Assessment",
    category: "Stretch & Flex",
    hazards_reviewed: "New hazards from yesterday's work · Weather-induced changes (water, frost, wind damage) · Equipment / material moved · Public encroachment · Utility work since last shift",
    discussion_notes: "• Foreman walks the entire work zone before crews start.\n• Look for anything new or different from yesterday: water in trench, displaced barricades, knockdowns, theft, vandalism.\n• Verify protective systems still in place.\n• Check for trip hazards from overnight equipment / material movement.\n• Reset / replace anything missing or damaged before crews enter.\n• Document and brief findings to crew at huddle.",
    references_cited: "MASCI Site Walk SOP · OSHA Competent Person",
    action_items: "Walk completed before crews start · Findings briefed · Corrections logged",
  },
  {
    key: "housekeeping_cleanup",
    domain: "general",
    title: "End-of-Shift Cleanup & Housekeeping",
    category: "Stretch & Flex",
    hazards_reviewed: "Trip hazards from material left out · Theft of unsecured tools / equipment · Public injury from open hazards overnight · Storm drain contamination from spills · Vandalism / encroachment",
    discussion_notes: "• 15 minutes of housekeeping at end of every shift — non-negotiable.\n• Tools and small equipment locked up; large equipment parked safely.\n• Open trenches / structures covered, barricaded, lighted.\n• MOT devices restored to night-time configuration; lights checked.\n• Trash and debris collected; no plastic / waste left to blow into storm drains.\n• Walk the site one last time before leaving.",
    references_cited: "OSHA 1926.25 · MASCI Housekeeping Standard",
    action_items: "Tools secured · Excavations covered/lit · MOT verified · Walk-through completed",
  },
  {
    key: "new_hire_orientation",
    domain: "general",
    title: "New Hire / New-to-Site Orientation",
    category: "Procedure / SOP",
    hazards_reviewed: "Unfamiliarity with site hazards · Unknown equipment / procedures · Higher injury rate in first 30 days · Missed PPE / training requirements · Cultural mismatch on Stop Work",
    discussion_notes: "• EVERY new hire and EVERY person new to this site gets a site-specific orientation.\n• Walk the site, point out hazards, evacuation routes, first-aid kit, fire extinguishers.\n• Review project-specific TCP, JHP for their crew, and any active permits.\n• Reinforce Stop Work Authority — they have it from minute one.\n• Pair with experienced buddy for first 1-3 days.\n• Confirm required certs / training current before they start.",
    references_cited: "OSHA 1926.21 · MASCI New Hire Procedure",
    action_items: "Site orientation completed · Buddy assigned · Training records verified · Stop Work Authority briefed",
  },
  {
    key: "subcontractor_coordination",
    domain: "general",
    title: "Subcontractor Coordination",
    category: "Procedure / SOP",
    hazards_reviewed: "Conflicting work activities · Unfamiliar with each other's hazards · Different safety standards · Communication breakdown · Schedule pressure overriding sequence",
    discussion_notes: "• Every sub onsite has had pre-mob safety review with MASCI.\n• Daily coordination meeting — who's where, what activities, conflicts identified.\n• Subs follow MASCI safety standards or higher — never lower.\n• MASCI Stop Work Authority extends to ALL workers regardless of employer.\n• JHP / pre-task plan shared between conflicting trades.\n• Incidents reported to MASCI same day.",
    references_cited: "OSHA Multi-Employer Citation Policy · MASCI Subcontractor Pre-Qual",
    action_items: "Sub safety reps identified · Daily coordination scheduled · Stop Work Authority extended · JHPs cross-shared",
  },
  {
    key: "emergency_action_plan",
    domain: "general",
    title: "Emergency Action Plan / Evacuation",
    category: "Procedure / SOP",
    hazards_reviewed: "Site-wide emergencies (fire, gas leak, severe weather, active threat) · Inadequate evacuation · Failure to account for personnel · Blocked emergency egress · Delayed 911 response",
    discussion_notes: "• Every site has a posted EAP — assembly point, primary and secondary evacuation routes, 911 directions, on-site emergency contacts.\n• Account for ALL personnel at the assembly point — buddy system or sign-in.\n• Never re-enter for tools, vehicles, or material.\n• 911 caller stays on line; provide site address and gate access info.\n• Equipment ops shut down equipment safely if time allows; otherwise evacuate immediately.\n• Drill the EAP every 90 days or after major site changes.",
    references_cited: "OSHA 1926.35 · NFPA 101 · State / Local Emergency Management",
    action_items: "EAP posted · Assembly point known · 911 address verified · Drill scheduled",
  },
  {
    key: "fire_prevention",
    domain: "general",
    title: "Fire Prevention & Extinguisher Use",
    category: "Procedure / SOP",
    hazards_reviewed: "Hot work ignition · Fuel spill / vapor ignition · Smoking near flammables · Improper extinguisher selection · Untrained worker fighting fire · Vehicle/equipment fire",
    discussion_notes: "• Combustibles 35 ft+ from any hot work; extinguisher staged.\n• ABC dry chemical for most jobsite fires; CO2 for electrical; foam for fuels.\n• PASS: Pull, Aim, Squeeze, Sweep — only fight a fire smaller than a wastebasket and only with a clear escape path.\n• When in doubt — get out and call 911.\n• No smoking around fuel, grease, or solvents — designated areas only.\n• Inspect all extinguishers monthly; recharge after any use.",
    references_cited: "OSHA 1926 Subpart F · NFPA 10 · NFPA 51B",
    action_items: "Extinguishers inspected · PASS technique briefed · Designated smoking areas · Hot work permits in use",
  },
];
