// iter302 · Dedicated `lab` domain ES translations.
// Domain: lab · 4 ES translations · mirrors `./lab.js` exactly (block count + types).
// Operator-approved tone benchmark: lab_nuclear_gauge_handling.
// Field-Spanish discipline: `troca`, `string-line` (untranslated), `cuadrilla del
// screed`, brief regulatory glosses on first use (RSO → "Responsable de Seguridad
// Radiológica"). NRC, ANSI, OSHA, ASTM, AASHTO preserved as-is per regulatory
// anchor convention from iter279/iter297/iter300.

export const TOPICS_LAB_ES = {
  lab_nuclear_gauge_handling: {
    title: "Medidor Nuclear de Densidad — Custodia, Transporte y Respuesta",
    incident_pattern:
      "Los incidentes con medidor nuclear a nivel de campo / laboratorio rara vez involucran daño por radiación al trabajador — involucran un medidor perdido, robado o dañado que de pronto se convierte en un incidente federal. El patrón se repite cada año. El técnico termina una prueba de densidad en pavimento al final del día, asegura el medidor en la caja abierta del camión en vez de adentro de la cabina, entra a la gasolinera, y regresa para encontrar el camión forzado. O el técnico pone el medidor en el hombro del camino durante una revisión rápida de string-line, y un camión lo aplasta. O el medidor pasa la noche en un vehículo estacionado en un patio sin seguridad y para la mañana ya lo sacaron. Ninguno de esos escenarios causa lesión directa — pero cada uno dispara un reporte ante la NRC, un paro de varios días en las operaciones de prueba, y una multa que llega a las decenas de miles de dólares. El técnico que perdió el medidor casi nunca falló en seguridad. Falló en custodia. En el trabajo con medidor nuclear, la custodia ES la seguridad.",
    hazards_reviewed:
      "Robo de vehículo desatendido · Daño por golpe de vehículo durante prueba en la carretera · Daño a la varilla de la fuente radiactiva por caída o pellizco · Uso no autorizado por personal sin licencia · Pérdida en tránsito (caja mal asegurada) · Contacto del público con un medidor abandonado · Incidente reportable a la NRC por cualquiera de los anteriores · Exposición personal a radiación por manejo prolongado e incorrecto",
    discussion_notes:
      "• La custodia, no la radiación, es el riesgo del día a día. El medidor nunca sale de su vista fuera del gabinete de almacenamiento.\n• Transporte: medidor en la caja cerrada con llave, caja asegurada adentro de la cabina. Nunca en la caja abierta, nunca en la caja de herramientas.\n• Almacenamiento: al final del día, regreso al lugar licenciado. Nada de pasar la noche en vehículos, ni en oficinas sin seguridad, ni 'mañana lo traigo de vuelta.'\n• Solo usuarios autorizados. Si usted no está en la licencia de la NRC, no toca el medidor — ni siquiera para llevarlo del banco a la troca.\n• En la carretera: medidor a los pies del técnico o adentro de la caja a su lado. Nunca en el pavimento atrás de usted. Nunca en la línea de la rueda.\n• Si un medidor es golpeado, se cae, o queda dañado — pare. Retroceda seis pies. Llame al RSO (Responsable de Seguridad Radiológica). No lo levante para revisarlo.\n• Si un medidor se pierde o lo roban: avise al RSO dentro de la hora. El reloj de 24 horas para reportar a la NRC empieza al descubrir la pérdida, no al final del turno.\n• Interacción con el público: 'Este es un instrumento regulado, por favor manténgase a seis pies.' Voz calmada. La curiosidad no debe llegar al contacto.\n• Conciencia del sitio: camiones, rodillos y la cuadrilla del screed se mueven todo el tiempo. El medidor se queda a los pies del técnico — no donde un rodillo lo va a aplastar.\n• EPP: chaleco reflectivo + bota de casquillo. El medidor mismo no requiere EPP adicional en operación normal. El dosímetro de radiación, si el RSO se lo asignó, se usa en cada turno.",
    references_cited:
      "10 CFR 30 · 10 CFR 71 · Licencia de Materiales NRC · Programa Estatal de Control de Radiación · ANSI N43.3 · SOP del RSO de la empresa",
    action_items:
      "Línea de vista de custodia reforzada · Seguridad de transporte verificada (caja con llave, adentro de la cabina) · Lista de usuarios autorizados revisada · Vía de escalación por pérdida / robo / daño identificada por nombre · Contacto del RSO verificado para el turno actual · Presencia del dosímetro confirmada",
  },
  lab_oven_burns_chemistry: {
    title: "Hornos de Laboratorio, Charolas Calientes y Química de Extracción de Bitumen",
    incident_pattern:
      "El incidente serio del horno de laboratorio rara vez es la quemadura. La quemadura es real — una charola de 325°F agarrada sin guantes de gauntlet manda al técnico a urgencias por el resto del turno — pero el incidente que mata es el de la química. Un trabajo de extracción de bitumen usa un solvente inflamable (tolueno, hexano, o uno de los reemplazos de perc / N-propyl-bromide). El técnico abre el horno para cambiar muestra, deja el trapo con solvente en el banco, el vapor se mueve hacia la masa caliente del horno, y un arco eléctrico de la placa caliente o del stir-bar encuentra la nube. Incendio relámpago. El laboratorio es un espacio cerrado. La salida es una sola puerta. La mayoría de estos incidentes vienen de dos compresiones: reúso de solvente para ahorrar (la concentración de vapor sube) y disciplina de 'nomás esta una rapidita' en la campana extractora. El horno no lo hizo. El vapor sí. El horno fue nada más la fuente de ignición esperando.",
    hazards_reviewed:
      "Quemaduras por contacto con horno, charola o pinzas · Incendio relámpago por vapor de solvente + fuente de ignición · Inhalación de vapor de solvente en laboratorio cerrado · Ignición de inflamables cercanos por superficie caliente · Quemaduras en los ojos por salpicadura de solvente durante extracción caliente · Resbalón por solvente o residuo de asfalto cerca del horno · Liberación de presión por muestra sellada calentada · Salida de emergencia insuficiente en laboratorio pequeño durante incendio",
    discussion_notes:
      "• Guantes de gauntlet — largo hasta la muñeca, de cuero o aramida — para cualquier charola de horno arriba de 200°F. Los guantes de algodón de trabajo no son guantes a 325°F.\n• Cargar con las dos manos cualquier charola arriba de 250°F. Cargar con una mano es como los técnicos tiran charolas calientes sobre sus propios pies.\n• Los trapos con solvente van al bote metálico tapado. No al banco. No a la basura. No 'nomás un momento.'\n• La hoja de la campana extractora a la altura marcada de operación. Si el indicador de flujo de aire está en amarillo o rojo, no se hace extracción caliente en esa campana.\n• El reúso de solvente está bien para el costo. El reúso sin revisar el nivel del bote es como la concentración de vapor sube arriba del LEL.\n• Cuando el horno se abre, el solvente del banco se quita. O tapado, o en la campana, o de regreso al gabinete. Horno abierto + solvente abierto + mismo banco = espere.\n• Las muestras selladas nunca van al horno. La liberación de presión de una lata tapada a 325°F le ha clavado vidrio en el antebrazo a un técnico.\n• Salida: conozca la puerta antes de prender. Los incendios de laboratorio doblan su tamaño cada 30 segundos. No se resuelve hacia la puerta.\n• Si un incendio pequeño empieza en la campana: cierre la hoja, corte el gas, dispare la supresión. No meta la mano para sacar la muestra.\n• Si el cuarto hace flash: salga. La muestra se reemplaza. El laboratorio se reemplaza. Usted no.",
    references_cited:
      "OSHA 1910.1450 (Norma de Laboratorios) · NFPA 45 (Protección Contra Incendios en Laboratorios) · ASTM D2172 (Extracción de Bitumen) · AASHTO T 164 · SOP del Laboratorio",
    action_items:
      "Condición de guantes de gauntlet revisada · Nivel del bote de solvente verificado · Hoja de la campana e indicador de flujo confirmados · Ruta de salida despejada y conocida · Ubicación del sistema de supresión identificada · Política de muestras selladas reafirmada",
  },
  lab_core_drilling_silica: {
    title: "Perforación de Núcleos de Pavimento — Sílice, Retroceso de Sierra y Disciplina de Corte Húmedo",
    incident_pattern:
      "Perforar núcleos en el banco del laboratorio se ve rutinario hasta que algo se atora. La broca de diamante pega un fragmento duro del agregado, el núcleo se traba en el barril, y el torque de la sierra se transfiere a las muñecas del técnico. La lesión casi siempre es una cortada en el antebrazo, un esguince de muñeca, o — cuando el técnico trató de liberar una broca atorada con la sierra todavía girando — un tendón rasgado. Debajo de ese riesgo mecánico va el silencioso: sílice cristalina respirable. El corte húmedo es requerido por una razón, pero la razón es invisible. El agua aplaca el polvo en el punto de corte; el lodo se seca después en el banco, en el piso, en la ropa del técnico, y en los racks donde los núcleos pasan la noche. A la mañana siguiente ese lodo seco se levanta como polvo aerotransportado. Cinco años de eso en ciclo diario de laboratorio es la diferencia entre una jubilación sana y silicosis a los cincuenta y ocho.",
    hazards_reviewed:
      "Cortada de antebrazo / muñeca por retroceso durante atorón · Esfuerzo de tendón por transferencia de torque en broca atorada · Sílice cristalina respirable de corte seco O por resuspensión de lodo seco · Lesión ocular por salpicadura de lodo · Choque eléctrico por sierra mojada sin GFCI · Resbalón en banco o piso mojado · Lesión en mano por manejo de muestra sin guantes",
    discussion_notes:
      "• El corte húmedo no es opcional. La línea de agua se queda prendida mientras la sierra esté prendida. Nada de atajos en seco para 'nomás terminar este último núcleo.'\n• Si la broca se atora, no la safe con la sierra girando. Suelte el gatillo. Espere parada total. Después evalúe.\n• Dos manos en la sierra — la agarradera del frente más la trasera. Cortes con una mano son como se tuerce la muñeca en un atorón.\n• Goggles de salpicadura para el técnico. Los lentes de seguridad estándar no son a prueba de salpicadura de lodo.\n• GFCI en cada contacto de sierra mojada. Si el GFCI brinca, no se brinca. Se averigua por qué.\n• La limpieza del lodo es parte del corte, no una tarea aparte. Esponja mojada, después tirar según el plan de derrames. No deje que se seque en el banco.\n• Los núcleos al salir de la sierra van a un rack con bandeja de goteo. No al banco. No al piso. El lodo seco es polvo al Día Dos.\n• Pisos barridos mojados, no en seco. Una escoba en lodo seco es el peor método posible de entregar sílice.\n• EPP mínimo: goggles de salpicadura, guantes de nitrilo o resistentes a químicos, mandil. Hacer núcleos sin mandil deja lodo con sílice en la ropa que el técnico se lleva a casa.\n• N95 o mejor en el laboratorio si hay lodo seco visible. Si usted puede ver el polvo, el polvo ya pasó el umbral.",
    references_cited:
      "OSHA 1926.1153 (Sílice Cristalina Respirable) · ASTM D5361 (Muestreo de Pavimentos Asfálticos) · Jerarquía de Controles de NIOSH · SOP del Laboratorio",
    action_items:
      "Línea de agua de corte húmedo verificada · GFCI probado en contacto de sierra · Goggles de salpicadura y guantes entregados · Protocolo de limpieza de lodo revisado · Rack de núcleos con bandeja de goteo en uso · Horario de barrido mojado confirmado",
  },
  lab_solvent_handling_ppe: {
    title: "Solventes de Laboratorio — Selección, EPP y Realidades de Disposición de Trapos",
    incident_pattern:
      "Las lesiones por solvente de laboratorio casi nunca pasan en eventos grandes y dramáticos. Pasan un turno a la vez. Un técnico reúsa solvente de extracción entre varias muestras para ahorrar. La campana extractora estaba 'casi cerrada.' Se usaron guantes de látex porque eso es lo que había en el clóset. Los trapos con solvente fueron a la basura regular porque el bote metálico estaba lleno. Ninguna de esas decisiones causó una lesión ese día. Cinco años después, el técnico tiene dermatitis crónica en los antebrazos, un temblor que puede o no ser por exposición a toxina reproductiva del reemplazo del perc, y un casi-incendio por una pila de trapos que se auto-calentó en una tina plástica tapada de la noche a la mañana. El solvente no tiene que ser el que OSHA le escribió la SDS. La realidad lado-laboratorio es que el inventario moderno de solventes — N-propyl bromide, percloroetileno, tolueno, hexano, mineral spirits, dicloromentano — es un problema de exposición crónica manejado con EPP diario y disciplina de campana, no con respuesta a incidente agudo.",
    hazards_reviewed:
      "Contacto crónico en piel por permeación del guante (el látex falla casi todos los solventes de asfalto) · Exposición por inhalación por disciplina de campana inadecuada · Toxicidad reproductiva y neurológica por reemplazos de perc / NPB · Contacto en ojos por salpicadura sin EPP a prueba de salpicadura · Incendio de pila de trapos auto-calentados por disposición incorrecta · Ignición de solvente por contenedor abierto cerca de horno o placa caliente · Contaminación cruzada por reúso de solvente sin monitoreo",
    discussion_notes:
      "• El material del guante importa. El látex es permeable a casi cualquier solvente de extracción de asfalto en minutos. Solo nitrilo, neopreno, o de grado químico.\n• Inspección del guante antes de cada tarea. Un hoyito de aguja es una falla del 100% para solventes orgánicos.\n• Hoja de la campana extractora a la altura marcada — usualmente 18 pulgadas. Hoja más alta = velocidad de captura perdida.\n• Verifique el flujo de aire de la campana a diario. ¿El indicador está en amarillo o rojo? No se hace trabajo con solvente en esa campana hasta que Mantenimiento la libere.\n• Goggles de salpicadura, no lentes de seguridad, cuando se vierte o se transfiere. Los lentes pierden contra una salpicadura de lado.\n• Mandil para cualquier extracción o vertido. El solvente en la bata pasa a la ropa de calle cuando el técnico sale.\n• El reúso de solvente es legítimo, pero registre el número de usos y el color visual. Un solvente pasado de su vida útil huele diferente y se ve diferente. Confíe en los dos.\n• Los trapos empapados van al bote metálico tapado. No al plástico. No a la basura. Vacíe el bote al gabinete de residuos antes de que pase de dos tercios.\n• Al final del turno: vacíe el bote de trapos. Un bote lleno dejado de la noche a la mañana es el incendio auto-calentado más común en laboratorios de asfalto.\n• Si se siente mareado, salga. El mareo es la primera señal — y la única señal — para varios solventes comunes. No se 'aguanta.'",
    references_cited:
      "OSHA 1910.1450 (Norma de Laboratorios) · OSHA 1910.1000 (PELs) · NFPA 45 · Guía de Bolsillo NIOSH · EPA TSCA (restricciones de perc / N-propyl bromide) · Biblioteca de SDS de la empresa",
    action_items:
      "Material del guante confirmado apropiado para los solventes en uso · Hoja + flujo de campana verificados · Goggles de salpicadura + mandil entregados · Bote de trapos vaciado al final del turno · Registro de reúso de solvente presente · Respuesta al mareo revisada",
  },
};
