// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: mot · 13 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_MOT = [
  {
    key: "mot_setup",
    domain: "mot",
    title: "MOT Setup & Work Zone Traffic Control",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Work-zone struck-by fatalities cluster at two specific moments: SETUP and TAKEDOWN. Crews tend to be safest in the middle of the day with the zone fully installed. But at 6 a.m. when the cones go down, and at 8 p.m. when they come up, the workers are inside the live lane, the buffer isn't built yet, and the public hasn't been conditioned to slow. The pattern is a single distracted driver, a 6-foot worker placing a cone, and a closing speed of 65+. The fix is upstream-to-downstream setup, downstream-to-upstream takedown — and treating the FIRST cone and the LAST cone as the deadliest objects on the job.",
    hazards_reviewed: "Struck-by vehicles entering work zone · Driver inattention / impaired drivers · Inadequate buffer / taper length · Worker exposure during setup and takedown · Night-time visibility · Equipment / vehicle interface inside work zone",
    discussion_notes: "• Approved Traffic Control Plan (TCP) on site and matches field conditions.\n• Setup from upstream to downstream; takedown reverse order — never face oncoming traffic.\n• Buffer / taper lengths matched to posted speed.\n• Devices clean, retroreflective, properly spaced.\n• Internal traffic-control plan separates workers from equipment inside the zone.\n• Night work: lighting min 5 fc, all workers in Class 3 hi-vis with retro bands.\n• Public traffic exposure controlled by positive protection where speed/volume warrant.",
    references_cited: "MUTCD Part 6 · FHWA Work Zone Safety · OSHA 1926 Subpart G · ATSSA Standards",
    action_items: "TCP onsite and signed · Devices match plan · Internal traffic plan briefed · Night lighting verified · Class 3 hi-vis confirmed",
  },
  {
    key: "flaggers",
    domain: "mot",
    title: "Flaggers & Public Traffic Exposure",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Flagger fatalities are remembered by name in this industry, and the pattern is almost always the same: lone position, no shadow vehicle behind them, a single distracted or impaired driver coming through the taper at speed. The flagger doesn't see the truck soon enough to step off — or they freeze. Sun-glare on the stop paddle, dark uniforms at dusk, and a long shift without rotation amplify it. The fix is positioning the flagger so they have an ESCAPE ROUTE — never trapped between barrier and traffic — and a shadow vehicle behind them in any zone with speed or volume. A flagger is the highest-exposure position on the entire crew.",
    hazards_reviewed: "Struck by passing motorist · Distracted / impaired drivers · Driver running stop paddle · Lone-worker exposure · Sun glare blinding flagger · Heat / cold stress",
    discussion_notes: "• Flagger is a certified position — current cert card on person.\n• Stop paddle, not a flag, in all paid traffic-control work.\n• Flagger station has clear escape route — never trapped between barrier and traffic.\n• Hi-vis Class 3 day, hi-vis with retro at night.\n• Two-way radio comms with crew and other flaggers.\n• Rotate flaggers every 2 hours in heat; provide water, shade, seating between rotations.\n• Position so flagger is visible for full stopping sight distance.",
    references_cited: "MUTCD Part 6E · ATSSA Flagger Cert · State Flagger requirements",
    action_items: "Flagger certs verified · Stop paddles in good condition · Escape route walked · Rotation schedule posted · Comms tested",
  },
  {
    key: "live_traffic",
    domain: "mot",
    title: "Live Traffic Exposure / Struck-By",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    incident_pattern: "Highway struck-by is the leading cause of construction fatalities, and the worker rarely sees it coming. The pattern: a crew member is heads-down on a task — sweeping, marking, holding a tape — and a single vehicle drifts through the taper. By the time the worker hears the tires, they have less than 1 second of reaction time. Most fatal intrusions happen at the BUFFER, not the work area, because the buffer is empty and drivers cut through it. The fix is positioning workers on the SHIELDED side of any barrier or equipment, never standing in an open lane, and treating the buffer as if a vehicle is already coming through it — because eventually one will.",
    hazards_reviewed: "Worker struck by vehicle · Distracted driver · Speeding · Vehicle intrusion through tapers · Limited reaction time at night · Lone worker exposure",
    discussion_notes: "• Highest fatality cause in our industry — treat every vehicle as a potential intrusion.\n• Always maintain situational awareness — one eye on traffic when working near open lanes.\n• Stand on the shielded side of barrier or equipment when possible.\n• Never cross open travel lanes on foot — use approved crossing points.\n• Work-zone intrusion alarms / shadow vehicles where speed and volume warrant.\n• Stop, get behind protection, call dispatch if vehicle penetrates buffer.",
    references_cited: "FHWA Work Zone Safety · OSHA 1926.201 · MUTCD Part 6 · NIOSH Highway Workers",
    action_items: "Buffer integrity verified · Shadow vehicle in place · Workers briefed on escape routes · Intrusion response reviewed",
  },
  {
    key: "mot_moving_trucks",
    domain: "mot",
    title: "MOT Placement from Moving Trucks",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Falls and ejections from MOT placement trucks happen in a very specific moment: the truck hits an unexpected bump, the worker on the back loses footing, and the tie-off either fails or wasn't on a rated anchor. The crews that have lost workers to this universally describe the same thing — they had been doing it the same way for years, the anchor was 'good enough,' and one bad pothole at 8 mph turned it into a fatality. The truck doesn't have to be going fast. The worker doesn't have to be careless. The fix is engineered anchors only, 5 mph hard cap, and zero mounting/dismounting while the truck is moving.",
    hazards_reviewed: "Falls from moving truck · Struck-by passing vehicle · Loss of grip / footing · Improper anchor for tie-off · Communication breakdown · Heat / fatigue",
    discussion_notes: "• Workers on the back of moving MOT truck must be 100% tied off to a rated, engineered anchor.\n• No improvised tie-off — guardrails and toolboxes are NOT anchors.\n• Truck speed during placement: 5 mph or less.\n• Driver and workers maintain constant communication via radio or hand signals.\n• No mounting/dismounting while truck is moving.\n• Workers never ride on equipment unless designated platform is provided.",
    references_cited: "OSHA 1926.501(b) · OSHA 1926.502 · MUTCD Part 6",
    action_items: "Harnesses inspected · Anchor points verified · Driver / crew comms tested · Speed limit enforced",
  },
  {
    key: "lane_closures",
    domain: "mot",
    title: "Lane Closures — Single & Multiple",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Lane-closure intrusions follow a predictable curve: the first hour after setup, the public hasn't conditioned to the new pattern, and 3-5 drivers will blow through cones before settling. That first hour is where intrusion fatalities happen. Multi-lane closures add a second pattern — drivers who realize too late they're in the wrong lane, swerve across the closed lane, and clip a worker or a piece of equipment. The fix is a shadow truck with TMA on the first hour at minimum, knockdown response (replace the cone, walk the line), and never letting the cone gap on a knocked-down section sit open for more than a minute.",
    hazards_reviewed: "Driver running closure · Crew exposed during setup · Inadequate taper for posted speed · Confusing signs · Cone knockover from wind / vehicle wake",
    discussion_notes: "• Setup ALWAYS upstream-to-downstream; takedown reverse.\n• First-truck = shadow truck with TMA where speed/volume requires it.\n• Cones / drums replaced if knocked down — re-up immediately.\n• 'Lane Closed' / merge signs visible at full stopping sight distance.\n• Cross-over point clearly delineated; arrow boards aimed correctly.\n• Verify temporary speed reduction signs placed where required.",
    references_cited: "MUTCD Part 6 · State DOT Lane Closure Standards · ATSSA Best Practices",
    action_items: "Devices match plan · Shadow vehicle in place · Speed reduction signage verified · Knockdown response plan",
  },
  {
    key: "shoulder_closures",
    domain: "mot",
    title: "Shoulder Closures",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Crews treat shoulder work as 'safer' than lane work. It is not. Errant drivers leave the travel lane at speed for exactly the reasons shoulders exist — distraction, drowsiness, mechanical issue, evasion of a hazard ahead. The shoulder is where they aim when they leave the lane. A worker in a shoulder closure with no positive barrier is taking an open-lane exposure. Combine with edge drop-offs from milling or trenching and a single errant vehicle becomes a multi-fatality. The fix is treating shoulder work as live-traffic exposure: shadow truck with TMA at high speed, positive barrier on the travel-lane side, and workers shielded by equipment when possible.",
    hazards_reviewed: "Errant vehicle striking shoulder workers · Tight working area · Vehicles using shoulder as escape lane · Edge drop-off hazards",
    discussion_notes: "• Treat shoulder as live traffic exposure — full PPE, full TCP.\n• Shadow vehicle / TMA recommended even on shoulder closures at high speed.\n• Watch for edge drop-offs — barricade where applicable.\n• Trench / pit operations on shoulder require positive barrier on travel-lane side.\n• Workers stay shielded by equipment / vehicle when feasible.",
    references_cited: "MUTCD Part 6 · FHWA Shoulder Operations · State DOT Standards",
    action_items: "Shadow vehicle staged · Edge drop-offs barricaded · Class 3 hi-vis · Position-of-protection identified",
  },
  {
    key: "detour_routing",
    domain: "mot",
    title: "Detour Routing & Road Closures",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Detour failures rarely cause a single big incident — they cause dozens of small ones. The pattern: a missing arrow at an intersection, a vandalized trailblazer, or contradictory signage sends drivers into the closure or onto a residential street that wasn't designed for the volume. Frustrated motorists then ignore the next round of signs, run cones, and create exposure for the next crew. Emergency response is the highest-stakes failure mode — a fire truck or ambulance hits the closure at speed because the detour wasn't communicated to dispatch. The fix is daily sign walks, advance coordination with local PD/Fire/EMS, and treating sign theft / vandalism as a same-day repair.",
    hazards_reviewed: "Drivers ignoring detour signs · Inadequate advance warning · Confusing or contradictory signage · Emergency vehicle access blocked · Local resident frustration / hostility",
    discussion_notes: "• Advance warning signs at all approaching intersections — minimum spacing per MUTCD.\n• 'DETOUR' arrow signs at every turn — no missing arrows.\n• Trailblazer signs along the detour route confirm motorists stay on path.\n• Coordinate with local fire / EMS / police for emergency response routing.\n• Communicate with local residents / businesses in advance.\n• Confirm signs daily — vandalism and theft are common.",
    references_cited: "MUTCD Part 6F · State DOT Standard Plans · Local PD coordination",
    action_items: "Sign inventory walked daily · Emergency services notified · Local outreach completed",
  },
  {
    key: "pavement_marking",
    domain: "mot",
    title: "Pavement Marking Operations (Striping)",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    incident_pattern: "Striping crews are the slowest-moving rolling work zone on the road, and the public is conditioned to faster traffic. The pattern of incidents: a thermoplastic truck rolling at 3-5 mph, a paint operator walking behind, and a motorist who closes from 70 mph in seconds without registering the speed differential. The strike happens at the trailing worker — the one watching the line, not the traffic. Secondary pattern is hot-thermoplastic burns to the operator's legs and feet when material splashes or a line breaks. The fix is multiple TMA shadow vehicles, a tail spotter watching only traffic, and burn-rated PPE that covers ankles up.",
    hazards_reviewed: "Struck-by traffic at low operating speed · Methylene chloride / MMA exposure · Hot thermoplastic burns · Glass bead splatter · Slips on wet paint · Fire / explosion (MMA)",
    discussion_notes: "• Striping crews work at slow speed — make extra sure motorists see them (additional shadow vehicles, large arrow boards).\n• Hot thermoplastic 400°F+ — long sleeves, thermal gloves, no skin exposure.\n• MMA epoxy: respiratory protection, no smoking, ignition sources removed.\n• Glass beads cause eye injury — full eye/face protection.\n• Workers downstream of paint kettle stay clear of fume plume.\n• Paint truck route pre-walked to verify obstacles cleared.",
    references_cited: "OSHA 1926.59 (HazCom) · MUTCD Part 6 · Material SDS",
    action_items: "Shadow vehicles staged · Burn-rated PPE · MMA SDS reviewed · Fire extinguisher staged",
  },
  {
    key: "sign_installation",
    domain: "mot",
    title: "Sign Installation & Removal",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Sign-install incidents split between two patterns: utility strikes on post drilling, and falls from aerial lifts on overhead truss installs. The first happens when an 811 ticket is skipped or the marks are misread — a fiber, gas, or power line lives 18 inches below where the auger is set, and the strike costs a worker's eyesight or starts a fire. The second happens when a crew member climbs out of the bucket to reach 'just a little further' on a guide-sign install. Buckets exist because the climb-out is what kills people. The fix is no-exceptions 811 + spotter on every drill, and no climbing the truss — reposition the bucket.",
    hazards_reviewed: "Struck-by traffic during install · Lifting strain · Falls from sign-mount aerial · Caught between auger and obstacles · Underground utility strike during post drilling",
    discussion_notes: "• 811 ticket required before any post drilling.\n• Two-person lift for any sign over 50 lb or oversized.\n• Aerial work for overhead signs: tie-off in bucket, no climbing on truss.\n• Sign panel slings rated for the load.\n• Auger no-go zones marked; spotter at fence lines and curbs.\n• Re-stripe pavement marks behind temporary signs after sign removal.",
    references_cited: "MUTCD Part 6 · OSHA 1926.453 (Aerial Lifts) · OSHA 1926.251",
    action_items: "811 ticket valid · Lifting plan · Aerial-lift fall protection · Slings inspected",
  },
  {
    key: "crash_cushion",
    domain: "mot",
    title: "Crash Cushion / Attenuator Setup",
    severity: "fatal_risk",
    category: "Procedure / SOP",
    incident_pattern: "Crash cushions exist to absorb an errant vehicle so the worker behind them lives. The pattern of failure in installation is rushing it — modules placed on the wrong anchor pattern, bolts driven before a locate is cleared, or a damaged module from a prior strike redeployed because it 'looks fine.' A used attenuator with internal damage will let a vehicle through at half the design speed. The installation crew is also exposed during install — they're working at the leading edge of the work zone with no attenuator yet protecting them. Treat the install itself as the highest-exposure task of the day, and don't redeploy a damaged module — ever.",
    hazards_reviewed: "Struck-by traffic during install · Pinch points between modules · Anchor bolt strikes · Heavy module lifts · Hidden damage on used attenuators",
    discussion_notes: "• Anchor bolts driven only after locate ticket cleared.\n• Module lifts — engineered slings, signal person, designated drop zone.\n• Workers stand outside line-of-tension during lift.\n• Inspect every module — damaged ones removed from service.\n• Reflective sheeting clean before placement.\n• Truck-mounted attenuator (TMA) on shadow vehicle confirmed operational.",
    references_cited: "MASH Test Level Standards · MUTCD Part 6 · State DOT Standards",
    action_items: "Locate ticket cleared · Slings inspected · Modules inspected · TMA operational",
  },
  {
    key: "vms_signs",
    domain: "mot",
    title: "Variable Message Signs (VMS / DMS)",
    severity: "serious_injury",
    category: "Tool / Equipment Specific",
    incident_pattern: "VMS incidents fall into two patterns: trailer tip-overs during mast raise, and overhead-line strikes when the mast catches what nobody looked up at first. The tip-overs happen when outriggers aren't fully extended or the ground gives — a 4,000-lb trailer with mast extended catches a gust of wind, the leading outrigger sinks 4 inches into soft asphalt, and the trailer goes over with the mast still up. The overhead strike pattern is identical to dump-bed strikes: someone raises a mast without looking up because the sky 'looked clear.' The fix is the same: walk it, look up, confirm clearance before any vertical motion.",
    hazards_reviewed: "Struck-by traffic during placement · Trailer tipping during lift / level · Electric shock from solar/battery system · Pinch points raising mast · Overhead clearance contact",
    discussion_notes: "• Place VMS on stable level ground — outriggers fully extended.\n• Verify overhead clearance before raising mast — power lines, trees.\n• Battery and solar system — keep away from sparks, no smoking around.\n• Lock mast at full height before walking away.\n• Message clear, legible, MUTCD-approved phrasing.\n• Secure trailer with hitch lock when unattended.",
    references_cited: "MUTCD Part 6F · Manufacturer's Operator Manual · OSHA 1926.405",
    action_items: "Outriggers set · Overhead clearance verified · Mast locked · Hitch locked",
  },
  {
    key: "barrier_placement",
    domain: "mot",
    title: "Concrete / Water-Filled Barrier Placement",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    incident_pattern: "Barrier-placement incidents follow two patterns. First — struck-by during install, because the barrier isn't there yet to protect the installers from the live lane. The crew is at maximum exposure for the 30-60 minutes it takes to place a run. Second — crush from suspended barrier when a pin isn't fully seated or a sling lets go. A 6,000-lb concrete segment dropping 18 inches will kill anyone underneath. The fix is the crew on the OFFSET side of the placement equipment (never between barrier and live traffic), pin engagement verified before the next lift, and a hard rule that nobody stands under a suspended load — no exceptions.",
    hazards_reviewed: "Struck-by passing traffic during placement · Crush from suspended barrier · Pinch points connecting segments · Lifting strain on water-filled units · Failure of improperly connected barrier",
    discussion_notes: "• Crew on offset side of placement equipment, never between barrier and live traffic.\n• Barrier slings rated; lift points marked or engineered.\n• Connection pins fully seated before next lift; no improvised connections.\n• Water-filled barrier requires water source — hydrant permit, hose secured.\n• Barrier deflection distance accounted for in design — workers behind it stay outside deflection zone.\n• Reflective delineators on every segment for night visibility.",
    references_cited: "MASH Test Levels · MUTCD Part 6 · OSHA 1926.251",
    action_items: "Slings rated · Connection pins verified · Deflection zone marked · Reflective delineators in place",
  },
  {
    key: "mot_survey_crew_exposure",
    domain: "mot",
    title: "Survey Crew Live-Traffic Exposure",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    role_context: ["surveyor","rodman","lead"],
    incident_pattern: "Survey crew struck-by incidents have a recognizable shape: a two-person crew running cross-sections or staking centerline, no closure in place because 'we're just here for an hour,' rodman in the lane reading the prism, instrument operator focused on the gun. The crew is heads-down on the work and conditions the public to expect them to move out of the way. A distracted driver — phone, radio, sun — closes the gap in 3 seconds. Most fatal hits are the rodman, not the instrument operator, because the rodman is the one in or near the lane. The fix is treating ANY survey work in the road shoulder or live lane as a closure-grade exposure: cones, hi-vis Class 3, a tail spotter, and a lawful pull-off whenever possible.",
    hazards_reviewed: "Rodman struck by passing motorist · Instrument operator struck on shoulder · Distracted driver crossing the line · Sun-glare blinding · Survey vehicle parked partly in lane",
    discussion_notes: "• Any survey shot in or near a live lane gets a real closure — cones to MUTCD spacing, advance warning sign upstream, and a tail spotter watching only traffic.\n• Hi-vis Class 3 on both crew members. Rodman with reflective tape on legs and arms — that's where headlights catch the eye.\n• Tail spotter has a radio AND a whistle. If they see a closing vehicle, they call AND blast — auditory cue is faster than visual recognition.\n• Survey vehicle parked OFF the pavement when possible. If the vehicle has to be on shoulder, hazards on and angle the wheels away from traffic so a hit doesn't push the vehicle into the crew.\n• Sun-glare matters. If the sun is behind your work zone in the morning or afternoon, schedule those shots when the sun is overhead. Cars literally cannot see you with sun in their eyes.\n• No 'just one more shot' if a closure is starting to break down. Pull, reset, then continue.\n• Lone survey work in live traffic — don't. Two-person minimum on any roadway exposure.\n• In the absence of true positive protection, your TAIL SPOTTER is the protection. Treat that position seriously.",
    references_cited: "MUTCD Part 6 · FHWA Work Zone Safety · ATSSA Best Practices · MASCI Survey SOP",
    action_items: "Cones / advance warning verified for survey window · Tail spotter assigned · Class 3 hi-vis confirmed · Sun-glare timing reviewed · Lone-work prohibition reinforced",
  },
];
