// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: office · 8 ES translations

export const TOPICS_OFFICE_ES = {
  office_distracted_driving: {
    title: "Manejar Distraído — Teléfonos, Café y el Trayecto",
    incident_pattern: "Los choques por manejo distraído golpean al personal de oficina a una tasa que el campo no ve, porque el personal de oficina maneja MÁS — entre obras, entre juntas, a comidas y de regreso. El patrón es benigno individualmente: un texto rápido de un PM, un vistazo a la navegación, un sorbo de café mientras te incorporas. Apila tres de esas cosas pequeñas en 10 segundos y cruzaste una línea central a 65 mph. El factor más consistente en choques de personal de oficina no es estado de embriaguez — es la inatención acumulada de una persona ocupada haciendo seis cosas mientras maneja. El arreglo es política y hábito, no tecnología.",
    hazards_reviewed: "Choque frontal / fuera de camino por inatención · Choque trasero en cambio de semáforo · Multa por uso de celular · Velocidad en zona escolar / construcción · Fatiga por días sobre-agendados · Comer / beber mientras maneja",
    discussion_notes: "• Teléfono boca abajo o en holder, en modo NO MOLESTAR. Las llamadas van al buzón. Los textos esperan.\n• Manos-libres sigue siendo distraído. La carga cognitiva importa, no solo la posición de las manos. Guarde la llamada para el estacionamiento.\n• Navegación fijada ANTES de poner el camión en marcha. Re-rutear mientras maneja es causa principal de choques relacionados con oficina.\n• Café, comida, papeleo — hágase a un lado. Los 90 segundos que cuesta es el seguro más barato que comprará.\n• Margen de horario. Si su día tiene cero margen, cada junta tarde se vuelve un viaje con exceso de velocidad. Construya holgura en su calendario.\n• Zonas de construcción — en ambas direcciones. Baje velocidad por las zonas PROPIAS de MASCI primero. Lidere la cultura.\n• Clima severo — hágase a un lado y espere. Lluvia a 70 mph no es manejar, es apostar.\n• Si está cansado, está manejando impedido. Hágase a un lado por 20 minutos. La junta esperará.",
    references_cited: "NHTSA Manejo Distraído · Leyes estatales de manos-libres · Política de Vehículo de Flota MASCI",
    action_items: "Política de NO-MOLESTAR-al-manejar reforzada · Mensaje de manos-libres-sigue-siendo-riesgoso discutido · Disciplina de margen de horario revisada · Regla de hacerse-a-un-lado por clima severo discutida",
  },
  office_site_visit_ppe: {
    title: "PPE de Visita a Obra y Expectativas para Visitantes",
    incident_pattern: "La mayoría de las lesiones a personal de oficina en sitios pasan en los primeros 5 minutos de llegar al jobsite. El patrón: llegar con ropa de oficina, sin hi-vis, sin casco, caminar hacia el foreman para encontrarlo, y meterse al radio de giro de un excavador o a la trayectoria de un dump truck retrocediendo. El visitante no conoce el sitio, los operadores no saben que el visitante viene, y el foreman está a 200 pies. El personal de oficina frecuentemente piensa que 'nomás vengo 5 minutos' justifica saltarse el PPE. La cuadrilla ha trabajado toda la mañana construyendo una cultura de PPE y el visitante la mina instantáneamente. El arreglo es PPE en el vehículo, sin excepciones.",
    hazards_reviewed: "Golpe-por de equipo en primera llegada · Tropezón / caída en terreno rugoso · Lesión ocular por escombros lanzados · Lesión de cabeza por bajo aéreo · Estrés por calor sin agua / sombra · Visitante minando la cultura de PPE de la cuadrilla",
    discussion_notes: "• Kit de PPE en cada vehículo de oficina: casco, chaleco hi-vis Clase 2, lentes de seguridad, guantes de cuero, botas de seguridad (o cubre-zapatos como respaldo para UNA visita).\n• Póngase el PPE ANTES de salir del vehículo. No después de caminar 50 pies por el estacionamiento. Antes.\n• Encuentre al foreman por RADIO o TELÉFONO antes de caminar. El foreman viene a USTED a un punto de encuentro seguro — no al revés.\n• Quédese en trayectos marcados. No corte por zonas de trabajo activas, aunque agregue 100 pies.\n• Firme en la caja de herramientas / hoja de firma. El sitio sabe quién está en sitio.\n• No aparezca a la hora de comida sin anuncio. Agende la visita. Deje que el foreman le avise a la cuadrilla.\n• Calor / frío — traiga agua, vístase para el clima, sepa dónde está el trailer de descanso.\n• Dé el ejemplo. La cuadrilla ve si SU PPE está bien. Siguen esa señal.",
    references_cited: "OSHA 1926.95 / .96 / .100 / .102 (PPE) · ANSI/ISEA 107 · SOP de Visitante MASCI",
    action_items: "Kit de PPE en cada vehículo de oficina verificado · Hábito de encontrar-al-foreman-primero reforzado · Política de visita-agendada revisada · Firma de visitante aplicada",
  },
  office_parking_lot_struck_by: {
    title: "Estacionamientos, Reversa y Conciencia Peatonal",
    incident_pattern: "Los incidentes de estacionamiento en sitios MASCI y oficinas de clientes pasan a las velocidades más lentas y aun así producen las lesiones de tobillo, rodilla y espalda más comunes del lado administrativo. El patrón: un admin o PM camina del vehículo a la puerta de oficina, mirando su teléfono por la confirmación de junta. Un chofer de pickup retrocediendo, también distraído, nunca lo ve. El contacto es a 3–5 mph. El peatón no cae duro pero se tuerce al esquivar — rodilla, tobillo, espalda. Otra variante: salir de una cabina hacia un vehículo estacionado junto al suyo. El filo de la puerta toca la siguiente puerta, el dueño se molesta, reclamo presentado. Velocidades lentas, grandes resultados.",
    hazards_reviewed: "Vehículo retrocediendo golpea-por · Resbalón en estacionamiento mojado / con hielo · Bajarse de banqueta a trayectoria de vehículo · Golpe de puerta a vehículo adyacente · Tropezón con topes · Problemas de visibilidad en invierno / poca luz",
    discussion_notes: "• Teléfono ABAJO al caminar. Ojos en el estacionamiento, en luces de reversa, en movimiento. El texto espera.\n• Camine en cruces marcados donde existan. Donde no, escoja la trayectoria más segura y manténgala.\n• Al retroceder — retroceda ANTES de que salgan los niños y peatones. O pase de paso si está disponible. O cámara de reversa, barrido de espejos, Y vistazo rápido sobre el hombro. Las cámaras solas no son suficiente.\n• Salga de su vehículo a un espacio LIBRE — no abra la puerta a ciegas al carril siguiente.\n• Invierno / mojado — botas con agarre en la suela, no zapatos de vestir. Un resbalón en el estacionamiento sí pasa a edad MASCI.\n• Estaciónese en espacios iluminados de noche. La visibilidad de SU vehículo importa tanto como la visibilidad desde SU vehículo.\n• Cuidado con personal de oficina y visitantes en sitios de cliente — no están acostumbrados a la escala de vehículos de construcción. Reduzca velocidad extra en estacionamientos de cliente.",
    references_cited: "OSHA Deber General · NHTSA Seguridad Peatonal · Política de Flota MASCI",
    action_items: "Hábito de teléfono-abajo-al-caminar discutido · Regla de cámara-más-espejo revisada · Discusión de calzado de invierno · Precaución-extra en estacionamiento de cliente reforzada",
  },
  office_heat_stress_visits: {
    title: "Estrés por Calor en Visitas de Verano a Obra",
    incident_pattern: "Las lesiones por calor a personal de oficina durante visitas de verano siguen un patrón específico. El visitante llega en ropa de oficina-casual, sin agua, camina el sitio por 30–45 minutos en calor de 95°F+, y solo se da cuenta que está en problemas cuando ya está sintomático — dolor de cabeza, mareo, náusea. Manejaron solos al sitio, y ahora tienen que manejar solos a casa mientras están sintomáticos por calor, lo cual es su propio riesgo de choque. El personal de oficina tiene menor tolerancia al calor que la cuadrilla de campo porque no están aclimatados al calor. Una caminata de 20 minutos para un trabajador de campo es un riesgo serio de salud para alguien que estuvo en AC toda la mañana.",
    hazards_reviewed: "Agotamiento por calor progresando a golpe de calor · Choque por manejar con síntomas de calor · Deshidratación · Quemadura solar / daño ocular por exposición prolongada · Subestimar el calor sin aclimatación",
    discussion_notes: "• Botella de agua en el vehículo, cada visita a obra, mayo a octubre. Beba antes, durante y después.\n• Agende visitas de verano en la mañana o tarde noche. Evite el pico de calor de 11 a.m. a 3 p.m.\n• Sombrero que sombree cara y cuello. Bloqueador solar. Las mangas largas son más frescas que la piel descubierta al sol directo.\n• Tome descansos en el trailer o en su vehículo con AC. No 'aguante.'\n• Vigile síntomas en usted y otros: dolor de cabeza, náusea, irritabilidad, mareo, silencio súbito. El agotamiento por calor progresa a golpe de calor RÁPIDO.\n• Si aparecen síntomas: a sombra o AC, beba agua con electrolitos, enfríe el cuerpo. Si los síntomas no resuelven en 15 minutos — ER.\n• Manejar con síntomas de calor es manejar impedido. Que alguien lo lleve. Llame a dispatch. Espere en el trailer.\n• Los nuevos contratados y visitantes NO están aclimatados. Trátelos más conservadoramente que la cuadrilla de campo.",
    references_cited: "OSHA Estrés por Calor · NIOSH Estrés por Calor · CDC Enfermedad por Calor · Política de Calor MASCI",
    action_items: "Hábito de agua-en-vehículo reforzado · Agendar visitas matutinas revisado · Conciencia de síntomas discutida · Regla de no-manejar-impedido reforzada",
  },
  office_lone_worker_checkin: {
    title: "Trabajador Solo / Realidades de Check-In en Obra",
    incident_pattern: "Los incidentes de trabajador solo en MASCI típicamente involucran un PM, un estimador o un vendedor que manejó a un jobsite remoto, se estacionó, caminó el proyecto solo, y o tuvo un evento médico (corazón, derrame, caída) o entró en interacción tensa con un cliente o un intruso. Nadie sabía exactamente dónde estaban. El teléfono no se había movido por 45 minutos. Para cuando alguien dio seguimiento, la situación se había vuelto seria. El arreglo no es glamoroso: dígale a alguien adónde va, fije una hora de check-in, y cumpla. No hemos tenido una fatalidad de esto — pero hemos tenido casi-accidentes que han cambiado qué tan seriamente tomamos los check-ins.",
    hazards_reviewed: "Evento médico sin nadie que responda · Resbalón / caída sin observador · Interacción tensa con intruso · Falla de vehículo en área de baja señal · Cliente hostil / escalada de disputa · Perdido / desorientado en área desconocida",
    discussion_notes: "• Dígale a alguien — dispatch, un admin, su gerente — adónde va y cuándo espera regresar. Texto funciona.\n• Fije una HORA de check-in, no solo intención. 'Mando texto para las 2:30.' Si pasa 2:30 sin texto, esa persona le llama.\n• Teléfono cargado antes de salir de oficina. Traiga cargador y power bank cargado para viajes más largos.\n• No entre a una situación hostil solo. ¿Disputa con cliente escalando? Retírese, llame a su gerente, regrese con compañero.\n• Intrusos / personas desconocidas en el sitio — no se enfrente solo. Llame a seguridad del sitio o policía local. Usted no es guardia de seguridad.\n• Falla de vehículo en área remota — quédese con el vehículo si es seguro. Salir caminando lo puede meter en peor problema.\n• Historial médico — si tiene cualquier condición que pueda dejarlo sin respuesta, el protocolo de check-in es doblemente importante.\n• Al final de la visita, mande texto 'libre' a la misma persona. Cierra el loop.",
    references_cited: "OSHA Trabajador Solo · ANSI/ASSP Z490 · Política de Visita de Campo MASCI",
    action_items: "Disciplina de hora de check-in reforzada · Hábito de cargar teléfono discutido · Política de des-escalación de interacción hostil revisada · Hábito de texto 'libre' al final fijado",
  },
  office_severe_weather_accountability: {
    title: "Responsabilidad por Clima Severo para Cuadrillas y Visitantes",
    incident_pattern: "Los eventos de clima severo agarran al personal de oficina en el peor momento — manejando de regreso de una visita, a media junta con cliente, o mientras la oficina cierra al final del día. El patrón de falla es contabilidad: la oficina asume que todas las cuadrillas están adentro, pero dos camiones siguen afuera. El campo asume que la oficina ha llamado a todos, pero tres visitantes siguen en sitio. Cuando un aviso de tornado llega o una tormenta eléctrica entra, nadie sabe con certeza quién está dónde. El arreglo es una persona — usualmente dispatch o admin — siendo dueña del proceso de revisar la lista durante eventos de clima.",
    hazards_reviewed: "Trabajador / visitante atrapado en tornado / tormenta severa · Golpe de rayo en sitio · Inundación súbita de sitios bajos · Daño por granizo a cuadrilla y equipo · Hipotermia / calor por exposición prolongada durante tormenta",
    discussion_notes: "• Una persona es el POC de clima durante un evento de clima severo. Usualmente dispatch o admin. Tienen la lista. Hacen las llamadas.\n• Revise el radar ANTES de salir de oficina en temporada de tormentas. Vigile frentes que se mueven rápido.\n• Regla de rayo: cuando VEA un rayo o ESCUCHE trueno, la cuadrilla de campo se mete. Regla 30/30 — 30 minutos después del último rayo antes de reanudar.\n• Aviso de tornado: a la estructura más segura disponible. Cuadrilla de campo a la oficina o edificio sólido, NO en vehículo, NO en trailer.\n• Lluvia severa / inundación súbita: evite sitios bajos hasta que las condiciones despejen. Muchos sitios de obra civil pesada están diseñados para inundarse — son canales.\n• Granizo: ponga vehículos bajo techo donde se pueda. Personas lejos de ventanas.\n• Contabilice TODO el personal durante un evento severo. Oficina, campo, choferes, visitantes. El POC revisa cada nombre en la lista.\n• Visitantes en sitio: avísenles antes de que salgan de la oficina que viene clima. Díganles que regresen directo cuando las condiciones se degraden.",
    references_cited: "NWS Conciencia de Clima Severo · OSHA Seguridad de Rayo · SOP de Clima Severo MASCI",
    action_items: "POC de clima designado · Regla 30/30 de rayo revisada · Mapeo de refugio de tornado verificado · Hábito de avisar a visitante sobre clima discutido",
  },
  office_slips_trips_falls: {
    title: "Resbalones, Tropezones y Caídas en el Ambiente de Oficina",
    incident_pattern: "Los incidentes de resbalón y caída en oficina son nada glamorosos y muy reales. El patrón: café derramado en la cocineta queda sin limpiar por una hora, alguien lo pisa con zapatos de vestir, y se cae. O un cable de poder cruzando una puerta durante un setup temporal, nunca recogido. O una escalera con un foco fundido, y alguien falla el último escalón en la esquina oscura. Ninguno de estos es dramático — pero juntos suman más lesiones de tiempo perdido de oficina que cualquier otra causa. Rodillas, tobillos, caderas, muñecas. La gente trabaja lesionada por semanas porque les da vergüenza una caída en el pasillo.",
    hazards_reviewed: "Resbalón en líquido derramado · Tropezón con cable de poder / orilla de tapete · Caída en escalera con poca luz · Resbalón en entrada con hielo · Caída de silla / banquito usado como escalera · Resbalón en baño",
    discussion_notes: "• Limpie derrames inmediatamente. No espere a alguien más. La siguiente persona que pase puede ser usted.\n• Señales de piso mojado cuando algo no puede limpiarse de inmediato. De verdad funcionan.\n• Cables de poder en setups temporales — pegados con cinta o ruteados alrededor del paso. Sin cables atravesando superficies de caminata.\n• Iluminación de escalera — reporte focos fundidos el mismo día. Facilidades los reemplaza.\n• Tapetes de entrada de invierno — mantenidos en su lugar, reemplazados cuando gastados. Los primeros 6 pies dentro de la puerta son donde pasan la mayoría de resbalones de invierno.\n• Banquito, no silla, para alcanzar algo alto. Tenemos banquitos. Úsenlos.\n• Limpieza del piso de baño — reporte pisos mojados a facilidades. La persona que se resbaló ahí el mes pasado fue usted.\n• ¿Cargando 4 cosas y caminando? Va a tirar una o caerse por una. Dos viajes es mejor que una caída.",
    references_cited: "OSHA 1910.22 · Guía NSC de resbalones/tropezones · Política de Seguridad de Oficina MASCI",
    action_items: "Hábito de limpiar-derrame-ya reforzado · Reporte de iluminación de escalera revisado · Manejo de cables en setups temporales discutido · Regla de banquito-no-silla reforzada",
  },
  office_fatigue_mental_load: {
    title: "Fatiga y Carga Mental — Cuando Está Cansado, Está Impedido",
    incident_pattern: "La fatiga mental es el equivalente de oficina al estrés por calor en campo — más lenta para desarrollarse, más fácil de ignorar, igual de peligrosa. El patrón: un PM trabaja días de 11 horas por dos semanas durante temporada ocupada, duerme mal, vive de café. Los errores se cuelan — un número de obra invertido, una cotización que le falta un renglón, un correo crítico que no se manda. El PM se culpa de no estar agudo. La causa real es deuda sostenida de sueño y fatiga de decisión. A largo plazo, este patrón lleva a depresión, estrés familiar y enfermedad física. Hemos perdido buena gente al burnout que empezó exactamente así.",
    hazards_reviewed: "Errores de decisión por privación de sueño · Choque por manejar fatigado · Errores en correo / contrato con impacto río abajo · Burnout / decline de salud mental · Estrés familiar · Enfermedad física por deuda sostenida de sueño",
    discussion_notes: "• El sueño no es opcional. Siete horas mínimo. Menos de eso por una semana es impacto cognitivo nivel manejar-impedido.\n• Tome sus vacaciones. Vacaciones acumuladas no ayudan a nadie — vacaciones usadas sí.\n• La fatiga de decisión es real. Las decisiones que toma a las 5 p.m. después de 10 horas de juntas no son sus mejores decisiones. Junte llamadas importantes más temprano en el día.\n• Cuando se cache cometiendo errores, no empuje más — pare. Camine. Hidrátese. Coma. Vuelva.\n• La salud mental no es debilidad. Hable con alguien. EAP es confidencial y útil. Los compañeros son útiles. La familia es útil.\n• Vigile a sus compañeros. Retirados, irritables, propensos a error — son las señales tempranas. Pregúntense unos a otros.\n• Teléfono apagado después de horas cuando se pueda. El trabajo estará ahí mañana. Sus reservas mentales no si no las reconstruye.\n• 988 — Línea de Crisis y Suicidio (llamar o textear). EAP MASCI para ayuda confidencial. La construcción tiene una de las tasas de suicidio más altas de cualquier industria. Esto importa.",
    references_cited: "CDC Fatiga · NIOSH Total Worker Health · 988 Línea de Suicidio y Crisis · EAP MASCI",
    action_items: "Prioridad de sueño discutida · Política de uso de vacaciones revisada · Conciencia de fatiga de decisión levantada · Info 988 / EAP compartida",
  },
};
