// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: office · 8 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_OFFICE = [
  {
    key: "office_distracted_driving",
    domain: "office",
    title: "Distracted Driving — Phones, Coffee, and the Commute",
    category: "Hazard-Specific",
    role_context: ["office","manager","estimator","sales"],
    incident_pattern: "Distracted-driving crashes hit office staff at a rate the field doesn't see, because office staff drive MORE — between jobs, between meetings, to lunches and back. The pattern is benign individually: a quick text from a PM, a glance at the navigation, a sip of coffee while merging. Stack three of those small things in 10 seconds and you've crossed a centerline at 65 mph. The most consistent factor in office-staff crashes isn't impairment — it's the cumulative inattention of a busy person doing six things while driving. The fix is policy and habit, not technology.",
    hazards_reviewed: "Head-on / off-road crash from inattention · Rear-end at signal change · Phone-handling violation citation · Speeding in school / construction zones · Fatigue from over-scheduled days · Eating / drinking while driving",
    discussion_notes: "• Phone face-down or in a holder, in DRIVE-DO-NOT-DISTURB mode. Calls go to voicemail. Texts wait.\n• Hands-free is still distracted. Cognitive load matters, not just hand position. Save the call for the parking lot.\n• Navigation set BEFORE you put the truck in gear. Re-routing while driving is a leading cause of office-related crashes.\n• Coffee, food, paperwork — pull over. The 90 seconds it costs is the cheapest insurance you'll buy.\n• Schedule margin. If your day has zero margin, every late meeting becomes a speeding trip. Build slack into your calendar.\n• Construction zones — both ways. Slow down through MASCI's OWN zones first. Lead the culture.\n• Severe weather — pull over and wait. Rain at 70 mph is not driving, it's gambling.\n• If you're tired, you're driving impaired. Pull over for 20 minutes. The meeting will wait.",
    references_cited: "NHTSA Distracted Driving · State hands-free laws · MASCI Fleet Vehicle Policy",
    action_items: "DND-while-driving policy reinforced · Hands-free still risky message discussed · Schedule-margin discipline reviewed · Severe-weather pull-over rule discussed",
  },
  {
    key: "office_site_visit_ppe",
    domain: "office",
    title: "Site Visit PPE and Visitor Expectations",
    category: "Procedure / SOP",
    role_context: ["office","manager","estimator","sales","visitor"],
    incident_pattern: "Most office-staff site injuries happen in the first 5 minutes of arriving at a jobsite. The pattern: arrive in office clothes, no hi-vis, no hard hat, walk toward the foreman to find them, and step into the swing radius of an excavator or into a backing dump truck path. The visitor doesn't know the site, the operators don't know the visitor is coming, and the foreman is 200 feet away. Office staff often think 'I'm just popping in for 5 minutes' justifies skipping PPE. The crew has worked all morning building a culture of PPE and the visitor undermines it instantly. The fix is PPE in the vehicle, no exceptions.",
    hazards_reviewed: "Struck-by equipment on first arrival · Trip / fall on rough site terrain · Eye injury from blown debris · Head injury from low overhead · Heat stress without water / shade · Visitor undermining crew PPE culture",
    discussion_notes: "• PPE kit in every office vehicle: hard hat, Class 2 hi-vis vest, safety glasses, leather gloves, safety boots (or shoe covers as a fallback for ONE site visit).\n• Put PPE on BEFORE you exit the vehicle. Not after you walk 50 feet across the parking area. Before.\n• Find the foreman by RADIO or PHONE before walking. The foreman comes to YOU at a safe meeting point — not the other way around.\n• Stay in marked walking paths. Do not cut across active work zones, even if it adds 100 feet.\n• Sign in at the gangbox / sign-in sheet. The site knows who's on-site.\n• Don't show up at lunch with no announcement. Schedule the visit. Let the foreman tell the crew.\n• Heat / cold — bring water, dress for the weather, know where the break trailer is.\n• Lead by example. The crew sees if YOUR PPE is right. They follow that signal.",
    references_cited: "OSHA 1926.95 / .96 / .100 / .102 (PPE) · ANSI/ISEA 107 · MASCI Visitor SOP",
    action_items: "PPE kit in every office vehicle verified · Find-the-foreman-first habit reinforced · Scheduled-visit policy reviewed · Visitor sign-in enforced",
  },
  {
    key: "office_parking_lot_struck_by",
    domain: "office",
    title: "Parking Lots, Backing, and Pedestrian Awareness",
    category: "Hazard-Specific",
    role_context: ["office","visitor","driver"],
    incident_pattern: "Parking-lot incidents at MASCI sites and customer offices happen at the slowest speeds and still produce the most ankle, knee, and back injuries on the admin side. The pattern: an admin or PM is walking from a vehicle to the office door, looking at their phone for the meeting confirmation. A backing pickup driver, also distracted, never sees them. The contact is at 3–5 mph. The pedestrian doesn't go down hard but twists out of the way — knee, ankle, back. Other variant: stepping out of a cab into a parked vehicle next to yours. Door-edge meets the next door, owner is upset, claim filed. Slow speeds, big outcomes.",
    hazards_reviewed: "Backing vehicle struck-by · Slip on wet / icy parking lot · Step off curb into vehicle path · Door-strike to adjacent vehicle · Tripping on parking blocks · Visibility issues in winter / low-light",
    discussion_notes: "• Phone DOWN while walking. Eyes on the lot, on backup lights, on movement. The text waits.\n• Walk in marked crosswalks where they exist. Where they don't, pick the safest path and stick to it.\n• When backing — back BEFORE the kids and pedestrians come out. Or pull through if available. Or back camera, mirror sweep, AND quick over-the-shoulder. Cameras alone are not enough.\n• Step out of your vehicle into a CLEAR space — don't open the door blind into the next lane.\n• Winter / wet — boots with grip on the soles, not dress shoes. A slip in the parking lot still happens at MASCI age.\n• Park in lit spaces at night. Visibility of YOUR vehicle matters as much as visibility from YOUR vehicle.\n• Watch for office staff and visitors at customer sites — they're not used to construction-vehicle scale. Slow down extra in customer parking.",
    references_cited: "OSHA General Duty · NHTSA Pedestrian Safety · MASCI Fleet Policy",
    action_items: "Phone-down-while-walking habit discussed · Backing-camera-plus-mirror rule reviewed · Winter footwear discussion · Customer-lot extra-caution reinforced",
  },
  {
    key: "office_heat_stress_visits",
    domain: "office",
    title: "Heat Stress on Summer Site Visits",
    category: "Hazard-Specific",
    role_context: ["office","manager","estimator","visitor"],
    incident_pattern: "Heat injuries to office staff during site visits in summer follow a specific pattern. The visitor arrives in business-casual clothes, doesn't have water, walks the site for 30–45 minutes in 95°F+ heat, and only realizes they're in trouble when they're already symptomatic — headache, lightheadedness, nausea. They drove themselves to the site, and now they have to drive themselves home while heat-symptomatic, which is its own crash risk. Office staff have lower heat tolerance than the field crew because they're not heat-acclimatized. A 20-minute walk for a field hand is a serious health risk for someone who sat in AC all morning.",
    hazards_reviewed: "Heat exhaustion progressing to heat stroke · Crash from driving while heat-symptomatic · Dehydration · Sunburn / eye damage from prolonged exposure · Underestimating heat without acclimation",
    discussion_notes: "• Water bottle in the vehicle, every site visit, May through October. Drink before, during, and after the visit.\n• Schedule summer site visits in the morning or late afternoon. Avoid 11 a.m. to 3 p.m. heat peak.\n• Hat that shades the face and neck. Sunscreen. Long sleeves are actually cooler than bare skin in direct sun.\n• Take breaks in the break trailer or in your vehicle with AC. Don't 'tough it out.'\n• Watch for symptoms in yourself and others: headache, nausea, irritability, dizziness, sudden quietness. Heat exhaustion progresses to heat stroke FAST.\n• If symptoms appear: get into shade or AC, drink water with electrolytes, cool the body. If symptoms don't resolve in 15 minutes — ER.\n• Driving while heat-symptomatic is impaired driving. Get someone to drive you. Call dispatch. Wait it out at the break trailer.\n• New hires and visitors are NOT acclimatized. Treat them more conservatively than the field crew.",
    references_cited: "OSHA Heat Stress · NIOSH Heat Stress · CDC Heat Illness · MASCI Heat Policy",
    action_items: "Water-in-vehicle habit reinforced · Morning-visit scheduling reviewed · Symptom-awareness discussed · Don't-drive-impaired rule reinforced",
  },
  {
    key: "office_lone_worker_checkin",
    domain: "office",
    title: "Lone Worker / Site Check-In Realities",
    category: "Procedure / SOP",
    role_context: ["office","manager","estimator","visitor"],
    incident_pattern: "Lone-worker incidents at MASCI typically involve a PM, an estimator, or a sales rep who drove to a remote jobsite, parked, walked the project alone, and either had a medical event (heart, stroke, fall) or got into a tense interaction with a customer or trespasser. No one knew exactly where they were. The phone hadn't moved for 45 minutes. By the time someone followed up, the situation had become serious. The fix is unglamorous: tell someone where you're going, set a check-in time, and follow through. We have not had a fatality from this — but we've had close calls that have changed how seriously we take check-ins.",
    hazards_reviewed: "Medical event with no one to respond · Slip / fall with no observer · Tense interaction with trespasser · Vehicle breakdown in low-signal area · Hostile customer / dispute escalation · Lost / disoriented in unfamiliar area",
    discussion_notes: "• Tell someone — dispatch, an admin, your manager — where you're going and when you expect to be back. Text works.\n• Set a check-in TIME, not just an intent. 'I'll text by 2:30.' If 2:30 passes with no text, that person calls you.\n• Phone charged before leaving the office. Bring a charger and a charged power bank for longer trips.\n• Don't enter a hostile situation alone. Customer dispute escalating? Pull back, call your manager, return with a partner.\n• Trespassers / unknown people on the site — don't engage alone. Call site security or local LE. You are not a security guard.\n• Vehicle breakdown in a remote area — stay with the vehicle if it's safe. Walking out can put you in worse trouble.\n• Medical history — if you have any condition that could leave you unresponsive, the check-in protocol is twice as important.\n• At the end of the visit, text the same person 'clear.' Closes the loop.",
    references_cited: "OSHA Lone Worker · ANSI/ASSP Z490 · MASCI Field Visit Policy",
    action_items: "Check-in time discipline reinforced · Phone-charging habit discussed · Hostile-interaction de-escalation policy reviewed · End-of-visit 'clear' text habit set",
  },
  {
    key: "office_severe_weather_accountability",
    domain: "office",
    title: "Severe Weather Accountability for Crews and Visitors",
    category: "Procedure / SOP",
    role_context: ["office","manager","dispatch","lead"],
    incident_pattern: "Severe-weather events catch office staff at the worst time — driving back from a site visit, midway through a customer meeting, or as the office is closing for the day. The pattern of failure is accountability: the office assumes all crews are pulled in, but two trucks are still out. The field assumes the office has called everyone, but three site visitors are still on site. When a tornado warning hits or a lightning storm rolls in, no one knows for sure who is where. The fix is one person — usually dispatch or admin — owning a check-the-roll process during weather events.",
    hazards_reviewed: "Worker / visitor caught in tornado / severe thunderstorm · Lightning strike on site · Flash flooding of low-lying jobsites · Hail damage to crew and equipment · Hypothermia / heat from extended exposure during storm",
    discussion_notes: "• One person is the weather POC during a severe-weather event. Usually dispatch or admin. They have the list. They make the calls.\n• Check the radar BEFORE leaving the office in summer thunderstorm season. Watch for fast-moving fronts.\n• Lightning rule: when you SEE lightning OR HEAR thunder, the field crew pulls in. 30/30 rule — 30 minutes after the last strike before resuming.\n• Tornado warning: into the safest available structure. Field crew into the office or substantial building, NOT into a vehicle, NOT into a trailer.\n• Severe rain / flash flood: avoid low-lying jobsites until conditions clear. Many heavy-civil sites are designed to flood — they're channels.\n• Hail: get vehicles under cover where possible. People away from windows.\n• Account for ALL personnel during a severe event. Office, field, drivers, visitors. The POC checks every name on the list.\n• Site visitors: notify them before they leave the office that weather is coming. Tell them to head straight back when conditions degrade.",
    references_cited: "NWS Severe Weather Awareness · OSHA Lightning Safety · MASCI Severe Weather SOP",
    action_items: "Weather POC designated · 30/30 lightning rule reviewed · Tornado-shelter mapping verified · Visitor weather-notify habit discussed",
  },
  {
    key: "office_slips_trips_falls",
    domain: "office",
    title: "Slips, Trips, and Falls in the Office Environment",
    category: "Hazard-Specific",
    role_context: ["office"],
    incident_pattern: "Office slip-and-fall incidents are unglamorous and very real. The pattern: spilled coffee in the kitchenette goes uncleaned for an hour, someone steps in it in dress shoes, and goes down. Or a power cord run across a doorway during a temporary setup, never picked up. Or a stairway with one bulb burned out, and someone misses the last step in the dim corner. None of these are dramatic — but they account for more lost-time office injuries than any other cause. Knees, ankles, hips, wrists. People work injured for weeks because they're embarrassed by a hallway fall.",
    hazards_reviewed: "Slip on spilled liquid · Trip over power cord / mat edge · Fall on stairs in low light · Slip on icy entryway · Fall from chair / step stool used as ladder · Slip in restroom",
    discussion_notes: "• Clean up spills immediately. Don't wait for someone else. The person who walks through it next might be you.\n• Wet-floor signs when something can't be cleaned right away. They actually work.\n• Power cords during temporary setups — taped down or routed around the path. No cords across walking surfaces.\n• Stairway lighting — report burned-out bulbs the same day. Office facilities replace them.\n• Winter entry mats — kept in place, replaced when worn out. The first 6 feet inside the door is where most winter slips happen.\n• Step stool, not chair, for reaching anything high. We have step stools. Use them.\n• Restroom floor cleanliness — report wet floors to facilities. The person who slipped in there last month was you.\n• Holding 4 things and walking? You're going to drop one or fall over one. Two trips is better than one fall.",
    references_cited: "OSHA 1910.22 · NSC slips/trips guidance · MASCI Office Safety Policy",
    action_items: "Spill-cleanup-now habit reinforced · Stair-lighting reporting reviewed · Cord-management for temp setups discussed · Step-stool-not-chair rule reinforced",
  },
  {
    key: "office_fatigue_mental_load",
    domain: "office",
    title: "Fatigue and Mental Load — When You're Tired, You're Impaired",
    category: "Hazard-Specific",
    role_context: ["office","manager","estimator","pm"],
    incident_pattern: "Mental fatigue is the office equivalent of heat stress in the field — slower to develop, easier to ignore, just as dangerous. The pattern: a PM works 11-hour days for two weeks during a busy season, sleeps badly, lives on coffee. Errors creep in — a job number transposed, a quote that's missing a line item, a critical email that doesn't get sent. The PM blames themselves for not being sharp. The real cause is sustained sleep debt and decision fatigue. Long-term, this pattern leads to depression, family stress, and physical illness. We have lost good people to burnout that started this exact way.",
    hazards_reviewed: "Decision errors from sleep deprivation · Crash from driving fatigued · Email / contract errors with downstream impact · Burnout / mental health decline · Family stress · Physical illness from sustained sleep debt",
    discussion_notes: "• Sleep is not optional. Seven hours minimum. Less than that for a week is impaired-driving-level cognitive impact.\n• Take your time off. Vacation accruing doesn't help anyone — used vacation does.\n• Decision fatigue is real. The decisions you make at 5 p.m. after 10 hours of meetings are not your best decisions. Batch important calls earlier in the day.\n• When you catch yourself making errors, don't push harder — stop. Walk. Hydrate. Eat. Come back.\n• Mental health is not weakness. Talk to someone. EAP is confidential and useful. Coworkers are useful. Family is useful.\n• Watch your coworkers. Withdrawn, irritable, error-prone — these are the early signs. Check in on each other.\n• Phone off after hours when you can. The job will be there tomorrow. Your mental reserves won't if you don't rebuild them.\n• 988 — Suicide & Crisis Lifeline (call or text). MASCI EAP for confidential help. Construction has one of the highest suicide rates of any industry. This matters.",
    references_cited: "CDC Fatigue · NIOSH Total Worker Health · 988 Suicide & Crisis Lifeline · MASCI EAP",
    action_items: "Sleep priority discussed · Vacation use policy reviewed · Decision-fatigue awareness raised · 988 / EAP info shared",
  },
];
