// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: plant · 8 ES translations

export const TOPICS_PLANT_ES = {
  plant_conveyor_entanglement: {
    title: "Enredamiento en Banda Transportadora — Poleas de Cola y Puntos de Pellizco",
    incident_pattern: "Las fatalidades por enredamiento en banda en plantas de agregado y asfalto siguen un patrón terriblemente predecible. Un peón se acerca a una polea de cola corriendo para limpiar acumulación de finos o un pedazo de metal extraño. Mete una pala, la pala agarra la banda, y es jalado al punto de pellizco entre banda y polea. La banda no para sola. Para cuando el operador pega al paro de emergencia desde la caseta, el trabajador ya se fue. CADA reporte de incidente de banda que hemos leído incluye la línea 'la guarda estaba quitada' o 'iba a agarrarlo nomás rapidito.'",
    hazards_reviewed: "Enredamiento en polea de cola / cabeza / take-up · Pellizco en rodillos idler · Ropa suelta atrapada por banda · Subirse a banda corriendo · Limpiar bajo banda corriendo · Aplastamiento por arranque/paro durante servicio",
    discussion_notes: "• NADIE cerca de una polea de cola o cabeza corriendo. Punto. La acumulación se limpia con la banda BLOQUEADA, no corriendo.\n• Guardas en todos los puntos de pellizco cuando la banda corre. Si una guarda está fuera por servicio, la banda está BLOQUEADA.\n• Metal extraño removido con la banda apagada, no 'lo agarro antes de la siguiente descarga.' Los imanes y detectores están para prevenir esa situación.\n• Sin meter mano a banda corriendo con pala, escoba, barra, mano. Sin excepciones.\n• Cuerdas de paro de emergencia a lo largo de toda la longitud, probadas semanalmente. Los operadores deben saber exactamente dónde está la cuerda más cercana.\n• Caminar bajo una banda — casco puesto, vigilar caída de material, nunca pararse bajo una banda que está siendo limpiada río arriba.\n• Subirse a una banda — solo con banda bloqueada y etiquetada. Nunca en banda corriendo.\n• Trabajadores nuevos de planta: caminen el sistema de bandas el Día 1 con el líder. Apunten a cada punto de pellizco. Muestren cada paro de emergencia.",
    references_cited: "OSHA 29 CFR 1910.147 · MSHA 30 CFR Parte 56 · Seguridad de bandas NSSGA · SOP de Planta MASCI",
    action_items: "Regla de no-tocar-banda-corriendo reforzada · Inspección de guardas asignada · Función de cuerdas de paro probada · Recorrido de bandas para trabajador nuevo programado",
  },
  plant_baghouse_silo_hazards: {
    title: "Limpieza de Baghouse y Riesgos de Entrada a Silos",
    incident_pattern: "Las fatalidades en silos y baghouse casi siempre involucran a alguien entrando sin permiso de espacio confinado. El patrón: un baghouse se está tapando, la producción cae, y alguien se sube al gabinete para romper el puente de material. No le dicen a nadie exactamente dónde están. El puente cede, el material cae en avalancha, y quedan engullidos. Los silos de asfalto añaden vapores de bitumen caliente y el riesgo de caer en material caliente. Los silos de agregado añaden polvo fino a densidades de asfixia. Ambos han matado trabajadores de planta en los últimos 5 años en esta industria. El arreglo es el mismo que siempre ha sido: permiso de espacio confinado, prueba atmosférica, asistente, línea de recuperación.",
    hazards_reviewed: "Engullimiento en material fluyente · Asfixia por bajo O2 en atmósfera de silo · Quemadura por contacto con bitumen caliente · Colapso de puente sobre trabajadores · Aplastamiento por equipo de limpieza rotatorio · Caídas desde plataformas de baghouse",
    discussion_notes: "• Permiso de entrada a espacio confinado ANTES de que alguien entre a silo, baghouse o tanque de almacenamiento. Sin 'nomás voy a meterme rápido.'\n• Prueba atmosférica — O2, LEL, CO, H2S mínimo. Monitoreo continuo mientras esté ocupado. Silos de asfalto: también probar VOCs.\n• Asistente afuera todo el tiempo. NO entran a rescatar. Llaman al rescate. Mantienen comunicación.\n• Línea de recuperación y arnés completo para el entrante. Silos de asfalto añaden PPE resistente al calor.\n• Aislamiento de material ANTES de entrada. Lockout de alimentación. Lockout de descarga. Verifique que el puente esté roto desde AFUERA si es posible.\n• Romper puente desde afuera siempre que sea posible — barras largas, lanzas de aire, vibradores. Entrar debe ser la última opción, no la primera.\n• Plataformas de acceso de baghouse — barandales completos, protección contra caídas arriba de 6 ft, nunca confíe en una plataforma con rejilla corroída.\n• Emergencias en silo de asfalto: el trabajador está del lado caliente. Sáquenlo RÁPIDO. Tengan plan de rescate escrito y ensayado.",
    references_cited: "OSHA 29 CFR 1926 Subparte AA · OSHA 1910.146 · NIOSH entrada a silos · SOP de Espacio Confinado MASCI",
    action_items: "Política de permiso de espacio confinado reforzada · Monitor atmosférico calibrado · Herramientas para romper desde afuera disponibles · Plan de rescate revisado",
  },
  plant_asphalt_burns_oil_exposure: {
    title: "Quemaduras de Asfalto Caliente y Exposición a Vapor de Bitumen",
    incident_pattern: "Las quemaduras de asfalto no son como quemaduras normales. El material está a 300–350°F cuando toca la piel y SE PEGA — no escurre como agua caliente. El trabajador no puede quitárselo a tiempo para prevenir quemaduras de tercer grado. El escenario más común es un muestreador en el load-out, un chofer subiéndose al camión, o un técnico de lab en la caldera. Un salpicón, un contacto con una línea caliente, una liberación súbita de material atrapado — y lo que habría sido un susto ahora es un viaje al hospital con injertos de piel. Los vapores de bitumen en la planta complican el asunto con irritación respiratoria y preocupaciones de exposición a largo plazo.",
    hazards_reviewed: "Quemadura de tercer grado por contacto con asfalto caliente · Quemadura por liberación de vapor en load-out · Inhalación de vapor (exposición PAH) · Quemadura ocular por salpicón · Resbalón en binder derramado y frío · Quemadura a través de ropa",
    discussion_notes: "• Mangas largas, pantalones largos, guantes con puños. Botas calificadas para asfalto — cuero, no sintéticas. Las botas sintéticas se derriten DENTRO del pie.\n• Careta sobre lentes de seguridad para cualquier trabajo de load-out, muestreo o caldera. Los salpicones van a la cara.\n• Párese A FAVOR DEL VIENTO del tubo al cargar. Choferes: quédense en la cabina durante el load-out donde se permita. Si debe estar afuera, protección ocular.\n• Nunca use agua para lavar asfalto caliente de la piel. Enfríe con compresas frías si es posible, luego al ER. El agua puede meter el calor más profundo.\n• Muestreo: muestreadores de mango largo. Nunca alcance dentro de una caldera o chute de load-out con herramienta corta. La distancia de salpicón es real.\n• Vapores de bitumen — trabaje a favor del viento, tome descansos, reporte síntomas (dolor de cabeza, ardor de ojos, irritación de garganta). El monitoreo a largo plazo importa.\n• Lavaojos y ducha de emergencia dentro de 25 pies de operaciones de asfalto. Probadas mensualmente.\n• Si un trabajador se quema: cubra la quemadura con paño limpio y seco (NO trate de quitar el asfalto de la piel). Al ER inmediatamente.",
    references_cited: "OSHA 29 CFR 1910.132 · TLV ACGIH para bitumen · Guía NIOSH para humos de asfalto · SOP de Quemadura en Planta MASCI",
    action_items: "PPE para trabajo en planta verificado · Uso de muestreador de mango largo discutido · Lavaojos / ducha probados · Procedimiento de respuesta a quemadura revisado",
  },
  plant_burner_systems: {
    title: "Sistemas de Quemador — Riesgos de Encendido y Apagado de Flama",
    incident_pattern: "Los incidentes relacionados con el quemador en plantas de hot-mix siguen dos patrones. El primero es explosión de encendido: el quemador cicla por ignición, no enciende, pero el combustible sigue alimentándose. El combustible sin quemar se acumula en el tambor. Cuando la ignición finalmente prende, el combustible acumulado explota — volando el extremo del tambor, lanzando flama a través del patio de planta, y lesionando a cualquiera cerca. El segundo es apagón durante operación: la flama se va, el combustible continúa, y el siguiente encendido se comporta igual. Ambos son causados por ciclos de purga saltados, fuentes de ignición débiles, u operación fuera del sobre de control. Los sistemas modernos de flame-safeguard previenen esto — SI están mantenidos y no son bypaseados.",
    hazards_reviewed: "Explosión de encendido en tambor · Flashback a línea de combustible · Quemadura por blowout de extremo del tambor · Daño auditivo por explosión · Acumulación de CO en área de operación de planta · Ignición de fuga de combustible",
    discussion_notes: "• Ciclo de purga CADA encendido. No 'cuando me acuerde.' CADA vez. La purga limpia cualquier combustible sin quemar de intentos previos.\n• No bypasee el sistema de flame-safeguard. Si está disparándose repetidamente, ARREGLE la causa — no lo brinquee.\n• Secuencia de encendido: purga → ignición piloto → ignición de quemador principal → flama detectada → fuego completo. Cada paso verificado antes del siguiente.\n• Si la flama se va durante operación: corte combustible INMEDIATAMENTE, complete un ciclo de purga, luego re-encienda. No solo siga alimentando.\n• Área del quemador libre de personal durante encendido. Fije la regla, hágala cumplir. Si algo falla, no quiere a nadie en línea de fuego.\n• Inspección diaria de líneas de combustible, válvulas, piloto, escaneador de flama. Las fugas en el quemador son catastróficas si se acumulan y encuentran ignición.\n• Monitoreo de CO en el área del patio de planta. Inversiones y condiciones de viento apretadas atrapan el escape. Los trabajadores necesitan saber si se está acumulando.\n• Si huele a combustible sin quemar cerca del quemador — PARE. Apague. Investigue antes de re-encender.",
    references_cited: "NFPA 86 · OSHA 29 CFR 1910.106 · Manuales OEM del quemador · SOP del Quemador de Planta MASCI",
    action_items: "Protocolo de ciclo de purga reforzado · Política de manipular flame-safeguard discutida · Inspección diaria de línea de combustible asignada · Monitor de CO verificado",
  },
  plant_loader_blind_spots_haul_road: {
    title: "Puntos Ciegos de Cargador y Interacciones en el Haul Road",
    incident_pattern: "Los incidentes en el patio de planta y haul road casi siempre involucran un cargador y un camión de acarreo o una pickup. El operador de cargador tiene buena visibilidad en la dirección que apunta el cucharón — y mala visibilidad ATRÁS y a la derecha. Un chofer entra a posición, un foreman camina el patio a inspeccionar material, o un vendedor sale de la oficina. El cargador retrocede para reposicionarse a la siguiente descarga, y el espacio entre el cucharón y el camión se cierra. El patrón es tráfico constante, movimiento constante, y un operador de cargador que no puede ver a todos todo el tiempo. La supervisión del patio y la disciplina de tráfico son lo que previene esto.",
    hazards_reviewed: "Golpe-por de cargador retrocediendo · Chofer de pickup en punto ciego del cargador · Aplastado entre cargador y pila · Vendedor / visitante en área activa de patio · Avalancha de material durante operación del cargador",
    discussion_notes: "• Operadores de cargador: alarma de reversa funcional, CADA turno. Si está rota, el cargador no corre.\n• Carril de entrada/salida para camiones de acarreo — definido y señalizado. Los choferes se quedan en cabina durante carga siempre que sea posible.\n• Visitantes / ventas / gerencia en el patio: chaleco hi-vis + casco, escoltados, nunca en la trayectoria activa del cargador. Si no está cargando, está en otro lado.\n• El operador NO carga si alguien está en la zona de retroceso. Pause, indíqueles que despejen, luego opere.\n• El haul road tiene límite de velocidad publicado y patrón de un solo sentido. Háganlo cumplir. Tráfico lado-a-lado en un haul road es un choque frontal esperando suceder.\n• Vigile la cara de la pila. Un cargador socavando una cara crea un voladizo que puede colapsar sin aviso. Mantenga las caras al ángulo de reposo.\n• Foremen en el patio: párese donde pueda ver los ojos del operador a través del vidrio de cabina. Si no puede, el operador no lo puede ver a usted tampoco.\n• Operaciones nocturnas de planta: operador con luz de cabina apagada, choferes con faros apuntando lejos del operador. El brillo ciega al cargador hacia trabajadores en tierra.",
    references_cited: "OSHA 29 CFR 1926.602 · MSHA 30 CFR Parte 56 · Seguridad de Planta NSSGA · SOP de Tráfico de Patio MASCI",
    action_items: "Verificación de alarma de reversa por turno verificada · Política de escolta de visitantes revisada · Pendiente de cara de pila inspeccionada · Procedimiento de brillo nocturno discutido",
  },
  plant_crusher_clearing_jams: {
    title: "Atascos de Triturador — Cómo Liberar Trituradores Bloqueados con Seguridad",
    incident_pattern: "Los incidentes al liberar trituradores son algunas de las peores lesiones en la industria del agregado. Un pedazo de metal extraño o alimentación de tamaño excesivo atasca el triturador. El operador se sube a la banda de alimentación o entra a la boca del triturador con una barra para liberar el material. El triturador sigue energizado, el operador está en un espacio apretado con energía hidráulica / mecánica almacenada, y o el atasco se libera violentamente (lanzando el material y al trabajador) o alguien golpea un control y el triturador arranca. Se pierden extremidades. Los trabajadores mueren. El patrón es el mismo que la gente de taller ve con LOTO — pero peor, porque los trituradores tienen energía almacenada enorme.",
    hazards_reviewed: "Arranque de triturador mientras está ocupado · Proyectil por liberación súbita de atasco · Aplastamiento en la garganta de alimentación · Caídas de banda de alimentación · Liberación de energía hidráulica / de resorte almacenada · Proyectil de metal extraño",
    discussion_notes: "• LOTO el triturador antes de CUALQUIER trabajo de liberación. Desconexión del motor principal. Aislamiento hidráulico. Candado personal por cada trabajador involucrado.\n• Verifique energía cero. Try-start en el control. Baje presión hidráulica. Bloquee cualquier componente móvil mecánicamente.\n• Nunca libere un atasco con la mano desde la garganta de alimentación. Use herramientas de mango largo desde AFUERA de la zona de trituración.\n• Si debe entrar — trato de espacio confinado. Asistente. Recuperación. Comunicación.\n• Manejo de metal extraño — imán, detector de metal, scalper. PREVENGA el atasco antes de que pase.\n• Material sobre-tamaño — sacado en el scalper, no permitido llegar a la boca del triturador.\n• Al liberar un atasco, párese fuera-de-eje de la garganta. El material liberado puede salir disparado rápido.\n• Operadores de triturador: capaciten a los nuevos en procedimiento de liberación con el triturador bloqueado, caminando cada paso ANTES de que encuentren un atasco real.",
    references_cited: "OSHA 29 CFR 1910.147 · MSHA 30 CFR Parte 56 · Seguridad de Triturador NSSGA · Manual OEM del triturador",
    action_items: "Procedimiento LOTO de triturador revisado · Herramientas de mango largo disponibles · Manejo de metal extraño discutido · Capacitación de liberación para nuevo asignada",
  },
  plant_lab_solvents_ignition: {
    title: "Lab de Asfalto — Solventes, Hornos y Riesgo de Ignición",
    incident_pattern: "Los incendios en lab de asfalto usualmente involucran solventes y hornos. Un técnico corre una extracción usando tricloroetileno o percloroetileno, ventila a la campana, pone el rotovap, y se va. Un reflujo al horno, un punto caliente en el elemento, un motor que arquea — y el vapor de solvente encuentra ignición. El fuego es rápido y el humo es tóxico. Los técnicos de lab trabajando solos están en el mayor riesgo porque nadie ve los avisos tempranos. El otro patrón es el aparato de punto de ignición durante prueba de pérdida por ignición — flama abierta, sólidos calientes, cerca de combustibles. Estos labs son más apretados de lo que la gente piensa.",
    hazards_reviewed: "Ignición de vapor de solvente · Quemadura por aparato calentado · Inhalación de TCE / perc / humos · Rotura de vidrio con aceite caliente · Salpicón ocular de binder extraído · Resbalón en derrame de solvente",
    discussion_notes: "• Campana de ventilación operativa y probada. CADA corrida de extracción usa la campana. Si la campana está abajo, la prueba espera.\n• Contenedores de solvente etiquetados, tapados, almacenados en gabinete inflamable entre usos.\n• Trabajo caliente — hornos, aparato de punto de ignición, calderas — mantenido físicamente separado del trabajo de solvente. Disciplina de lado caliente / lado frío.\n• PPE: guantes de nitrilo, protección ocular, bata de lab. Sin cabello suelto, sin bufandas, sin batas con cordones o lazos.\n• Lavaojos y ducha de emergencia dentro de 10 segundos de cualquier aparato. Probados semanalmente.\n• Contenedores de desecho de solvente metálicos, tapados, conectados a tierra. No vidrio, no jarras abiertas en repisa.\n• Sin comer, beber o guardar comida en el lab. El bitumen y los solventes se transfieren a las manos y a las bocas.\n• Técnico de lab trabajando solo fuera de horas — protocolo de llamada. Alguien sabe que está adentro. Revisan si no envía mensaje de salida.",
    references_cited: "OSHA 29 CFR 1910.1450 (Estándar de Lab) · NFPA 45 · TLVs ACGIH · SOP de Lab MASCI",
    action_items: "Prueba de función de campana verificada · Auditoría de almacenamiento de solventes hecha · Layout lado-caliente / lado-frío discutido · Protocolo de check-in fuera de horas fijado",
  },
  plant_silo_burn_avalanche: {
    title: "Drag Slat de Silo de Asfalto y Avalancha de Material",
    incident_pattern: "El load-out de silo de asfalto es una interfaz peligrosa — material caliente a 300°F+ sentado en un silo, liberado por una compuerta, cayendo 8–15 pies a la caja de un camión abajo. El patrón de lesiones es doble: los choferes bajo el silo durante una caída se queman por salpicón o derrame, y los drag-slat sobre el silo pueden lanzar material si una acumulación se libera inesperadamente. El incidente clásico es un chofer subiendo a la plataforma del silo para revisar el nivel de carga, asomándose, y siendo golpeado por una liberación súbita de material cuando la compuerta abre. O un trabajador de mantenimiento en la plataforma del drag-slat cuando un atasco río arriba se libera.",
    hazards_reviewed: "Quemadura por liberación súbita de material en compuerta · Caída desde plataforma de silo · Aplastamiento por cadena de drag-slat · Quemadura por fuga de aceite de drag-slat · Inhalación de vapor tóxico en parte alta del silo · Chofer atorado bajo silo caliente",
    discussion_notes: "• Chofer bajo el silo: en la cabina durante carga. Siempre. Suba solo después de que la compuerta cerró y el chute drenó.\n• Acceso a parte alta del silo: arnés y atado arriba de 6 ft. Aun en plataforma con barandal, protección contra caídas durante cualquier tarea que involucre asomarse.\n• Los drag-slat son LOTO siempre que un trabajador esté en la plataforma para servicio o inspección. Pasar caminando para revisión visual desde distancia segura es una cosa — trabajo de servicio necesita LOTO completo.\n• Comunicación entre operador de load-out y chofer — radio o señal de claxon. El chofer sabe cuándo la compuerta está por abrir.\n• Fallas de compuerta de silo — si una compuerta no sella, ponga el silo FUERA DE SERVICIO para reparar. No trabaje alrededor de una compuerta con falla.\n• Vapores en parte alta del silo — los vapores de bitumen se acumulan en el espacio superior. No abra la escotilla de inspección en viento calmo sin ventilación. Tome descanso a favor del viento después de exposición.\n• Caja del camión bajo el silo: confirmación visual antes de abrir la compuerta. Caja vacía, posicionada apropiadamente. El foreman da el OK.",
    references_cited: "OSHA 29 CFR 1926.501 · MSHA Seguridad de Silos · Manuales OEM de silo / drag-slat · SOP de Load-out MASCI",
    action_items: "Regla de chofer-en-cabina-en-load-out reforzada · Protección contra caídas en parte alta verificada · Procedimiento LOTO de drag-slat revisado · Regla OOS por falla de compuerta discutida",
  },
};
