// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: plant · 8 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_PLANT = [
  {
    key: "plant_conveyor_entanglement",
    domain: "plant",
    title: "Conveyor Belt Entanglement — Tail Pulleys and Pinch Points",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    role_context: ["plant_operator","groundman","lead"],
    incident_pattern: "Conveyor entanglement fatalities at aggregate and asphalt plants follow a sickeningly predictable pattern. A laborer goes near a running tail pulley to clear a buildup of fines or a piece of tramp metal. They reach in with a shovel, the shovel catches the belt, and they're pulled into the pinch point between belt and pulley. The conveyor doesn't stop on its own. By the time the operator hits the e-stop from the control house, the worker is already gone. EVERY conveyor incident report we've ever read includes the line 'guard was off' or 'I was just going to grab it real quick.'",
    hazards_reviewed: "Entanglement at tail / head / take-up pulley · Pinch at idler rollers · Loose clothing catching belt · Climbing on running belt · Cleaning under running belt · Crush from belt stops/starts during service",
    discussion_notes: "• NO ONE near a running tail pulley or head pulley. Period. Build-up is cleared with the belt LOCKED OUT, not running.\n• Guards on all pinch points whenever the conveyor runs. If a guard is off for service, the conveyor is LOCKED OUT.\n• Tramp metal cleared with the belt off, not 'I'll grab it before the next dump.' Magnets and metal detectors are there to prevent that very situation.\n• No reaching into a running belt with a shovel, broom, bar, hand. No exceptions.\n• Pull-cord e-stops along the full length, tested weekly. Operators should know exactly where the closest cord is.\n• Walking under a belt — wear hard hat, watch for material drop, never stand under a belt that's being cleaned upstream.\n• Climbing on a belt — only with belt locked out and tagged. Never on a running belt.\n• New plant workers: walk the conveyor system on Day 1 with the lead. Point at every pinch point. Show every e-stop.",
    references_cited: "OSHA 29 CFR 1910.147 · MSHA 30 CFR Part 56 · NSSGA conveyor safety · MASCI Plant SOP",
    action_items: "No-touch-running-belt rule reinforced · Guard inspection assigned · Pull-cord function tested · New-worker conveyor walkthrough scheduled",
  },
  {
    key: "plant_baghouse_silo_hazards",
    domain: "plant",
    title: "Baghouse Cleanout and Silo Entry Hazards",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    role_context: ["plant_operator","lead","mechanic"],
    incident_pattern: "Silo and baghouse fatalities almost always involve someone going inside without a confined-space permit. The pattern: a baghouse is plugging up, production is dropping, and someone climbs into the housing to break the bridge of material. They don't tell anyone exactly where they are. The bridge fails, material avalanches down, and they're engulfed. Asphalt silos add hot bitumen vapors and the risk of falling into hot material. Aggregate silos add fine dust at suffocation densities. Both have killed plant workers in the last 5 years across this industry. The fix is the same fix it's always been: confined-space permit, atmospheric testing, attendant, retrieval line.",
    hazards_reviewed: "Engulfment in flowing material · Asphyxiation from low O2 in silo atmosphere · Burn from hot bitumen contact · Bridge collapse on workers · Crush from rotating clean-out equipment · Falls from baghouse access platforms",
    discussion_notes: "• Confined-space entry permit BEFORE anyone enters a silo, baghouse, or storage vessel. No 'just gonna pop in real quick.'\n• Atmospheric testing — O2, LEL, CO, H2S minimum. Continuous monitoring while occupied. Asphalt silos: also test for VOCs.\n• Attendant outside at all times. They DO NOT enter to rescue. They call rescue. They maintain communication.\n• Retrieval line and full-body harness for the entrant. Asphalt silos add heat-resistant PPE.\n• Material isolation BEFORE entry. Lockout the silo feed. Lockout the discharge. Verify the bridge is broken from OUTSIDE if possible.\n• Bridge-breaking from outside whenever possible — long bars, air lances, vibrators. Going inside should be the last option, not the first.\n• Baghouse access platforms — full guardrails, fall protection above 6 ft, never trust a platform with corroded grating.\n• Asphalt silo emergencies: the worker is on the hot side. Get them out FAST. Have rescue plan written and rehearsed.",
    references_cited: "OSHA 29 CFR 1926 Subpart AA · OSHA 1910.146 · NIOSH silo entry · MASCI Confined Space SOP",
    action_items: "Confined-space permit policy reinforced · Atmospheric monitor calibrated · Bridge-from-outside tools available · Rescue plan reviewed",
  },
  {
    key: "plant_asphalt_burns_oil_exposure",
    domain: "plant",
    title: "Hot Asphalt Burns and Bitumen Vapor Exposure",
    severity: "serious_injury",
    category: "Hazard-Specific",
    role_context: ["plant_operator","driver","lab_tech","lead"],
    incident_pattern: "Asphalt burns are not like normal burns. The material is 300–350°F when it hits skin and it STICKS — it doesn't run off like hot water. The worker cannot get it off in time to prevent third-degree burns. The most common scenario is a sampler at the load-out, a driver climbing on the truck, or a lab tech at the kettle. A splash, a contact with a hot line, a sudden release of trapped material — and what would have been a flinch is now a hospital trip with skin grafts. Bitumen vapors at the plant compound the issue with respiratory irritation and long-term exposure concerns.",
    hazards_reviewed: "Third-degree burn from hot asphalt contact · Burn from steam release at load-out · Vapor inhalation (PAH exposure) · Eye burn from splash · Slip on cooled spilled binder · Burn through clothing",
    discussion_notes: "• Long sleeves, long pants, gloves with cuffs. Asphalt-rated boots — leather, not synthetic. Synthetic boots melt INTO the foot.\n• Face shield over safety glasses for any load-out work, sampling, or kettle work. Splashes go for the face.\n• Stand UPWIND of the spout when loading. Drivers: stay in the cab during load-out where allowed. If you must be out, eye protection.\n• Never use water to wash hot asphalt off skin. Cool with cold compresses if possible, then to the ER. Water can drive the heat in deeper.\n• Sampling: long-handled samplers. Never reach into a kettle or load-out chute with a short tool. The splash distance is real.\n• Bitumen vapors — work upwind, take breaks, report symptoms (headache, eye burning, throat irritation). Long-term monitoring matters.\n• Eye-wash and emergency shower within 25 feet of asphalt operations. Tested monthly.\n• If a worker is burned: cover the burn with a clean dry cloth (do NOT try to remove asphalt from skin). To ER immediately.",
    references_cited: "OSHA 29 CFR 1910.132 · ACGIH TLV for bitumen · NIOSH asphalt fume guidance · MASCI Plant Burn SOP",
    action_items: "PPE for plant work verified · Long-handle sampler usage discussed · Eye wash / shower tested · Burn response procedure reviewed",
  },
  {
    key: "plant_burner_systems",
    domain: "plant",
    title: "Burner Systems — Light-Off and Flameout Hazards",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    role_context: ["plant_operator","lead"],
    incident_pattern: "Burner-related incidents at hot-mix plants follow two patterns. The first is light-off explosion: the burner cycles through ignition, fails to light, but fuel keeps feeding. The unburned fuel pools in the drum. When ignition finally catches, the accumulated fuel explodes — blowing the drum end out, throwing flame across the plant pad, and injuring anyone nearby. The second is flameout during operation: the flame goes out, fuel continues, and the next light-off behaves the same. Both are caused by skipped purge cycles, weak ignition sources, or operating outside the control envelope. Modern flame-safeguard systems prevent this — IF they're maintained and not bypassed.",
    hazards_reviewed: "Light-off explosion in drum · Flashback to fuel line · Burn from drum-end blowout · Hearing damage from explosion · CO buildup in plant operating area · Fuel leak ignition",
    discussion_notes: "• Purge cycle EVERY light-off. Not 'when I think about it.' EVERY time. The purge clears any unburned fuel from prior attempts.\n• Don't bypass the flame-safeguard system. If it's tripping repeatedly, FIX the cause — don't jumper around it.\n• Light-off sequence: purge → pilot ignition → main burner ignition → flame detected → full fire. Each step verified before next.\n• If the flame goes out during operation: shut fuel off IMMEDIATELY, complete a purge cycle, then re-light. Do not just keep feeding.\n• Burner area clear of personnel during light-off. Set the rule, enforce it. If something fails, you don't want anyone in the line of fire.\n• Daily inspection of fuel lines, valves, pilot, flame scanner. Leaks at the burner are catastrophic if they pool and find ignition.\n• CO monitoring in the plant pad area. Inversions and tight wind conditions trap exhaust. Workers need to know if it's accumulating.\n• If you smell unburned fuel near the burner — STOP. Shut down. Investigate before relighting.",
    references_cited: "NFPA 86 · OSHA 29 CFR 1910.106 · OEM burner manuals · MASCI Plant Burner SOP",
    action_items: "Purge cycle protocol reinforced · Flame-safeguard tampering policy discussed · Daily fuel-line inspection assigned · CO monitor verified",
  },
  {
    key: "plant_loader_blind_spots_haul_road",
    domain: "plant",
    title: "Loader Blind Spots and Haul-Road Interactions",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    role_context: ["loader_operator","driver","lead"],
    incident_pattern: "Plant pad and haul-road incidents almost always involve a loader and a haul truck or a pickup. The loader operator has good visibility in the direction the bucket is facing — and poor visibility BEHIND and to the right. A truck driver pulls into position, a foreman walks the pad to inspect material, or a sales rep wanders out from the office. The loader backs up to reposition for the next dump, and the gap between the bucket and the truck closes. The pattern is constant traffic, constant motion, and a loader operator who can't see everyone all the time. Pad supervision and traffic discipline are what prevent these.",
    hazards_reviewed: "Struck-by from backing loader · Pickup driver in loader blind spot · Crushed between loader and stockpile · Sales / visitor in active pad area · Material avalanche during loader operation",
    discussion_notes: "• Loader operators: backup-alarm functional, EVERY shift. If it's broken, the loader doesn't run.\n• Pull-up/pull-out lane for haul trucks — defined and signed. Drivers stay in cab during load whenever possible.\n• Visitors / sales / management on the pad: hi-vis vest + hard hat, escorted, never in active loader path. If you're not loading, you're somewhere else.\n• Loader operator does NOT load if anyone is in the backing zone. Pause, signal them clear, then operate.\n• Haul road has a posted speed limit and a one-way pattern. Enforce it. Side-by-side traffic on a haul road is a head-on waiting to happen.\n• Watch the stockpile face. A loader undercutting a face creates an overhang that can collapse without warning. Keep faces sloped to the angle of repose.\n• Foremen on the pad: stand where you can see the loader's eyes through the cab glass. If you can't, the operator can't see you either.\n• Night plant operations: loader operator with cab-light off, drivers with headlights aimed away from the operator. Glare blinds the loader to ground workers.",
    references_cited: "OSHA 29 CFR 1926.602 · MSHA 30 CFR Part 56 · NSSGA Plant Safety · MASCI Pad Traffic SOP",
    action_items: "Backup-alarm shift-check verified · Visitor escort policy reviewed · Stockpile face slope inspected · Night-glare procedure discussed",
  },
  {
    key: "plant_crusher_clearing_jams",
    domain: "plant",
    title: "Crusher Jams — Clearing Blocked Crushers Safely",
    severity: "fatal_risk",
    category: "Hazard-Specific",
    role_context: ["crusher_operator","lead","mechanic"],
    incident_pattern: "Crusher clearing incidents are some of the worst injuries in the aggregate industry. A piece of tramp metal or oversize feed jams the crusher. The operator climbs onto the feed conveyor or into the crusher mouth with a pry bar to free the material. The crusher is still energized, the operator is in a tight space with stored hydraulic / mechanical energy, and either the jam releases violently (throwing the material and the worker) or someone bumps a control and the crusher starts. Limbs are lost. Workers are killed. The pattern is the same one shop people see with LOTO — but worse, because crushers have enormous stored energy.",
    hazards_reviewed: "Crusher start-up while occupied · Sudden jam release projectile · Crush in feed throat · Falls from feed conveyor · Stored hydraulic / spring energy release · Tramp metal projectile",
    discussion_notes: "• LOTO the crusher before ANY jam-clearing work. Main motor disconnect. Hydraulic isolation. Personal lock for every worker involved.\n• Verify zero energy. Try-start at the control. Drop hydraulic pressure. Block any movable component mechanically.\n• Never clear a jam by hand from the feed throat. Use long-handled tools from OUTSIDE the crushing zone.\n• If you must enter — confined-space treatment. Attendant. Retrieval. Communication.\n• Tramp metal management — magnet, metal detector, scalper. PREVENT the jam before it happens.\n• Oversized material — kicked off at the scalper, not allowed to reach the crusher mouth.\n• When releasing a jam, stand off-axis from the throat. Released material can shoot back fast.\n• Crusher operators: train new hands on jam-clearing procedure with the crusher locked out, walking through every step BEFORE they encounter a real jam.",
    references_cited: "OSHA 29 CFR 1910.147 · MSHA 30 CFR Part 56 · NSSGA Crusher Safety · OEM crusher manual",
    action_items: "Crusher LOTO procedure reviewed · Long-handle tools available · Tramp metal management discussed · New-hand jam-clearing training scheduled",
  },
  {
    key: "plant_lab_solvents_ignition",
    domain: "plant",
    title: "Asphalt Lab — Solvents, Ovens, and Ignition Risk",
    severity: "serious_injury",
    category: "Hazard-Specific",
    role_context: ["lab_tech","lead"],
    incident_pattern: "Asphalt-lab fires usually involve solvents and ovens. A tech runs an extraction using trichloroethylene or perchloroethylene, vents to the hood, sets the rotovap, and walks away. A backflow into the oven, a hot spot in the heating element, an arcing motor — and the solvent vapor finds ignition. The fire is fast and the smoke is toxic. Lab techs working alone are at the highest risk because no one sees the early warning signs. The other pattern is the ignition-point apparatus during AC ignition-loss testing — open flame, hot solids, near combustibles. These labs are tighter than people think.",
    hazards_reviewed: "Solvent vapor ignition · Burn from heated apparatus · Inhalation of TCE / perc / fumes · Glass breakage with hot oil · Eye splash from extracted binder · Slip on solvent spill",
    discussion_notes: "• Ventilation hood operational and tested. EVERY extraction run uses the hood. If the hood is down, the test waits.\n• Solvent containers labeled, capped, stored in a flammable cabinet between uses.\n• Hot work — ovens, ignition-point apparatus, kettles — kept physically separate from solvent work. Hot side / cold side discipline.\n• PPE: nitrile gloves, eye protection, lab coat. NO loose hair, NO scarves, NO lab coats with strings or ties.\n• Eye wash and emergency shower within 10 seconds of any apparatus. Tested weekly.\n• Solvent waste containers metal, capped, grounded. Not glass, not open jars on a shelf.\n• No eating, drinking, or storing food in the lab. Bitumen and solvents transfer to hands and into mouths.\n• Lab tech working alone after hours — call-in protocol. Someone knows you're in there. They check in if you don't text out.",
    references_cited: "OSHA 29 CFR 1910.1450 (Lab Standard) · NFPA 45 · ACGIH TLVs · MASCI Lab SOP",
    action_items: "Hood function test verified · Solvent storage audit done · Hot side / cold side layout discussed · After-hours check-in protocol set",
  },
  {
    key: "plant_silo_burn_avalanche",
    domain: "plant",
    title: "Asphalt Silo Drag Slat and Material Avalanche",
    severity: "serious_injury",
    category: "Hazard-Specific",
    role_context: ["plant_operator","driver","lead"],
    incident_pattern: "Asphalt silo loadout is a dangerous interface — hot material at 300°F+ sitting in a silo, released through a gate, falling 8–15 feet into a truck bed below. The pattern of injury is two-fold: drivers under the silo during a drop get burns from splash or overflow, and drag-slat conveyors above the silo can throw material if a buildup releases unexpectedly. The classic incident is a driver climbing the silo platform to check the load level, leaning over, and getting hit by a sudden material release as the gate opens. Or a maintenance worker on the drag slat platform when an upstream jam clears.",
    hazards_reviewed: "Burn from sudden material release at gate · Fall from silo platform · Crush from drag-slat chain · Burn from drag-slat oil leak · Toxic vapor inhalation at top of silo · Stuck driver under hot silo",
    discussion_notes: "• Driver under the silo: in the cab during load. Always. Climb out only after the gate has closed and the chute drained.\n• Silo top access: harness and tie-off above 6 ft. Even on a railed platform, fall protection during any task that involves leaning.\n• Drag-slat conveyors are LOTO whenever a worker is on the platform for service or inspection. Walking past for visual check from a safe distance is one thing — service work needs full LOTO.\n• Communication between loadout operator and driver — radio or horn signal. Driver knows when the gate is about to open.\n• Silo gate misfires — if a gate isn't sealing, take the silo OUT OF SERVICE for repair. Do not work around a misfiring gate.\n• Vapors at the silo top — bitumen vapors collect in the top space. Don't open the inspection hatch in calm wind without ventilation. Take a break upwind after exposure.\n• Truck bed under the silo: visual confirmation before opening the gate. Empty bed, properly positioned. Foreman gives the OK.",
    references_cited: "OSHA 29 CFR 1926.501 · MSHA Silo Safety · OEM silo / drag-slat manuals · MASCI Loadout SOP",
    action_items: "Driver-in-cab-at-loadout rule reinforced · Silo top fall protection verified · Drag-slat LOTO procedure reviewed · Gate-misfire OOS rule discussed",
  },
];
