// Auto-split from monolithic meetingTopicLibrary.es.js · iter260
// Domain: shop · 8 ES translations

export const TOPICS_SHOP_ES = {
  shop_jack_stand_failure: {
    title: "Fallas de Caballetes — Fatalidades Bajo el Camión",
    incident_pattern: "Casi cada fatalidad de caballete sigue la misma secuencia: un mecánico levanta un camión o trailer pesado con el gato de piso, pone dos caballetes, se mete a empezar el trabajo, y el camión se mueve. A veces es porque los caballetes se pusieron en un miembro de chasis oxidado, a veces porque el piso tenía pendiente, a veces porque eran de capacidad menor a la carga. El camión no cae todo lo que puede — solo se asienta 2 pulgadas. Eso es suficiente para aplastar un pecho. No hay aviso. El mecánico está solo, frecuentemente al final del turno, y nadie lo encuentra por una hora. Hemos perdido mecánicos en esta industria a este patrón más veces de las que nadie quiere contar.",
    hazards_reviewed: "Aplastamiento fatal por caída de vehículo · Caballete hundiéndose en piso blando · Capacidad de caballete equivocada para la carga · Un solo caballete en vez de par · Trabajar solo bajo carga · Deslizamiento / falla de gato hidráulico",
    discussion_notes: "• Gato de piso es para LEVANTAR, nunca para SOSTENER. En el momento que la carga está arriba, caballetes de la capacidad de la carga van bajo PUNTOS DE LEVANTE APROPIADOS.\n• Caballetes con capacidad AL MENOS al peso de la carga, con margen. Un camión de 40,000 lb no va en caballetes de 6 toneladas. Lea la capacidad, haga las cuentas.\n• Ambos caballetes enganchados — no solo uno con el gato todavía debajo como segundo sostén. Un mango golpeado tira el camión.\n• Cuñas en las ruedas del EXTREMO OPUESTO. Trans en velocidad o parking. Freno de mano PUESTO. Cinturón y tirantes.\n• Coloque caballetes en el CHASIS, no en faldones de plástico, no en paneles de carrocería, no en estructura oxidada. Toque y mire antes de poner.\n• Solo piso de concreto. Puntos blandos de asfalto pueden fallar bajo un solo caballete. Si debe trabajar sobre asfalto, use una placa de acero para distribuir la carga.\n• Tug-test ANTES de meterse abajo. Empuje el camión, sacúdalo. Si algo se mueve más que la oscilación de la suspensión, rehaga el levante.\n• No trabaje solo bajo un vehículo. Si debe, fije una hora de check-in con alguien que lo busque si no contesta el mensaje.",
    references_cited: "OSHA 29 CFR 1910.244 · ANSI/PASE 5/MH29 (caballetes) · Manuales OEM de puntos de levante · SOP de Levante en Taller MASCI",
    action_items: "Mapa de puntos de levante para unidades comunes publicado · Verificación de capacidad de caballete asignada · Hábito de tug-test reforzado · Protocolo de check-in solo-bajo-vehículo fijado",
  },
  shop_lockout_tagout_bypass: {
    title: "Lockout / Tagout — El Bypass Que Mata",
    incident_pattern: "Las fallas de LOTO no matan al trabajador que puso el lockout — matan al trabajador que NO lo puso. El patrón: una pieza de equipo está en el taller para servicio hidráulico. El mecánico líder hace lockout correctamente. Un segundo mecánico, ayudando, no tiene su candado personal en él. Un tercer mecánico, terminando su turno, ve el equipo y decide 'nomás picar' los controles para revisar algo. El segundo mecánico, con la mano dentro del área del cilindro, queda aplastado. El candado del primer mecánico estaba correcto. El sistema falló porque no cada persona bajo el equipo tenía su propio candado.",
    hazards_reviewed: "Liberación de energía hidráulica almacenada · Aplastamiento por colapso de cilindro · Re-energización eléctrica durante servicio · Arranque de banda durante alineación · Liberación neumática de aire almacenado · Caída de contrapeso",
    discussion_notes: "• Un trabajador, un candado. CADA persona que tenga cualquier parte del cuerpo en o cerca de la zona de peligro pone SU PROPIO candado. Sin atajos de 'comparto candado.'\n• Etiquete el candado con quién lo puso y cuándo. Así el tercer mecánico que llega sabe de quién es este lockout y no lo quita.\n• Verifique energía cero: ciclar los controles, revisar los manómetros, bajar presión hidráulica a cero, drenar aire almacenado. CADA servicio.\n• Bloquee cilindros hidráulicos mecánicamente. Un soporte de cilindro, un bloque de madera, una cadena — algo que sostenga la carga si el sello falla.\n• No confíe en 'el jefe dijo que está bloqueado.' Verifique con sus propios ojos. Ponga su propio candado. Trate de arrancar.\n• Quitar un lockout: SOLO el trabajador que lo puso. Si no está en sitio, siga el procedimiento de retiro — usualmente requiere autorización del supervisor e intento documentado de localizar al dueño original.\n• Mecánicos nuevos: caminen un procedimiento LOTO con el líder el Día 1. Cada. Sola. Vez.",
    references_cited: "OSHA 29 CFR 1910.147 · Manuales de servicio OEM · Estándar LOTO de Taller MASCI",
    action_items: "Regla de un-trabajador-un-candado reforzada · Etiquetado de candado discutido · Verificación de energía cero revisada · Práctica de bloqueo de cilindro asignada · Recorrido LOTO para mecánico nuevo programado",
  },
  shop_brake_spring_energy: {
    title: "Liberación de Energía Almacenada en Resorte de Freno",
    incident_pattern: "Las liberaciones de cámara de freno han matado y cegado mecánicos por décadas, y siguen haciéndolo. El patrón es siempre el mismo: un mecánico reemplaza una cámara de freno o trabaja un ajustador de holgura en una unidad sin resorte enjaulado. Golpean un pasador atascado con martillo, o desatornillan una cámara que todavía sostiene la fuerza del resorte, y la cámara se desarma con la energía de una pequeña explosión. El resorte interno tiene capacidad de 2,000 lb de fuerza. Cuando eso se libera a seis pulgadas de una cara, es un impacto facial fatal. Enjaular el resorte no es opcional y nunca lo ha sido.",
    hazards_reviewed: "Proyectil de liberación de cámara de freno · Trauma facial / pectoral por componente de cámara · Pérdida de ojo por metralla de resorte · Daño auditivo por liberación · Pellizco durante enjaulamiento",
    discussion_notes: "• SIEMPRE enjaule el resorte antes de tocar un perno de servicio de cámara de freno, ajustador de holgura, o vástago. Las herramientas de enjaular son baratas. Los mecánicos nuevos cuestan más.\n• Use el puerto de enjaular de la cámara — deslice la herramienta, gírela 90°, jale apretado. Verifique que la jaula esté enganchada antes de quitar cualquier perno de servicio.\n• Párese al LADO durante la verificación de liberación. No al frente, no atrás — al lado. La trayectoria de liberación es derecho hacia afuera.\n• Protección ocular es no-negociable. No solo lentes de seguridad — careta completa sobre lentes para trabajo de freno.\n• Si no puede enjaular porque el puerto está oxidado, considere la unidad fuera-de-servicio para trabajo de taller. Corte la cámara como unidad y reemplácela con el resorte todavía enjaulado en la cámara VIEJA.\n• Tapones pop-off en el extremo del vástago — nunca los manipule. Son calificados para PRESIÓN, no para servicio.\n• Capacite a cada mecánico nuevo en instalación de jaula la primera semana. Hágalos hacerlo con una cámara en sus manos.",
    references_cited: "Servicio de Frenos FMCSA · Manuales OEM de cámara de freno · OSHA 1910.132 (PPE) · SOP de Taller de Frenos MASCI",
    action_items: "Inventario de herramienta de jaula verificado · Hábito de enjaular-antes-de-servicio reforzado · Requisito de careta revisado · Capacitación para mecánico nuevo programada",
  },
  shop_tire_cage_explosion: {
    title: "Explosiones de Jaula de Llanta y Rines de Múltiples Piezas",
    incident_pattern: "Los incidentes de jaula de llanta no son lo que la gente piensa. Las famosas fatalidades viejas — rines de múltiples piezas separándose durante inflado — siguen pasando porque algún equipo todavía corre en esos rines. Un rin de cargador, un rin de motoconformadora, un rin viejo de carretera. El mecánico desinfla, desmonta, vuelve a armar, infla sin jaula, y el anillo de cierre se separa a 80 psi. La energía es equivalente a una pequeña carga explosiva. Hay video. Todos lo hemos visto. El arreglo es más viejo que la mayoría de la gente en talleres hoy — y la gente sigue muriendo porque la jaula 'nada más por un segundo' se dejó a un lado.",
    hazards_reviewed: "Proyectil de separación de anillo de cierre durante inflado · Mecánico en línea de fuego · Falla de rin múltiple por corrosión · Agrietamiento de rin de una pieza · Recogida de manguera de inflado · Explosión de talón de llanta",
    discussion_notes: "• Jaula de llanta para CADA inflado, cada vez. Incluidos rines de una pieza — las fallas de talón pasan ahí también.\n• Párese al LADO durante el inflado. Nunca al frente del rin. Manguera de inflado larga con manómetro en línea para que esté afuera de la trayectoria.\n• Inspeccione rines ANTES de montar. Anillos de cierre, anillos laterales, canales — busque grietas, corrosión, deformación. Si el anillo no asienta limpio, el rin no vuelve a servicio.\n• Rines de múltiples piezas deben coincidir. Mezclar fabricantes o tamaños es lo que causa la mayoría de las separaciones. Si no está seguro que coincide, dispóngalo.\n• Infle en etapas. Asiente el talón a menor presión, verifique asentado, luego suba a presión de operación.\n• Lubricante de talón — solo agua y jabón. NUNCA use lubricantes con solvente. Pueden inflamarse bajo alta temperatura.\n• Los veteranos a veces saltan la jaula porque 'conocen' el rin. El rin no los conoce a ellos. Use la jaula.",
    references_cited: "OSHA 29 CFR 1910.177 · Manuales OEM de servicio de rin · Estándares de servicio de llanta TIA · SOP de Taller de Llantas MASCI",
    action_items: "Regla de jaula-cada-inflado reforzada · Paso de inspección de rin verificado · Política de lubricante de talón revisada · Política de rin de múltiples piezas discutida",
  },
  shop_welding_fire_watch: {
    title: "Fire Watch de Soldadura y Limpieza Post-Trabajo en Caliente",
    incident_pattern: "Los incendios de taller por soldadura casi nunca pasan durante la soldadura — pasan 20 a 60 minutos DESPUÉS. El soldador corta un soporte, esmerila el cordón, sopla la escoria, y se va. Una chispa que cayó en trapos aceitosos en una repisa, atrás de un tambo de 55 galones, o en cartón empaque arde lento. El taller está vacío para entonces. El detector de humo se dispara a la 1:30 a.m. y los bomberos llegan a un edificio totalmente envuelto. El arreglo es de décadas: limpieza, fire watch, inspección post-soldadura. Lo sabemos. Seguimos perdiendo edificios a fire watches saltadas.",
    hazards_reviewed: "Fuego de arder-lento en materiales aceitosos / con polvo · Fuego escondido tras / bajo equipo · Lesión por quemadura / humo · Incendio total del edificio · Ignición por chispa de líquido inflamable · Ignición de vapor durante corte",
    discussion_notes: "• Permiso de trabajo en caliente para cada trabajo de soldadura / corte / esmerilado. Hábito viejo, todavía correcto. El permiso nombra al soldador, la ubicación, el fire watch, y la hora de fin.\n• Despeje un radio de 35 pies antes de que vuelen chispas. Mueva trapos aceitosos, contenedores de combustible, cartón, aserrín, tambos de aceite hidráulico. TODO lo combustible.\n• Moje lo que no pueda mover. Cobijas de soldadura sobre lo que sí. Escudos de acero sobre aberturas a cuartos adyacentes.\n• El fire watch SE QUEDA por 30 minutos después de la última chispa. Teléfono en mano. Ojos en cada lugar donde pudo haber caído una chispa.\n• Revise ARRIBA y ABAJO de rejillas, en drenajes de piso, atrás de cualquier equipo dentro del radio de 35 ft. Las chispas viajan.\n• Extintor cargado al alcance del brazo durante Y después. Confirme que no es el vacío del último simulacro.\n• Último soldador al cierre de turno: camine todo el taller. Toque superficies, huela el aire. El humo y calor dicen lo que los ojos no.",
    references_cited: "NFPA 51B · OSHA 29 CFR 1910.252 · NFPA 241 · SOP de Permiso de Trabajo en Caliente MASCI",
    action_items: "Permisos de trabajo en caliente requeridos + publicados · Zona-libre de 35 ft aplicada · Duración del fire watch verificada · Caminata de fin de turno discutida",
  },
  shop_hydraulic_stored_energy: {
    title: "Energía Hidráulica Almacenada en Cilindros, Mangueras y Acumuladores",
    incident_pattern: "Las lesiones por inyección hidráulica se ven menores y matan gente. Un agujero pinhole en una manguera a 2,500 psi atomiza aceite a través de la piel como aguja hipodérmica. El mecánico ve un piquete diminuto en su mano, lo lava, lo venda, se va a casa. Dentro de 24 horas la mano está hinchada, el tejido se está muriendo por contaminación de aceite, y la sala de emergencias está amputando. Compuesto con la liberación de presión cruda de cilindro — un acople se afloja y el cilindro descarga a través del taller — y un acople se vuelve proyectil. La energía hidráulica almacenada es invisible. Mata mecánicos que no la respetan.",
    hazards_reviewed: "Lesión por inyección hidráulica a través de piel · Proyectil de acople / manguera · Extensión sin control de cilindro al liberar energía · Aplastamiento por caída de carga al despresurizar · Quemadura por aceite caliente · Lesión ocular por aceite atomizado",
    discussion_notes: "• Nunca busque una fuga hidráulica con la mano. Use cartón, papel o un pedazo de madera. Si encuentra una fuga, reemplace la manguera — no la parche.\n• Baje la presión a cero ANTES de desconectar cualquier acople. Cicle los controles con el motor apagado. Mire el manómetro. Verifique CERO.\n• Los acumuladores hidráulicos quedan presurizados DESPUÉS de cero en el manómetro del sistema. Descárguelos por el procedimiento OEM antes de tocar cualquier línea conectada.\n• Si aceite contacta piel bajo presión — ER YA. Aun si 'se ve como nada.' Dígales que fue inyección hidráulica. El reloj de cirugía empieza inmediato.\n• Herramientas de mango largo al trabajar cerca de una manguera presurizada. Párese fuera-de-eje al aflojar un acople.\n• Inspecciones de manguera semanales. Grietas, abrasión, bultos, fugas. Reemplace antes de la falla.\n• Protección ocular Y careta para cualquier trabajo hidráulico abierto. Sistema cerrado es regla distinta — sistema abierto es PPE completo.\n• Bloquee cilindros mecánicamente antes de trabajar en ellos. La presión hidráulica puede desaparecer y la carga puede caer si un sello falla.",
    references_cited: "OSHA 29 CFR 1910.147 · Seguridad de Fluid Power Society · Manuales de servicio OEM · SOP de Servicio Hidráulico MASCI",
    action_items: "Regla de buscar-pinhole-con-cartón discutida · Procedimiento de descarga de acumulador revisado · Política de ER-inmediato-para-inyección reforzada · Bloqueo de cilindro verificado",
  },
  shop_under_bed_crush_zone: {
    title: "Zonas de Aplastamiento Bajo Cajas, Brazos y Equipo",
    incident_pattern: "El pasador de body-prop en una caja volcadora existe por una razón: mantener vivos a los mecánicos cuando la caja baja inesperadamente. La mayoría de fatalidades bajo cajas pasan porque el prop se 'nomás por un minuto' dejó a un lado mientras el mecánico alcanzaba para liberar un pasador atorado o engrasar un pivote. Un sello hidráulico falla. Un interruptor de control se golpea. Una fuga que ha sido menor finalmente cede. La caja baja. El mecánico, manos arriba, queda atrapado entre caja y chasis. No hay escape de ese pellizco — se mide en fracciones de segundo, no segundos.",
    hazards_reviewed: "Aplastamiento entre caja y chasis en dump trucks · Aplastamiento bajo brazo en excavadores / grúas · Pellizco en rotación de contrapeso · Aplastamiento bajo attachment sin apoyo · Caída de cucharón / cuchilla con motor apagado",
    discussion_notes: "• Pasador de body-prop enganchado CUALQUIER vez que un mecánico esté bajo una caja levantada. No 'la mayoría del tiempo.' CADA vez. Aun por 30 segundos de engrase.\n• Brazo o pluma: BÁJELO HASTA EL FONDO antes de cualquier servicio. Si debe trabajar bajo uno levantado, bloquéelo con cribbing calificado para la carga.\n• Pasadores de stinger en stinger steer / tag-axles — póngalos adentro o afuera, no trabaje bajo ellos en posición media. El amortiguamiento hidráulico no sostendrá.\n• Rotación de contrapeso en excavadores — despeje el radio de giro antes de servicio. Aun con motor apagado, los hidráulicos pueden deslizar.\n• Cucharón / cuchilla — baje al suelo o bloquee antes de servicio. Las fallas de sello hidráulico tiran cargas. Los bloques mecánicos no.\n• Comuníquense en cambio de turno. El mecánico nuevo que toma un trabajo necesita saber qué está bloqueado, qué está pasador, qué está presurizado.\n• Si un body prop no engancha limpio, el camión no entra a trabajo. Arregle el prop primero.",
    references_cited: "OSHA 29 CFR 1910.147 · Manuales OEM de body prop · Estándares ANSI / SAE de bloqueo · SOP de Taller MASCI",
    action_items: "Regla de pasador-de-prop-siempre reforzada · Inventario de cribbing verificado · Zona-libre de contrapeso revisada · Comunicación de cambio de turno discutida",
  },
  shop_battery_explosion: {
    title: "Carga, Boost y Explosión de Hidrógeno de Batería",
    incident_pattern: "Las explosiones de batería se ven como efecto de película y pasan en la vida real. Un mecánico está dando boost a un camión muerto, la batería muerta ha estado descargada por semanas, y las celdas han desgasificado hidrógeno al gabinete. La pinza de boost arquea al borne, la chispa enciende el hidrógeno, y el gabinete revienta. Ácido y fragmentos de plástico vuelan en cada dirección — a la cara, ojos, brazos del mecánico. Las lesiones son a veces cegadoras y siempre con quemaduras. El arreglo es más viejo que el camión: conecte último a tierra, no a la batería, y revise abultamiento de gabinete o desgasificación antes de tocarla.",
    hazards_reviewed: "Explosión de hidrógeno durante boost / carga · Quemadura por ácido en ojos / piel · Salpicón de ácido por gabinete agrietado · Arco / fuego de cable de boost · Ruptura de gabinete por corto interno · Lesión por levantar baterías comerciales pesadas",
    discussion_notes: "• Mire la batería ANTES de conectar. Gabinete abultado = FUERA DE SERVICIO. Reemplace, no boostee.\n• Secuencia de conexión de boost: rojo-positivo a positivo-muerto · rojo-positivo a positivo-vivo · negro-negativo a negativo-vivo · negro-negativo a TIERRA DE VEHÍCULO MUERTO (chasis), NO al borne de batería muerta.\n• Esa última conexión es donde sucede el arco. Ponerlo en una tierra de chasis mantiene el arco LEJOS del hidrógeno en las celdas.\n• Protección ocular puesta. El ácido no es sobrevivible en los ojos sin enjuague inmediato — 15+ minutos en la estación de lavaojos.\n• Ventilación durante carga. Abra el cofre. No cargue un camión sellado en una bahía cerrada sin ventilación.\n• Desconecte el negativo PRIMERO al quitar una batería. Conecte negativo ÚLTIMO al instalar. Reduce riesgo de arco en la celda.\n• Las baterías comerciales son PESADAS — 70+ lbs. Cargar entre dos o levantador apropiado. Espaldas y dedos del pie son lesiones típicas.\n• Kit de derrames de ácido y estación de lavaojos probados cada mes. Lavaojos sin probar es lavaojos inútil.",
    references_cited: "OSHA 29 CFR 1910.151 · OSHA 1910.305 · Manuales OEM de servicio de batería · SOP de Servicio de Batería MASCI",
    action_items: "Paso de inspección visual de batería agregado · Secuencia de boost-a-tierra-no-batería reforzada · Prueba mensual de lavaojos programada · Política de levante entre dos revisada",
  },
};
