// Auto-split from monolithic meetingTopicLibrary.js · iter260
// Domain: shop · 8 topics
// Edit content here; index.js aggregates all domains.

export const TOPICS_SHOP = [
  {
    key: "shop_jack_stand_failure",
    domain: "shop",
    title: "Jack-Stand Failures — Under-the-Truck Fatalities",
    category: "Hazard-Specific",
    role_context: ["mechanic","lead"],
    incident_pattern: "Almost every jack-stand fatality follows the same sequence: a mechanic raises a heavy truck or trailer on the floor jack, sets two stands, slides under to start work, and the truck shifts. Sometimes it's because the stands were placed on a rusted frame member, sometimes because the ground sloped just enough, sometimes because they were undersized for the load. The truck doesn't fall all the way — it just settles 2 inches. That's enough to crush a chest. There is no warning. The mechanic is alone, often at end-of-shift, and no one finds them for an hour. We have lost mechanics in this industry to this exact pattern more times than anyone wants to count.",
    hazards_reviewed: "Crush fatality from vehicle drop · Stand sinking into soft floor · Wrong stand rating for load · Single stand instead of pair · Working alone under load · Hydraulic jack creep / failure",
    discussion_notes: "• Floor jack is for LIFTING, never for HOLDING. The moment the load is at height, jack stands rated to the load go under PROPER lift points.\n• Stands rated to AT LEAST the load weight, with margin. A 40,000-lb truck doesn't go on 6-ton stands. Read the rating, do the math.\n• Both stands engaged — not just one with the jack still under as the second hold. A bumped jack handle drops the truck.\n• Wheels chocked on the OPPOSITE end. Trans in gear or park. Parking brake ON. Belt-and-suspenders.\n• Place stands on the FRAME, not on plastic skirts, not on body panels, not on rusted-through structure. Tap and look before you set.\n• Concrete floor only. Asphalt soft-spots can fail under a single stand. If you have to work on asphalt, use a steel plate to spread the load.\n• Tug-test BEFORE you slide under. Lean on the truck, shake it. If anything moves more than the rocking of suspension, redo the lift.\n• Don't work alone under a vehicle. If you must, set a check-in time with someone who will look for you if you don't text back.",
    references_cited: "OSHA 29 CFR 1910.244 · ANSI/PASE 5/MH29 (jack stands) · OEM lift-point manuals · MASCI Shop Lift SOP",
    action_items: "Lift-point map for common units posted · Stand rating check assigned · Tug-test habit reinforced · Solo-under-vehicle check-in protocol set",
  },
  {
    key: "shop_lockout_tagout_bypass",
    domain: "shop",
    title: "Lockout / Tagout — The Bypass That Kills",
    category: "Procedure / SOP",
    role_context: ["mechanic","lead","operator"],
    incident_pattern: "LOTO failures don't kill the worker who set the lockout — they kill the worker who DIDN'T. The pattern: a piece of equipment is in the shop for hydraulic service. The lead mechanic locks it out properly. A second mechanic, helping out, doesn't have a personal lock on it. A third mechanic, finishing his shift, sees the equipment and decides to 'just bump' the controls to check something. The second mechanic, hand inside the cylinder area, gets crushed. The first mechanic's lock was correct. The system failed because not every person under the equipment had their own lock on it.",
    hazards_reviewed: "Stored hydraulic energy release · Crush from cylinder collapse · Electrical re-energization during service · Belt restart during alignment · Pneumatic release of stored air · Counterweight drop",
    discussion_notes: "• One worker, one lock. EVERY person who has any part of their body in or near the danger zone hangs THEIR OWN lock. No 'I'll share a lock' shortcuts.\n• Tag the lock with who set it and when. So the third mechanic walking up knows whose lockout this is and doesn't undo it.\n• Verify zero energy: cycle the controls, check the gauges, drop hydraulic pressure to zero, drain stored air. EVERY service.\n• Block hydraulic cylinders mechanically. A cylinder support, a wood block, a chain — something that holds the load if the seal fails.\n• Don't trust 'the boss said it's locked.' Verify with your own eyes. Put your own lock on it. Try to start it.\n• Removing a lockout: ONLY the worker who set it. If they're not on-site, follow the lock-removal procedure — usually requires supervisor authorization and a documented attempt to reach the original locker.\n• New mechanics: walk a LOTO procedure with the lead on Day 1. Every. Single. Time.",
    references_cited: "OSHA 29 CFR 1910.147 · OEM service manuals · MASCI Shop LOTO Standard",
    action_items: "One-worker-one-lock rule reinforced · Lock tagging discussed · Zero-energy verification reviewed · Cylinder blocking practice assigned · New-mechanic LOTO walkthrough scheduled",
  },
  {
    key: "shop_brake_spring_energy",
    domain: "shop",
    title: "Brake Spring Stored Energy Release",
    category: "Hazard-Specific",
    role_context: ["mechanic","lead"],
    incident_pattern: "Brake chamber spring releases have killed and blinded mechanics for decades, and they keep doing it. The pattern is always the same: a mechanic is replacing a brake chamber or working a slack adjuster on a unit with no caged spring. They strike a stuck pin with a hammer, or unbolt a chamber that's still holding its spring force, and the chamber comes apart with the energy of a small explosion. The internal spring is rated to 2,000 lb of force. When that releases six inches from a face, it's a fatal facial impact. Caging the spring is not optional and never has been.",
    hazards_reviewed: "Spring brake chamber release projectile · Facial / chest trauma from chamber component · Eye loss from spring shrapnel · Hearing damage from release · Pinch injury during caging",
    discussion_notes: "• ALWAYS cage the spring before touching a brake chamber service bolt, slack adjuster, or pushrod. Caging tools are cheap. New mechanics cost more.\n• Use the chamber's caging port — slide the caging tool in, turn it 90°, pull tight. Verify the cage is engaged before removing any service bolt.\n• Stand to the SIDE during release verification. Not in front, not behind — to the side. The release path is straight out.\n• Eye protection is non-negotiable. Not safety glasses — a full face shield over safety glasses for brake work.\n• If you can't cage it because the port is rusted shut, treat the unit as out-of-service for shop work. Cut the chamber off as a unit and replace it with the spring still caged in the OLD chamber.\n• Pop-off plugs on the chamber pushrod end — never tamper with them. They are PRESSURE-rated, not service-rated.\n• Train every new shop hand on cage installation in the first week. Make them do it with a chamber in their hands.",
    references_cited: "FMCSA Brake Service · OEM brake chamber manuals · OSHA 1910.132 (PPE) · MASCI Brake Shop SOP",
    action_items: "Spring caging tool inventory verified · Caging-before-service habit reinforced · Face-shield requirement reviewed · New-hand training scheduled",
  },
  {
    key: "shop_tire_cage_explosion",
    domain: "shop",
    title: "Tire Cage Explosions and Multi-Piece Rims",
    category: "Hazard-Specific",
    role_context: ["mechanic","tire_tech","lead"],
    incident_pattern: "Tire-cage incidents are not what people think. The famous old fatalities — multi-piece rims separating during inflation — are still happening because some equipment still runs on those rims. A loader rim, a road-grader rim, an older over-the-road rim. The mechanic deflates, dismounts, reassembles, inflates without a cage, and the lock ring separates at 80 psi. The energy is equivalent to a small explosive charge. There is video. We have all seen it. The fix is older than most of the people working in shops today — and people are still dying because the cage was 'just for a second' set aside.",
    hazards_reviewed: "Lock-ring separation projectile during inflation · Mechanic in line of fire · Multi-piece rim corrosion failure · Single-piece rim cracking · Inflation hose recoil · Tire bead explosion",
    discussion_notes: "• Tire cage for EVERY inflation, every time. Single-piece rims included — bead failures happen on those too.\n• Stand to the SIDE during inflation. Never in front of the rim. Long inflation hose with in-line gauge so you stand outside the trajectory.\n• Inspect rims BEFORE you mount. Lock rings, side rings, gutters — look for cracks, corrosion, deformation. If the ring doesn't seat clean, the rim doesn't go back in service.\n• Multi-piece rims need to match. Mixing manufacturers or sizes is what causes most separations. If you're not sure it matches, scrap it.\n• Inflate in stages. Bead seat at lower pressure, verify seating, then take it up to running pressure.\n• Bead lubricant — water and soap only. NEVER use solvent-based lubricants. They can ignite under high heat.\n• Old hands sometimes skip the cage because they 'know' the rim. The rim does not know them. Use the cage.",
    references_cited: "OSHA 29 CFR 1910.177 · OEM rim service manuals · TIA tire service standards · MASCI Tire Shop SOP",
    action_items: "Cage-every-inflation rule reinforced · Rim inspection step verified · Bead lubricant policy reviewed · Multi-piece rim policy discussed",
  },
  {
    key: "shop_welding_fire_watch",
    domain: "shop",
    title: "Welding Fire Watch and Hot-Work Cleanup",
    category: "Hazard-Specific",
    role_context: ["welder","fire_watch","lead"],
    incident_pattern: "Shop fires from welding almost never happen during the weld — they happen 20 to 60 minutes AFTER. The welder cuts a brace, grinds the bead, blows the slag away, and walks off. A spark that landed in oily rags on a shelf, behind a 55-gallon drum, or in cardboard packaging smolders. The shop is empty by then. The smoke detector kicks at 1:30 a.m. and the fire department arrives to a fully-involved building. The fix is decades-old: cleanup, fire watch, post-weld inspection. We know this. We keep losing buildings to skipped fire watches.",
    hazards_reviewed: "Slow-smolder fire in oily / dusty materials · Hidden fire behind / under equipment · Burn / smoke injury · Total-loss building fire · Spark ignition of flammable liquid · Vapor ignition during cutting",
    discussion_notes: "• Hot-work permit for every welding / cutting / grinding job. Old habit, still right. Permit names the welder, the location, the fire watch, and the end time.\n• Clear a 35-foot radius before sparks fly. Move oily rags, fuel containers, cardboard, sawdust, hydraulic fluid drums. EVERYTHING combustible.\n• Wet down what you can't move. Welding blankets over what you can. Steel shields over openings into adjacent rooms.\n• Fire watch STAYS for 30 minutes after the last spark. Phone in hand. Eyes on every place a spark could have landed.\n• Check ABOVE and BELOW grates, into floor drains, behind any equipment within the 35-ft radius. Sparks travel.\n• Charged extinguisher within arm's reach during AND after. Confirm it's not the empty one from the last drill.\n• Last welder out at end of shift: walk the whole shop. Touch surfaces, smell the air. Smoke and heat tell you what eyes don't.",
    references_cited: "NFPA 51B · OSHA 29 CFR 1910.252 · NFPA 241 · MASCI Hot Work Permit SOP",
    action_items: "Hot-work permits required + posted · 35-ft clear-zone enforced · Fire-watch duration verified · End-of-shift walk discussed",
  },
  {
    key: "shop_hydraulic_stored_energy",
    domain: "shop",
    title: "Hydraulic Stored Energy in Cylinders, Hoses, and Accumulators",
    category: "Hazard-Specific",
    role_context: ["mechanic","lead"],
    incident_pattern: "Hydraulic injection injuries look minor and kill people. A pinhole in a hose at 2,500 psi sprays oil through skin like a hypodermic needle. The mechanic sees a tiny puncture in their hand, washes it, bandages it, goes home. Within 24 hours the hand is swollen, the tissue is dying from oil contamination, and the emergency room is amputating. Compounded with raw cylinder pressure release — a loose fitting backs off and the cylinder discharges across the shop — and a fitting becomes a projectile. Stored hydraulic energy is invisible. It kills mechanics who don't respect it.",
    hazards_reviewed: "Hydraulic injection injury through skin · Fitting / hose projectile · Cylinder uncontrolled extension at energy release · Crush from load drop when pressure bleeds · Burn from hot oil · Eye injury from sprayed oil",
    discussion_notes: "• Never search for a hydraulic leak with your hand. Use cardboard, paper, or a piece of wood. If you find a leak, replace the hose — don't band-aid it.\n• Drop pressure to zero BEFORE disconnecting any fitting. Cycle the controls with the engine off. Watch the gauge. Verify ZERO.\n• Hydraulic accumulators stay pressurized AFTER zero on the system gauge. Discharge them per the OEM procedure before touching any line connected to them.\n• If oil contacts skin under pressure — ER NOW. Even if it 'looks like nothing.' Tell them it was a hydraulic injection. Surgery clock starts immediately.\n• Long-handled tools when working close to a pressurized hose. Stand off-axis when cracking a fitting.\n• Hose inspections weekly. Cracks, abrasion, bulges, leaks. Replace before failure.\n• Eye protection AND face shield for any open hydraulic work. Closed system is a different rule — open system is full PPE.\n• Block cylinders mechanically before working on them. Hydraulic pressure can disappear and the load can still drop if a seal lets go.",
    references_cited: "OSHA 29 CFR 1910.147 · Fluid Power Society safety · OEM service manuals · MASCI Hydraulic Service SOP",
    action_items: "Pinhole-search-with-cardboard rule discussed · Accumulator discharge procedure reviewed · ER-immediately-for-injection policy reinforced · Cylinder blocking verified",
  },
  {
    key: "shop_under_bed_crush_zone",
    domain: "shop",
    title: "Crush Zones Under Beds, Booms, and Equipment",
    category: "Hazard-Specific",
    role_context: ["mechanic","operator","lead"],
    incident_pattern: "The body-prop pin on a dump bed exists for one reason: to keep mechanics alive when the bed comes down unexpectedly. Most under-bed fatalities happen because the prop was 'just for a minute' set aside while the mechanic reached up to free a stuck pin or grease a pivot. A hydraulic seal lets go. A control switch is bumped. A leak that's been minor finally gives. The bed comes down. The mechanic, hands raised, gets pinned between bed and frame. There is no escape from that pinch — it's measured in fractions of a second, not seconds.",
    hazards_reviewed: "Crush between bed and frame on dump trucks · Under-boom crush on excavators / cranes · Pinch in counterweight rotation · Crush under unsupported attachment · Drop of bucket / blade with engine off",
    discussion_notes: "• Body-prop pin engaged ANY time a mechanic is under a raised bed. Not 'most of the time.' EVERY time. Even for 30 seconds of grease work.\n• Boom or arm: lower it ALL THE WAY DOWN before any service. If you must work under one raised, block it with cribbing rated for the load.\n• Stinger pins on stinger steer / tag-axles — pin them in or out, do not work under them in mid-position. Hydraulic cushion will not hold.\n• Counterweight rotation on excavators — clear the swing radius before service. Even with the engine off, hydraulics can creep.\n• Bucket / blade — drop to ground or block before service. Hydraulic seal failures drop loads. Mechanical blocks don't.\n• Communicate at shift change. New mechanic taking over a job needs to know what's blocked, what's pinned, what's pressurized.\n• If a body prop doesn't engage cleanly, the truck doesn't go under work. Fix the prop first.",
    references_cited: "OSHA 29 CFR 1910.147 · OEM body prop manuals · ANSI / SAE blocking standards · MASCI Shop SOP",
    action_items: "Body-prop-pin-always rule reinforced · Cribbing inventory verified · Counterweight clear-zone reviewed · Shift-handoff communication discussed",
  },
  {
    key: "shop_battery_explosion",
    domain: "shop",
    title: "Battery Charging, Boost, and Hydrogen Explosion",
    category: "Hazard-Specific",
    role_context: ["mechanic","lead","driver"],
    incident_pattern: "Battery explosions look like a movie effect and they happen in real life. A mechanic is boosting a dead truck, the dead battery has been discharged for weeks, and the cells have outgassed hydrogen into the case. The boost clamp arcs at the post, the spark ignites the hydrogen, and the battery case bursts. Acid and plastic fragment fly in every direction — into the mechanic's face, eyes, arms. The injuries are sometimes blinding and always burning. The fix is older than the truck: connect last to a ground, not to the battery, and check for case bulging or off-gassing before you touch it.",
    hazards_reviewed: "Hydrogen explosion during boost / charge · Acid burn to eyes / skin · Acid spray from cracked case · Boost-cable arc / fire · Battery case rupture from internal short · Lifting injury from heavy commercial batteries",
    discussion_notes: "• Look at the battery BEFORE you connect. Bulging case = OUT OF SERVICE. Replace, do not boost.\n• Boost connection sequence: red-positive to dead-positive · red-positive to live-positive · black-negative to live-negative · black-negative to DEAD-VEHICLE GROUND (frame), NOT to the dead battery post.\n• That last connection is where the arc happens. Putting it on a frame ground keeps the arc AWAY from hydrogen at the cells.\n• Eye protection on. Acid is not survivable in the eyes without immediate flushing — 15+ minutes at the eyewash station.\n• Ventilation during charging. Open the hood. Don't charge a sealed truck in a closed bay without ventilation.\n• Disconnect negative FIRST when removing a battery. Connect negative LAST when installing. Reduces arc risk at the cell.\n• Commercial batteries are HEAVY — 70+ lbs. Two-person carry or proper lifter. Backs and toes are typical injuries.\n• Acid spill kit and eye-wash station tested every month. Untested eye-wash is a useless eye-wash.",
    references_cited: "OSHA 29 CFR 1910.151 · OSHA 1910.305 · OEM battery service manuals · MASCI Battery Service SOP",
    action_items: "Battery visual inspection step added · Boost-to-ground-not-battery sequence reinforced · Eyewash monthly test scheduled · Two-person lift policy reviewed",
  },
];
