"""Phase 9B — Report export renderers (XLSX + PDF).

Pure helpers — no FastAPI, no DB. Take a flattened 2-D rows table
(produced by `reports._flatten_for_csv`) and return BytesIO content
ready for `StreamingResponse`.

XLSX uses openpyxl; PDF uses reportlab. Both are already vendored.
"""
from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any, Dict, List


def render_xlsx(report_id: str, rows: List[List[Any]], actor_email: str) -> io.BytesIO:
    import openpyxl
    from openpyxl.styles import Alignment, Font, PatternFill

    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = report_id[:30]

    title_font = Font(name="Calibri", size=14, bold=True, color="0E7490")
    section_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    section_fill = PatternFill("solid", fgColor="0E7490")
    header_font = Font(name="Calibri", size=10, bold=True)
    header_fill = PatternFill("solid", fgColor="E2E8F0")

    rownum = 1
    state = "intro"
    for r in rows:
        if not r:
            rownum += 1
            state = "section_seek"
            continue
        # Detect section headers (1-cell rows after an empty row)
        if state == "section_seek" and len(r) == 1:
            ws.cell(row=rownum, column=1, value=str(r[0])).font = section_font
            ws.cell(row=rownum, column=1).fill = section_fill
            ws.cell(row=rownum, column=1).alignment = Alignment(horizontal="left")
            state = "section_header_row"
            rownum += 1
            continue
        if state == "section_header_row":
            for ci, v in enumerate(r, start=1):
                c = ws.cell(row=rownum, column=ci, value=str(v) if v is not None else "")
                c.font = header_font
                c.fill = header_fill
            state = "section_body"
            rownum += 1
            continue
        if rownum == 1:
            ws.cell(row=rownum, column=1, value=str(r[0]) if r else "").font = title_font
            rownum += 1
            continue
        for ci, v in enumerate(r, start=1):
            ws.cell(row=rownum, column=ci, value=("" if v is None else (v if isinstance(v, (int, float)) else str(v))))
        rownum += 1

    # Auto width — simple heuristic
    for col_idx in range(1, 8):
        max_len = 8
        for row in ws.iter_rows(min_col=col_idx, max_col=col_idx, values_only=True):
            v = row[0]
            if v is None:
                continue
            ln = len(str(v))
            if ln > max_len:
                max_len = ln
        ws.column_dimensions[openpyxl.utils.get_column_letter(col_idx)].width = min(max_len + 2, 60)

    # Footer sheet with provenance
    meta = wb.create_sheet(title="Provenance")
    meta["A1"] = "MASCI Trench Safety Report"
    meta["A1"].font = title_font
    meta["A2"] = f"Report ID: {report_id}"
    meta["A3"] = f"Generated by: {actor_email}"
    meta["A4"] = f"Generated at: {datetime.now(timezone.utc).isoformat()}"
    meta["A5"] = "Source: certified Trench Safety Operations System (no analytics engine)"

    out = io.BytesIO()
    wb.save(out)
    out.seek(0)
    return out


def render_pdf(report_id: str, rows: List[List[Any]], actor_email: str, filters: Dict[str, Any]) -> io.BytesIO:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=0.5 * inch, rightMargin=0.5 * inch,
        topMargin=0.5 * inch, bottomMargin=0.5 * inch,
        title=f"MASCI Trench Safety · {report_id}",
        author="MASCI Operations Platform",
    )
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=18, textColor=colors.HexColor("#0e7490"), spaceAfter=4)
    kicker = ParagraphStyle("kicker", parent=styles["Normal"], fontSize=8, textColor=colors.HexColor("#64748b"),
                             spaceAfter=12, leading=10, alignment=0)
    section = ParagraphStyle("section", parent=styles["Heading2"], fontSize=12,
                              textColor=colors.HexColor("#0e7490"), spaceBefore=12, spaceAfter=4)
    body = ParagraphStyle("body", parent=styles["Normal"], fontSize=9, leading=11)

    story = []
    pretty_id = report_id.replace("-", " ").title()
    story.append(Paragraph(f"MASCI Trench Safety · {pretty_id} Report", h1))
    story.append(Paragraph(
        f"Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} · "
        f"By <b>{actor_email}</b> · "
        f"From the certified Trench Safety Operations System (no analytics engine).",
        kicker,
    ))

    # Filters block
    flt = filters or {}
    flt_used = {k: v for k, v in flt.items() if v}
    if flt_used:
        flt_rows = [["Filter", "Value"]] + [[k, str(v)] for k, v in flt_used.items()]
        tbl = Table(flt_rows, colWidths=[1.6 * inch, 5.4 * inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0e7490")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
            ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(Paragraph("Filters Applied", section))
        story.append(tbl)
    else:
        story.append(Paragraph("Filters Applied", section))
        story.append(Paragraph("None — full registry scope.", body))

    # Walk the flattened rows and emit sections.
    # The flattener emits: title row, ts row, blank, then alternating
    # section_title (single cell) + header row + body rows + blank.
    i = 0
    n = len(rows)
    section_started = False
    current_table_rows: List[List[str]] = []

    def _flush_table(title_or_none):
        nonlocal current_table_rows
        if not current_table_rows:
            return
        # Header is first row in current_table_rows
        max_cols = max(len(r) for r in current_table_rows)
        norm = [[str(c) if c is not None else "" for c in r] + [""] * (max_cols - len(r))
                for r in current_table_rows]
        widths = [7.0 / max(max_cols, 1) * inch] * max_cols
        tbl = Table(norm, colWidths=widths, repeatRows=1)
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e2e8f0")),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cbd5e1")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#fafbfc"), colors.white]),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(tbl)
        current_table_rows = []

    while i < n:
        r = rows[i]
        if not r:
            _flush_table(None)
            section_started = False
            i += 1
            continue
        if len(r) == 1 and not section_started:
            # Section header
            _flush_table(None)
            title_text = str(r[0])
            # Skip the very first two banner rows (handled above already)
            if i <= 2:
                i += 1
                continue
            story.append(Paragraph(title_text, section))
            section_started = True
            i += 1
            continue
        # Body row
        current_table_rows.append([str(c) if c is not None else "" for c in r])
        i += 1
    _flush_table(None)

    doc.build(story)
    buf.seek(0)
    return buf
